// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: protochain/solana/program/system/v1/service.proto

package system_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_Create_FullMethodName                 = "/protochain.solana.program.system.v1.Service/Create"
	Service_Transfer_FullMethodName               = "/protochain.solana.program.system.v1.Service/Transfer"
	Service_Allocate_FullMethodName               = "/protochain.solana.program.system.v1.Service/Allocate"
	Service_Assign_FullMethodName                 = "/protochain.solana.program.system.v1.Service/Assign"
	Service_CreateWithSeed_FullMethodName         = "/protochain.solana.program.system.v1.Service/CreateWithSeed"
	Service_BuildMemo_FullMethodName              = "/protochain.solana.program.system.v1.Service/BuildMemo"
	Service_AllocateWithSeed_FullMethodName       = "/protochain.solana.program.system.v1.Service/AllocateWithSeed"
	Service_AssignWithSeed_FullMethodName         = "/protochain.solana.program.system.v1.Service/AssignWithSeed"
	Service_TransferWithSeed_FullMethodName       = "/protochain.solana.program.system.v1.Service/TransferWithSeed"
	Service_InitializeNonceAccount_FullMethodName = "/protochain.solana.program.system.v1.Service/InitializeNonceAccount"
	Service_AuthorizeNonceAccount_FullMethodName  = "/protochain.solana.program.system.v1.Service/AuthorizeNonceAccount"
	Service_WithdrawNonceAccount_FullMethodName   = "/protochain.solana.program.system.v1.Service/WithdrawNonceAccount"
	Service_AdvanceNonceAccount_FullMethodName    = "/protochain.solana.program.system.v1.Service/AdvanceNonceAccount"
	Service_UpgradeNonceAccount_FullMethodName    = "/protochain.solana.program.system.v1.Service/UpgradeNonceAccount"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// Core system program operations - all return composable instructions
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error)
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
	Assign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*AssignResponse, error)
	CreateWithSeed(ctx context.Context, in *CreateWithSeedRequest, opts ...grpc.CallOption) (*CreateWithSeedResponse, error)
	BuildMemo(ctx context.Context, in *BuildMemoRequest, opts ...grpc.CallOption) (*BuildMemoResponse, error)
	// Extended system program operations
	AllocateWithSeed(ctx context.Context, in *AllocateWithSeedRequest, opts ...grpc.CallOption) (*AllocateWithSeedResponse, error)
	AssignWithSeed(ctx context.Context, in *AssignWithSeedRequest, opts ...grpc.CallOption) (*AssignWithSeedResponse, error)
	TransferWithSeed(ctx context.Context, in *TransferWithSeedRequest, opts ...grpc.CallOption) (*TransferWithSeedResponse, error)
	InitializeNonceAccount(ctx context.Context, in *InitializeNonceAccountRequest, opts ...grpc.CallOption) (*InitializeNonceAccountResponse, error)
	AuthorizeNonceAccount(ctx context.Context, in *AuthorizeNonceAccountRequest, opts ...grpc.CallOption) (*AuthorizeNonceAccountResponse, error)
	WithdrawNonceAccount(ctx context.Context, in *WithdrawNonceAccountRequest, opts ...grpc.CallOption) (*WithdrawNonceAccountResponse, error)
	AdvanceNonceAccount(ctx context.Context, in *AdvanceNonceAccountRequest, opts ...grpc.CallOption) (*AdvanceNonceAccountResponse, error)
	UpgradeNonceAccount(ctx context.Context, in *UpgradeNonceAccountRequest, opts ...grpc.CallOption) (*UpgradeNonceAccountResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, Service_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Transfer(ctx context.Context, in *TransferRequest, opts ...grpc.CallOption) (*TransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferResponse)
	err := c.cc.Invoke(ctx, Service_Transfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, Service_Allocate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Assign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*AssignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignResponse)
	err := c.cc.Invoke(ctx, Service_Assign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateWithSeed(ctx context.Context, in *CreateWithSeedRequest, opts ...grpc.CallOption) (*CreateWithSeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWithSeedResponse)
	err := c.cc.Invoke(ctx, Service_CreateWithSeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) BuildMemo(ctx context.Context, in *BuildMemoRequest, opts ...grpc.CallOption) (*BuildMemoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildMemoResponse)
	err := c.cc.Invoke(ctx, Service_BuildMemo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AllocateWithSeed(ctx context.Context, in *AllocateWithSeedRequest, opts ...grpc.CallOption) (*AllocateWithSeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateWithSeedResponse)
	err := c.cc.Invoke(ctx, Service_AllocateWithSeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AssignWithSeed(ctx context.Context, in *AssignWithSeedRequest, opts ...grpc.CallOption) (*AssignWithSeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignWithSeedResponse)
	err := c.cc.Invoke(ctx, Service_AssignWithSeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) TransferWithSeed(ctx context.Context, in *TransferWithSeedRequest, opts ...grpc.CallOption) (*TransferWithSeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferWithSeedResponse)
	err := c.cc.Invoke(ctx, Service_TransferWithSeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) InitializeNonceAccount(ctx context.Context, in *InitializeNonceAccountRequest, opts ...grpc.CallOption) (*InitializeNonceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeNonceAccountResponse)
	err := c.cc.Invoke(ctx, Service_InitializeNonceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AuthorizeNonceAccount(ctx context.Context, in *AuthorizeNonceAccountRequest, opts ...grpc.CallOption) (*AuthorizeNonceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeNonceAccountResponse)
	err := c.cc.Invoke(ctx, Service_AuthorizeNonceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) WithdrawNonceAccount(ctx context.Context, in *WithdrawNonceAccountRequest, opts ...grpc.CallOption) (*WithdrawNonceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawNonceAccountResponse)
	err := c.cc.Invoke(ctx, Service_WithdrawNonceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) AdvanceNonceAccount(ctx context.Context, in *AdvanceNonceAccountRequest, opts ...grpc.CallOption) (*AdvanceNonceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdvanceNonceAccountResponse)
	err := c.cc.Invoke(ctx, Service_AdvanceNonceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpgradeNonceAccount(ctx context.Context, in *UpgradeNonceAccountRequest, opts ...grpc.CallOption) (*UpgradeNonceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpgradeNonceAccountResponse)
	err := c.cc.Invoke(ctx, Service_UpgradeNonceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	// Core system program operations - all return composable instructions
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Transfer(context.Context, *TransferRequest) (*TransferResponse, error)
	Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error)
	Assign(context.Context, *AssignRequest) (*AssignResponse, error)
	CreateWithSeed(context.Context, *CreateWithSeedRequest) (*CreateWithSeedResponse, error)
	BuildMemo(context.Context, *BuildMemoRequest) (*BuildMemoResponse, error)
	// Extended system program operations
	AllocateWithSeed(context.Context, *AllocateWithSeedRequest) (*AllocateWithSeedResponse, error)
	AssignWithSeed(context.Context, *AssignWithSeedRequest) (*AssignWithSeedResponse, error)
	TransferWithSeed(context.Context, *TransferWithSeedRequest) (*TransferWithSeedResponse, error)
	InitializeNonceAccount(context.Context, *InitializeNonceAccountRequest) (*InitializeNonceAccountResponse, error)
	AuthorizeNonceAccount(context.Context, *AuthorizeNonceAccountRequest) (*AuthorizeNonceAccountResponse, error)
	WithdrawNonceAccount(context.Context, *WithdrawNonceAccountRequest) (*WithdrawNonceAccountResponse, error)
	AdvanceNonceAccount(context.Context, *AdvanceNonceAccountRequest) (*AdvanceNonceAccountResponse, error)
	UpgradeNonceAccount(context.Context, *UpgradeNonceAccountRequest) (*UpgradeNonceAccountResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedServiceServer) Transfer(context.Context, *TransferRequest) (*TransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Transfer not implemented")
}
func (UnimplementedServiceServer) Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedServiceServer) Assign(context.Context, *AssignRequest) (*AssignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Assign not implemented")
}
func (UnimplementedServiceServer) CreateWithSeed(context.Context, *CreateWithSeedRequest) (*CreateWithSeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWithSeed not implemented")
}
func (UnimplementedServiceServer) BuildMemo(context.Context, *BuildMemoRequest) (*BuildMemoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildMemo not implemented")
}
func (UnimplementedServiceServer) AllocateWithSeed(context.Context, *AllocateWithSeedRequest) (*AllocateWithSeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllocateWithSeed not implemented")
}
func (UnimplementedServiceServer) AssignWithSeed(context.Context, *AssignWithSeedRequest) (*AssignWithSeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignWithSeed not implemented")
}
func (UnimplementedServiceServer) TransferWithSeed(context.Context, *TransferWithSeedRequest) (*TransferWithSeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferWithSeed not implemented")
}
func (UnimplementedServiceServer) InitializeNonceAccount(context.Context, *InitializeNonceAccountRequest) (*InitializeNonceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitializeNonceAccount not implemented")
}
func (UnimplementedServiceServer) AuthorizeNonceAccount(context.Context, *AuthorizeNonceAccountRequest) (*AuthorizeNonceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeNonceAccount not implemented")
}
func (UnimplementedServiceServer) WithdrawNonceAccount(context.Context, *WithdrawNonceAccountRequest) (*WithdrawNonceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawNonceAccount not implemented")
}
func (UnimplementedServiceServer) AdvanceNonceAccount(context.Context, *AdvanceNonceAccountRequest) (*AdvanceNonceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdvanceNonceAccount not implemented")
}
func (UnimplementedServiceServer) UpgradeNonceAccount(context.Context, *UpgradeNonceAccountRequest) (*UpgradeNonceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpgradeNonceAccount not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Transfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Transfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Transfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Transfer(ctx, req.(*TransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Allocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Assign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Assign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Assign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Assign(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateWithSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWithSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateWithSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateWithSeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateWithSeed(ctx, req.(*CreateWithSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_BuildMemo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildMemoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).BuildMemo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_BuildMemo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).BuildMemo(ctx, req.(*BuildMemoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AllocateWithSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateWithSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AllocateWithSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AllocateWithSeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AllocateWithSeed(ctx, req.(*AllocateWithSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AssignWithSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignWithSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AssignWithSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AssignWithSeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AssignWithSeed(ctx, req.(*AssignWithSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_TransferWithSeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferWithSeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).TransferWithSeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_TransferWithSeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).TransferWithSeed(ctx, req.(*TransferWithSeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_InitializeNonceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeNonceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).InitializeNonceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_InitializeNonceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).InitializeNonceAccount(ctx, req.(*InitializeNonceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AuthorizeNonceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeNonceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AuthorizeNonceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AuthorizeNonceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AuthorizeNonceAccount(ctx, req.(*AuthorizeNonceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_WithdrawNonceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawNonceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).WithdrawNonceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_WithdrawNonceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).WithdrawNonceAccount(ctx, req.(*WithdrawNonceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_AdvanceNonceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvanceNonceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).AdvanceNonceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_AdvanceNonceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).AdvanceNonceAccount(ctx, req.(*AdvanceNonceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpgradeNonceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradeNonceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpgradeNonceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_UpgradeNonceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpgradeNonceAccount(ctx, req.(*UpgradeNonceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protochain.solana.program.system.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Service_Create_Handler,
		},
		{
			MethodName: "Transfer",
			Handler:    _Service_Transfer_Handler,
		},
		{
			MethodName: "Allocate",
			Handler:    _Service_Allocate_Handler,
		},
		{
			MethodName: "Assign",
			Handler:    _Service_Assign_Handler,
		},
		{
			MethodName: "CreateWithSeed",
			Handler:    _Service_CreateWithSeed_Handler,
		},
		{
			MethodName: "BuildMemo",
			Handler:    _Service_BuildMemo_Handler,
		},
		{
			MethodName: "AllocateWithSeed",
			Handler:    _Service_AllocateWithSeed_Handler,
		},
		{
			MethodName: "AssignWithSeed",
			Handler:    _Service_AssignWithSeed_Handler,
		},
		{
			MethodName: "TransferWithSeed",
			Handler:    _Service_TransferWithSeed_Handler,
		},
		{
			MethodName: "InitializeNonceAccount",
			Handler:    _Service_InitializeNonceAccount_Handler,
		},
		{
			MethodName: "AuthorizeNonceAccount",
			Handler:    _Service_AuthorizeNonceAccount_Handler,
		},
		{
			MethodName: "WithdrawNonceAccount",
			Handler:    _Service_WithdrawNonceAccount_Handler,
		},
		{
			MethodName: "AdvanceNonceAccount",
			Handler:    _Service_AdvanceNonceAccount_Handler,
		},
		{
			MethodName: "UpgradeNonceAccount",
			Handler:    _Service_UpgradeNonceAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protochain/solana/program/system/v1/service.proto",
}
