// Code generated by protoc-gen-passivgo. DO NOT EDIT.
// source: protochain/solana/program/system/v1/service.proto
//
// This auto-generated file is a gRPC service adaptor.
//
// It adapts our Go business logic to the gRPC service definitions.
// The service interface is defined separately for clean architecture,
// and this adaptor connects that interface with gRPC transport.
package system_v1

import (
	context "context"
	trace "go.opentelemetry.io/otel/trace"
	grpc "google.golang.org/grpc"
)

// Ensure that ServiceGRPCAdaptor implements the ServiceServer interface
var _ ServiceServer = &ServiceGRPCAdaptor{}

// ServiceProviderName returns the service provider name
func (a *ServiceGRPCAdaptor) ServiceProviderName() string {
	return ServiceServiceProviderName
}

// RegisterWithGRPCServer registers this adaptor with the gRPC server
func (a *ServiceGRPCAdaptor) RegisterWithGRPCServer(s grpc.ServiceRegistrar) {
	RegisterServiceServer(s, a)
}

// ServiceGRPCAdaptor exposes an implementation of the Service interface over gRPC
type ServiceGRPCAdaptor struct {
	UnimplementedServiceServer
	tracer  trace.Tracer
	service ServiceInterface
}

// NewServiceGRPCAdaptor constructs a new ServiceGRPCAdaptor
func NewServiceGRPCAdaptor(
	tracer trace.Tracer,
	service ServiceInterface,
) *ServiceGRPCAdaptor {
	return &ServiceGRPCAdaptor{
		tracer:  tracer,
		service: service,
	}
}

// Create exposes the Create method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) Create(ctx context.Context, request *CreateRequest) (*CreateResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.Create",
	)
	defer span.End()

	// call the service interface implementation
	createResponse, err := a.service.Create(ctx, request)
	if err != nil {
		return nil, err
	}

	return createResponse, nil
}

// Transfer exposes the Transfer method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) Transfer(ctx context.Context, request *TransferRequest) (*TransferResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.Transfer",
	)
	defer span.End()

	// call the service interface implementation
	transferResponse, err := a.service.Transfer(ctx, request)
	if err != nil {
		return nil, err
	}

	return transferResponse, nil
}

// Allocate exposes the Allocate method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) Allocate(ctx context.Context, request *AllocateRequest) (*AllocateResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.Allocate",
	)
	defer span.End()

	// call the service interface implementation
	allocateResponse, err := a.service.Allocate(ctx, request)
	if err != nil {
		return nil, err
	}

	return allocateResponse, nil
}

// Assign exposes the Assign method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) Assign(ctx context.Context, request *AssignRequest) (*AssignResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.Assign",
	)
	defer span.End()

	// call the service interface implementation
	assignResponse, err := a.service.Assign(ctx, request)
	if err != nil {
		return nil, err
	}

	return assignResponse, nil
}

// CreateWithSeed exposes the CreateWithSeed method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) CreateWithSeed(ctx context.Context, request *CreateWithSeedRequest) (*CreateWithSeedResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.CreateWithSeed",
	)
	defer span.End()

	// call the service interface implementation
	createWithSeedResponse, err := a.service.CreateWithSeed(ctx, request)
	if err != nil {
		return nil, err
	}

	return createWithSeedResponse, nil
}

// BuildMemo exposes the BuildMemo method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) BuildMemo(ctx context.Context, request *BuildMemoRequest) (*BuildMemoResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.BuildMemo",
	)
	defer span.End()

	// call the service interface implementation
	buildMemoResponse, err := a.service.BuildMemo(ctx, request)
	if err != nil {
		return nil, err
	}

	return buildMemoResponse, nil
}

// AllocateWithSeed exposes the AllocateWithSeed method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) AllocateWithSeed(ctx context.Context, request *AllocateWithSeedRequest) (*AllocateWithSeedResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.AllocateWithSeed",
	)
	defer span.End()

	// call the service interface implementation
	allocateWithSeedResponse, err := a.service.AllocateWithSeed(ctx, request)
	if err != nil {
		return nil, err
	}

	return allocateWithSeedResponse, nil
}

// AssignWithSeed exposes the AssignWithSeed method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) AssignWithSeed(ctx context.Context, request *AssignWithSeedRequest) (*AssignWithSeedResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.AssignWithSeed",
	)
	defer span.End()

	// call the service interface implementation
	assignWithSeedResponse, err := a.service.AssignWithSeed(ctx, request)
	if err != nil {
		return nil, err
	}

	return assignWithSeedResponse, nil
}

// TransferWithSeed exposes the TransferWithSeed method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) TransferWithSeed(ctx context.Context, request *TransferWithSeedRequest) (*TransferWithSeedResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.TransferWithSeed",
	)
	defer span.End()

	// call the service interface implementation
	transferWithSeedResponse, err := a.service.TransferWithSeed(ctx, request)
	if err != nil {
		return nil, err
	}

	return transferWithSeedResponse, nil
}

// InitializeNonceAccount exposes the InitializeNonceAccount method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) InitializeNonceAccount(ctx context.Context, request *InitializeNonceAccountRequest) (*InitializeNonceAccountResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.InitializeNonceAccount",
	)
	defer span.End()

	// call the service interface implementation
	initializeNonceAccountResponse, err := a.service.InitializeNonceAccount(ctx, request)
	if err != nil {
		return nil, err
	}

	return initializeNonceAccountResponse, nil
}

// AuthorizeNonceAccount exposes the AuthorizeNonceAccount method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) AuthorizeNonceAccount(ctx context.Context, request *AuthorizeNonceAccountRequest) (*AuthorizeNonceAccountResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.AuthorizeNonceAccount",
	)
	defer span.End()

	// call the service interface implementation
	authorizeNonceAccountResponse, err := a.service.AuthorizeNonceAccount(ctx, request)
	if err != nil {
		return nil, err
	}

	return authorizeNonceAccountResponse, nil
}

// WithdrawNonceAccount exposes the WithdrawNonceAccount method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) WithdrawNonceAccount(ctx context.Context, request *WithdrawNonceAccountRequest) (*WithdrawNonceAccountResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.WithdrawNonceAccount",
	)
	defer span.End()

	// call the service interface implementation
	withdrawNonceAccountResponse, err := a.service.WithdrawNonceAccount(ctx, request)
	if err != nil {
		return nil, err
	}

	return withdrawNonceAccountResponse, nil
}

// AdvanceNonceAccount exposes the AdvanceNonceAccount method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) AdvanceNonceAccount(ctx context.Context, request *AdvanceNonceAccountRequest) (*AdvanceNonceAccountResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.AdvanceNonceAccount",
	)
	defer span.End()

	// call the service interface implementation
	advanceNonceAccountResponse, err := a.service.AdvanceNonceAccount(ctx, request)
	if err != nil {
		return nil, err
	}

	return advanceNonceAccountResponse, nil
}

// UpgradeNonceAccount exposes the UpgradeNonceAccount method of the Service interface over gRPC
func (a *ServiceGRPCAdaptor) UpgradeNonceAccount(ctx context.Context, request *UpgradeNonceAccountRequest) (*UpgradeNonceAccountResponse, error) {
	ctx, span := a.tracer.Start(
		ctx,
		ServiceServiceProviderName+"GRPCAdaptor.UpgradeNonceAccount",
	)
	defer span.End()

	// call the service interface implementation
	upgradeNonceAccountResponse, err := a.service.UpgradeNonceAccount(ctx, request)
	if err != nil {
		return nil, err
	}

	return upgradeNonceAccountResponse, nil
}
