// @generated
// This file is @generated by prost-build.
/// Corresponds to the Metaplex DataV2 Rust struct used for on-chain metadata.
/// See: <https://github.com/metaplex-foundation/mpl-token-metadata>
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetaplexTokenMetadata {
    /// The full name of the token (e.g. "USD Coin").
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    /// The ticker/symbol of the token (e.g. "USDC").
    #[prost(string, tag="2")]
    pub symbol: ::prost::alloc::string::String,
    /// URL pointing to an off-chain JSON file (Arweave, IPFS, or HTTPS).
    /// Follows the Metaplex standard for displaying images and descriptions in wallets.
    /// See: <https://developers.metaplex.com/smart-contracts/token-metadata/token-standard>
    #[prost(string, tag="3")]
    pub uri: ::prost::alloc::string::String,
    /// Royalties in basis points (100 = 1%).
    #[prost(uint32, tag="4")]
    pub seller_fee_basis_points: u32,
    /// List of creators and their royalty shares.
    #[prost(message, repeated, tag="5")]
    pub creators: ::prost::alloc::vec::Vec<MetaplexCreator>,
    /// Optional collection information grouping this asset.
    #[prost(message, optional, tag="6")]
    pub collection: ::core::option::Option<MetaplexCollection>,
    /// Optional usage restrictions/rules (primarily for gaming or limited-use assets).
    #[prost(message, optional, tag="7")]
    pub uses: ::core::option::Option<MetaplexUses>,
}
/// Creator information for royalties.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetaplexCreator {
    /// The public key of the creator (Base58 encoded string).
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    /// Whether the creator has signed the metadata (verified).
    #[prost(bool, tag="2")]
    pub verified: bool,
    /// The percentage of royalties this creator receives (0-100).
    #[prost(uint32, tag="3")]
    pub share: u32,
}
/// Collection grouping info.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetaplexCollection {
    /// Whether the collection has been verified by the authority.
    #[prost(bool, tag="1")]
    pub verified: bool,
    /// The mint address of the collection parent NFT (Base58 encoded string).
    #[prost(string, tag="2")]
    pub key: ::prost::alloc::string::String,
}
/// Usage rules for the asset.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MetaplexUses {
    /// How the asset is consumed.
    #[prost(enumeration="metaplex_uses::UseMethod", tag="1")]
    pub use_method: i32,
    /// Remaining number of uses.
    #[prost(uint64, tag="2")]
    pub remaining: u64,
    /// Total allowed uses.
    #[prost(uint64, tag="3")]
    pub total: u64,
}
/// Nested message and enum types in `MetaplexUses`.
pub mod metaplex_uses {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum UseMethod {
        /// Default unspecified value.
        Unspecified = 0,
        /// The asset is burned after use.
        Burn = 1,
        /// The asset can be used multiple times.
        Multiple = 2,
        /// The asset can be used once.
        Single = 3,
    }
    impl UseMethod {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                UseMethod::Unspecified => "USE_METHOD_UNSPECIFIED",
                UseMethod::Burn => "USE_METHOD_BURN",
                UseMethod::Multiple => "USE_METHOD_MULTIPLE",
                UseMethod::Single => "USE_METHOD_SINGLE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "USE_METHOD_UNSPECIFIED" => Some(Self::Unspecified),
                "USE_METHOD_BURN" => Some(Self::Burn),
                "USE_METHOD_MULTIPLE" => Some(Self::Multiple),
                "USE_METHOD_SINGLE" => Some(Self::Single),
                _ => None,
            }
        }
    }
}
/// Configuration for Token-2022 Metadata Extension
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Token2022ExtensionMetadata {
    /// The account that serves as the "source of truth" for metadata.
    /// For the most common modern setup, this can be left empty to default
    /// to the mint_pub_key.
    #[prost(string, tag="1")]
    pub metadata_address: ::prost::alloc::string::String,
    /// The authority allowed to sign and update the metadata fields
    /// (name, symbol, uri, etc).
    /// If not provided, this defaults to the mint_authority_pub_key.
    #[prost(string, tag="2")]
    pub update_authority_pub_key: ::prost::alloc::string::String,
    /// The full name of the token (e.g. "USD Coin").
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    /// The ticker/symbol of the token (e.g. "USDC").
    #[prost(string, tag="4")]
    pub symbol: ::prost::alloc::string::String,
    /// URL pointing to an off-chain JSON file (IPFS/Arweave/HTTPS).
    /// Follows the Metaplex standard for displaying images and descriptions in wallets.
    /// See: <https://developers.metaplex.com/smart-contracts/token-metadata/token-standard>
    #[prost(string, tag="5")]
    pub uri: ::prost::alloc::string::String,
    /// Custom key-value pairs stored directly on the blockchain.
    /// Use this for data that smart contracts need to read (e.g., "rarity": "mythic").
    /// Note: Adding many items increases the rent cost of the Mint account.
    #[prost(map="string, string", tag="6")]
    pub additional_metadata: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
/// Wrapper for Token-2022 extensions.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Token2022Extension {
    #[prost(oneof="token2022_extension::Extension", tags="1")]
    pub extension: ::core::option::Option<token2022_extension::Extension>,
}
/// Nested message and enum types in `Token2022Extension`.
pub mod token2022_extension {
    #[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Extension {
        /// Other extension support COMING SOON!
        /// protochain.solana.program.token.v1.TransferHookConfig transfer_hook = 2;
        /// protochain.solana.program.token.v1.TransferFeeConfig transfer_fee = 3;
        /// protochain.solana.program.token.v1.InterestBearingConfig interest_bearing = 4;
        /// string permanent_delegate_pub_key = 5;
        #[prost(message, tag="1")]
        Metadata(super::Token2022ExtensionMetadata),
    }
}
/// Request to initialise a Token-2022 mint with optional extensions.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitialiseToken2022MintRequest {
    /// The public key of the Mint account to be initialized.
    #[prost(string, tag="1")]
    pub mint_pub_key: ::prost::alloc::string::String,
    /// The authority that can mint new tokens.
    #[prost(string, tag="2")]
    pub mint_authority_pub_key: ::prost::alloc::string::String,
    /// Optional authority that can freeze token accounts.
    #[prost(string, tag="3")]
    pub freeze_authority_pub_key: ::prost::alloc::string::String,
    /// Number of base 10 digits to the right of the decimal place.
    /// Common values: 9 for SOL-like tokens, 6 for USDC-like tokens, 0 for NFTs.
    #[prost(uint32, tag="4")]
    pub decimals: u32,
    /// Ordered list of extensions to enable on the mint.
    /// NOTE: If an extension is not included here during initialization,
    /// it cannot be added to the mint account later.
    #[prost(message, repeated, tag="5")]
    pub extensions: ::prost::alloc::vec::Vec<Token2022Extension>,
}
/// Response containing Token-2022 InitialiseMint instructions.
/// Multiple instructions are returned when extensions are requested
/// (e.g. metadata pointer initialisation precedes initialize_mint,
/// and token-metadata initialisation follows it).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitialiseToken2022MintResponse {
    #[prost(message, repeated, tag="1")]
    pub instructions: ::prost::alloc::vec::Vec<super::super::super::transaction::v1::SolanaInstruction>,
}
/// Request to initialise a legacy SPL Token mint.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitialiseSplTokenMintRequest {
    /// The public key of the Mint account to be initialized.
    #[prost(string, tag="1")]
    pub mint_pub_key: ::prost::alloc::string::String,
    /// The authority that can mint new tokens.
    #[prost(string, tag="2")]
    pub mint_authority_pub_key: ::prost::alloc::string::String,
    /// Optional authority that can freeze token accounts.
    #[prost(string, tag="3")]
    pub freeze_authority_pub_key: ::prost::alloc::string::String,
    /// Number of base 10 digits to the right of the decimal place.
    /// Common values: 9 for SOL-like tokens, 6 for USDC-like tokens, 0 for NFTs.
    #[prost(uint32, tag="4")]
    pub decimals: u32,
    /// The public key of the account paying for the Metaplex metadata PDA creation.
    /// Required when metadata is provided.
    #[prost(string, tag="5")]
    pub payer_pub_key: ::prost::alloc::string::String,
    /// Optional Metaplex metadata to attach to the mint via the Metaplex Token Metadata program.
    /// When provided, a CreateMetadataAccountV3 instruction is appended after initialize_mint.
    #[prost(message, optional, tag="6")]
    pub metadata: ::core::option::Option<MetaplexTokenMetadata>,
}
/// Response containing SPL Token initialise_mint instructions.
/// When metadata is requested, additional Metaplex instructions follow the base initialize_mint.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InitialiseSplTokenMintResponse {
    #[prost(message, repeated, tag="1")]
    pub instructions: ::prost::alloc::vec::Vec<super::super::super::transaction::v1::SolanaInstruction>,
}
/// Request for the minimum rent and space required for a Token-2022 mint account.
/// Provide the same extension set you intend to pass to InitialiseToken2022Mint so that
/// the returned lamports and space values are consistent with each other.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCurrentMinRentForToken2022MintAccountRequest {
    /// Ordered list of extensions to enable on the mint.
    /// Must match the extensions you will pass to InitialiseToken2022Mint.
    /// If empty, results are based on a base Token-2022 mint with no extensions.
    /// Duplicates are rejected.
    #[prost(message, repeated, tag="1")]
    pub extensions: ::prost::alloc::vec::Vec<Token2022Extension>,
}
/// Rent and space for a Token-2022 mint account with the requested extensions.
/// Pass both fields directly to the System Program's CreateAccount instruction
/// before calling InitialiseToken2022Mint.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetCurrentMinRentForToken2022MintAccountResponse {
    /// Minimum lamports required for the account to be rent-exempt after all
    /// extensions (including variable-length metadata) are fully initialised.
    #[prost(uint64, tag="1")]
    pub lamports: u64,
    /// Initial account size in bytes for System::CreateAccount.
    /// Covers the base mint layout and fixed-size extension pods only.
    #[prost(uint64, tag="2")]
    pub space: u64,
}
/// Request for the minimum rent and space required for a legacy SPL Token mint account.
/// No parameters are needed because SPL Token mints are always exactly Mint::LEN (82 bytes).
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetCurrentMinRentForSplTokenMintAccountRequest {
}
/// Rent and space for a legacy SPL Token mint account.
/// Pass both fields directly to the System Program's CreateAccount instruction
/// before calling InitialiseSPLTokenMint.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetCurrentMinRentForSplTokenMintAccountResponse {
    /// Minimum lamports required for the account to be rent-exempt.
    #[prost(uint64, tag="1")]
    pub lamports: u64,
    /// Account size in bytes to allocate (always Mint::LEN = 82 bytes).
    #[prost(uint64, tag="2")]
    pub space: u64,
}
/// Request to parse mint account
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseMintRequest {
    #[prost(string, tag="1")]
    pub account_address: ::prost::alloc::string::String,
}
/// Response with parsed mint data.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseMintResponse {
    /// Base mint account fields (authority, decimals, supply, etc.).
    #[prost(message, optional, tag="1")]
    pub mint: ::core::option::Option<MintInfo>,
    /// The token program that owns this mint account (Legacy SPL Token or Token-2022).
    #[prost(enumeration="super::super::super::r#type::v1::TokenProgram", tag="2")]
    pub token_program: i32,
    /// Extensions present on the mint account.
    /// Only populated for Token-2022 mints that have extensions configured.
    #[prost(message, repeated, tag="3")]
    pub extensions: ::prost::alloc::vec::Vec<Token2022Extension>,
}
/// Structured mint account information
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MintInfo {
    #[prost(string, tag="1")]
    pub mint_authority_pub_key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub freeze_authority_pub_key: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub decimals: u32,
    #[prost(string, tag="4")]
    pub supply: ::prost::alloc::string::String,
    #[prost(bool, tag="5")]
    pub is_initialized: bool,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MemoTransferConfig {
    /// Require every inbound transfer into the account to include a memo.
    #[prost(bool, tag="1")]
    pub require_incoming_memo: bool,
}
/// Request to get current rent for holding account
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetCurrentMinRentForHoldingAccountRequest {
    /// optional, defaults to false
    #[prost(message, optional, tag="1")]
    pub memo_transfer_config: ::core::option::Option<MemoTransferConfig>,
}
/// Response with current rent amount for holding account
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetCurrentMinRentForHoldingAccountResponse {
    #[prost(uint64, tag="1")]
    pub lamports: u64,
}
/// Request to create and initialize a holding account in one call
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateHoldingAccountRequest {
    /// Account paying for creation (signer)
    #[prost(string, tag="1")]
    pub payer: ::prost::alloc::string::String,
    /// Owner of the holding account
    #[prost(string, tag="2")]
    pub owner_pub_key: ::prost::alloc::string::String,
    /// Mint this account will hold
    #[prost(string, tag="3")]
    pub mint_pub_key: ::prost::alloc::string::String,
    #[prost(enumeration="super::super::super::r#type::v1::TokenProgram", tag="4")]
    pub token_program: i32,
    /// optional, defaults to false
    #[prost(message, optional, tag="5")]
    pub memo_transfer_config: ::core::option::Option<MemoTransferConfig>,
}
/// Response containing both create and initialize instructions
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateHoldingAccountResponse {
    #[prost(message, repeated, tag="1")]
    pub instructions: ::prost::alloc::vec::Vec<super::super::super::transaction::v1::SolanaInstruction>,
}
/// Request to create and initialize a mint account in one call
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateMintRequest {
    /// System program create fields
    ///
    /// Account paying for creation (signer)
    #[prost(string, tag="1")]
    pub payer: ::prost::alloc::string::String,
    /// Token program initialize mint fields
    ///
    /// Same as new_account for validation
    #[prost(string, tag="2")]
    pub mint_pub_key: ::prost::alloc::string::String,
    /// Mint authority
    #[prost(string, tag="3")]
    pub mint_authority_pub_key: ::prost::alloc::string::String,
    /// Freeze authority (optional)
    #[prost(string, tag="4")]
    pub freeze_authority_pub_key: ::prost::alloc::string::String,
    /// Mint decimals
    #[prost(uint32, tag="5")]
    pub decimals: u32,
    #[prost(enumeration="super::super::super::r#type::v1::TokenProgram", tag="6")]
    pub token_program: i32,
}
/// Response containing both create and initialize instructions
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateMintResponse {
    #[prost(message, repeated, tag="1")]
    pub instructions: ::prost::alloc::vec::Vec<super::super::super::transaction::v1::SolanaInstruction>,
}
/// Request to mint tokens to a token account
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MintRequest {
    /// The mint to mint from
    #[prost(string, tag="1")]
    pub mint_pub_key: ::prost::alloc::string::String,
    /// Token account to mint to
    #[prost(string, tag="2")]
    pub destination_account_pub_key: ::prost::alloc::string::String,
    /// Authority that can mint tokens
    #[prost(string, tag="3")]
    pub mint_authority_pub_key: ::prost::alloc::string::String,
    /// Amount to mint (as string to handle large numbers)
    #[prost(string, tag="4")]
    pub amount: ::prost::alloc::string::String,
    /// Expected decimals for validation
    #[prost(uint32, tag="5")]
    pub decimals: u32,
}
/// Response containing Mint instruction
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MintResponse {
    #[prost(message, optional, tag="1")]
    pub instruction: ::core::option::Option<super::super::super::transaction::v1::SolanaInstruction>,
}
include!("protochain.solana.program.token.v1.tonic.rs");
// @@protoc_insertion_point(module)