// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/type/v1/commitment_level.proto

package solana_type_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommitmentLevel represents the different levels of transaction confirmation
// available in the Solana blockchain network. These levels provide different
// trade-offs between speed and reliability of transaction confirmation.
type CommitmentLevel int32

const (
	// UNSPECIFIED allows services to use their default commitment level.
	// This provides backward compatibility and lets services choose appropriate defaults.
	CommitmentLevel_COMMITMENT_LEVEL_UNSPECIFIED CommitmentLevel = 0
	// PROCESSED means the transaction has been processed by the leader and included
	// in a block, but the block has not yet been confirmed by the cluster.
	// This is the fastest option but least reliable for finality guarantees.
	CommitmentLevel_COMMITMENT_LEVEL_PROCESSED CommitmentLevel = 1
	// CONFIRMED means the transaction has been processed and the block containing
	// the transaction has been confirmed by a supermajority of the cluster.
	// This provides a good balance between speed and reliability.
	CommitmentLevel_COMMITMENT_LEVEL_CONFIRMED CommitmentLevel = 2
	// FINALIZED means the transaction has been processed, confirmed, and the block
	// containing the transaction has been finalized by the cluster (rooted).
	// This is the slowest but most reliable option for absolute finality.
	CommitmentLevel_COMMITMENT_LEVEL_FINALIZED CommitmentLevel = 3
)

// Enum value maps for CommitmentLevel.
var (
	CommitmentLevel_name = map[int32]string{
		0: "COMMITMENT_LEVEL_UNSPECIFIED",
		1: "COMMITMENT_LEVEL_PROCESSED",
		2: "COMMITMENT_LEVEL_CONFIRMED",
		3: "COMMITMENT_LEVEL_FINALIZED",
	}
	CommitmentLevel_value = map[string]int32{
		"COMMITMENT_LEVEL_UNSPECIFIED": 0,
		"COMMITMENT_LEVEL_PROCESSED":   1,
		"COMMITMENT_LEVEL_CONFIRMED":   2,
		"COMMITMENT_LEVEL_FINALIZED":   3,
	}
)

func (x CommitmentLevel) Enum() *CommitmentLevel {
	p := new(CommitmentLevel)
	*p = x
	return p
}

func (x CommitmentLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommitmentLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_protochain_solana_type_v1_commitment_level_proto_enumTypes[0].Descriptor()
}

func (CommitmentLevel) Type() protoreflect.EnumType {
	return &file_protochain_solana_type_v1_commitment_level_proto_enumTypes[0]
}

func (x CommitmentLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommitmentLevel.Descriptor instead.
func (CommitmentLevel) EnumDescriptor() ([]byte, []int) {
	return file_protochain_solana_type_v1_commitment_level_proto_rawDescGZIP(), []int{0}
}

var File_protochain_solana_type_v1_commitment_level_proto protoreflect.FileDescriptor

const file_protochain_solana_type_v1_commitment_level_proto_rawDesc = "" +
	"\n" +
	"0protochain/solana/type/v1/commitment_level.proto\x12\x19protochain.solana.type.v1*\x93\x01\n" +
	"\x0fCommitmentLevel\x12 \n" +
	"\x1cCOMMITMENT_LEVEL_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCOMMITMENT_LEVEL_PROCESSED\x10\x01\x12\x1e\n" +
	"\x1aCOMMITMENT_LEVEL_CONFIRMED\x10\x02\x12\x1e\n" +
	"\x1aCOMMITMENT_LEVEL_FINALIZED\x10\x03BQZOgithub.com/meshtrade/protochain/lib/go/protochain/solana/type/v1;solana_type_v1b\x06proto3"

var (
	file_protochain_solana_type_v1_commitment_level_proto_rawDescOnce sync.Once
	file_protochain_solana_type_v1_commitment_level_proto_rawDescData []byte
)

func file_protochain_solana_type_v1_commitment_level_proto_rawDescGZIP() []byte {
	file_protochain_solana_type_v1_commitment_level_proto_rawDescOnce.Do(func() {
		file_protochain_solana_type_v1_commitment_level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_type_v1_commitment_level_proto_rawDesc), len(file_protochain_solana_type_v1_commitment_level_proto_rawDesc)))
	})
	return file_protochain_solana_type_v1_commitment_level_proto_rawDescData
}

var file_protochain_solana_type_v1_commitment_level_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protochain_solana_type_v1_commitment_level_proto_goTypes = []any{
	(CommitmentLevel)(0), // 0: protochain.solana.type.v1.CommitmentLevel
}
var file_protochain_solana_type_v1_commitment_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protochain_solana_type_v1_commitment_level_proto_init() }
func file_protochain_solana_type_v1_commitment_level_proto_init() {
	if File_protochain_solana_type_v1_commitment_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_type_v1_commitment_level_proto_rawDesc), len(file_protochain_solana_type_v1_commitment_level_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protochain_solana_type_v1_commitment_level_proto_goTypes,
		DependencyIndexes: file_protochain_solana_type_v1_commitment_level_proto_depIdxs,
		EnumInfos:         file_protochain_solana_type_v1_commitment_level_proto_enumTypes,
	}.Build()
	File_protochain_solana_type_v1_commitment_level_proto = out.File
	file_protochain_solana_type_v1_commitment_level_proto_goTypes = nil
	file_protochain_solana_type_v1_commitment_level_proto_depIdxs = nil
}
