// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file protochain/solana/transaction/v1/transaction.proto (package protochain.solana.transaction.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { SolanaInstruction } from "./instruction_pb";
import { file_protochain_solana_transaction_v1_instruction } from "./instruction_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file protochain/solana/transaction/v1/transaction.proto.
 */
export const file_protochain_solana_transaction_v1_transaction: GenFile = /*@__PURE__*/
  fileDesc("CjJwcm90b2NoYWluL3NvbGFuYS90cmFuc2FjdGlvbi92MS90cmFuc2FjdGlvbi5wcm90bxIgcHJvdG9jaGFpbi5zb2xhbmEudHJhbnNhY3Rpb24udjEimgEKEVRyYW5zYWN0aW9uQ29uZmlnEhoKEmNvbXB1dGVfdW5pdF9saW1pdBgBIAEoDRIaChJjb21wdXRlX3VuaXRfcHJpY2UYAiABKAQSFAoMcHJpb3JpdHlfZmVlGAMgASgEEhYKDnNraXBfcHJlZmxpZ2h0GAQgASgIEh8KF3NraXBfYWNjb3VudF92YWxpZGF0aW9uGAUgASgIItACCgtUcmFuc2FjdGlvbhJJCgxpbnN0cnVjdGlvbnMYASADKAsyMy5wcm90b2NoYWluLnNvbGFuYS50cmFuc2FjdGlvbi52MS5Tb2xhbmFJbnN0cnVjdGlvbhJBCgVzdGF0ZRgCIAEoDjIyLnByb3RvY2hhaW4uc29sYW5hLnRyYW5zYWN0aW9uLnYxLlRyYW5zYWN0aW9uU3RhdGUSQwoGY29uZmlnGAMgASgLMjMucHJvdG9jaGFpbi5zb2xhbmEudHJhbnNhY3Rpb24udjEuVHJhbnNhY3Rpb25Db25maWcSDAoEZGF0YRgEIAEoCRIRCglmZWVfcGF5ZXIYBSABKAkSGAoQcmVjZW50X2Jsb2NraGFzaBgGIAEoCRISCgpzaWduYXR1cmVzGAcgAygJEgwKBGhhc2gYCCABKAkSEQoJc2lnbmF0dXJlGAkgASgJKr4BChBUcmFuc2FjdGlvblN0YXRlEiEKHVRSQU5TQUNUSU9OX1NUQVRFX1VOU1BFQ0lGSUVEEAASGwoXVFJBTlNBQ1RJT05fU1RBVEVfRFJBRlQQARIeChpUUkFOU0FDVElPTl9TVEFURV9DT01QSUxFRBACEiYKIlRSQU5TQUNUSU9OX1NUQVRFX1BBUlRJQUxMWV9TSUdORUQQAxIiCh5UUkFOU0FDVElPTl9TVEFURV9GVUxMWV9TSUdORUQQBEJWWlRnaXRodWIuY29tL0JSQnVzc3kvcHJvdG9jaGFpbi9saWIvZ28vcHJvdG9jaGFpbi9zb2xhbmEvdHJhbnNhY3Rpb24vdjE7dHJhbnNhY3Rpb25fdjFiBnByb3RvMw", [file_protochain_solana_transaction_v1_instruction]);

/**
 * Configuration for transaction compilation and execution
 *
 * @generated from message protochain.solana.transaction.v1.TransactionConfig
 */
export type TransactionConfig = Message<"protochain.solana.transaction.v1.TransactionConfig"> & {
  /**
   * Compute budget configuration
   *
   * @generated from field: uint32 compute_unit_limit = 1;
   */
  computeUnitLimit: number;

  /**
   * @generated from field: uint64 compute_unit_price = 2;
   */
  computeUnitPrice: bigint;

  /**
   * @generated from field: uint64 priority_fee = 3;
   */
  priorityFee: bigint;

  /**
   * Validation options
   *
   * @generated from field: bool skip_preflight = 4;
   */
  skipPreflight: boolean;

  /**
   * @generated from field: bool skip_account_validation = 5;
   */
  skipAccountValidation: boolean;
};

/**
 * Describes the message protochain.solana.transaction.v1.TransactionConfig.
 * Use `create(TransactionConfigSchema)` to create a new message.
 */
export const TransactionConfigSchema: GenMessage<TransactionConfig> = /*@__PURE__*/
  messageDesc(file_protochain_solana_transaction_v1_transaction, 0);

/**
 * Composable transaction supporting multiple instructions
 *
 * @generated from message protochain.solana.transaction.v1.Transaction
 */
export type Transaction = Message<"protochain.solana.transaction.v1.Transaction"> & {
  /**
   * Instructions for composition (populated in draft state)
   *
   * @generated from field: repeated protochain.solana.transaction.v1.SolanaInstruction instructions = 1;
   */
  instructions: SolanaInstruction[];

  /**
   * Transaction lifecycle state
   *
   * @generated from field: protochain.solana.transaction.v1.TransactionState state = 2;
   */
  state: TransactionState;

  /**
   * Transaction configuration
   *
   * @generated from field: protochain.solana.transaction.v1.TransactionConfig config = 3;
   */
  config?: TransactionConfig;

  /**
   * Compiled transaction data (populated when compiled)
   *
   * @generated from field: string data = 4;
   */
  data: string;

  /**
   * Transaction metadata
   *
   * @generated from field: string fee_payer = 5;
   */
  feePayer: string;

  /**
   * @generated from field: string recent_blockhash = 6;
   */
  recentBlockhash: string;

  /**
   * @generated from field: repeated string signatures = 7;
   */
  signatures: string[];

  /**
   * Transaction hash (when submitted)
   *
   * @generated from field: string hash = 8;
   */
  hash: string;

  /**
   * Primary signature for compatibility with existing account service
   *
   * @generated from field: string signature = 9;
   */
  signature: string;
};

/**
 * Describes the message protochain.solana.transaction.v1.Transaction.
 * Use `create(TransactionSchema)` to create a new message.
 */
export const TransactionSchema: GenMessage<Transaction> = /*@__PURE__*/
  messageDesc(file_protochain_solana_transaction_v1_transaction, 1);

/**
 * Transaction lifecycle states
 *
 * @generated from enum protochain.solana.transaction.v1.TransactionState
 */
export enum TransactionState {
  /**
   * @generated from enum value: TRANSACTION_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Can add/remove instructions
   *
   * @generated from enum value: TRANSACTION_STATE_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * Instructions compiled to data, read-only
   *
   * @generated from enum value: TRANSACTION_STATE_COMPILED = 2;
   */
  COMPILED = 2,

  /**
   * Some signatures added
   *
   * @generated from enum value: TRANSACTION_STATE_PARTIALLY_SIGNED = 3;
   */
  PARTIALLY_SIGNED = 3,

  /**
   * All signatures present, ready for submission
   *
   * @generated from enum value: TRANSACTION_STATE_FULLY_SIGNED = 4;
   */
  FULLY_SIGNED = 4,
}

/**
 * Describes the enum protochain.solana.transaction.v1.TransactionState.
 */
export const TransactionStateSchema: GenEnum<TransactionState> = /*@__PURE__*/
  enumDesc(file_protochain_solana_transaction_v1_transaction, 0);

