// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: protochain/solana/account/v1/service.proto

package account_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_GetAccount_FullMethodName                = "/protochain.solana.account.v1.Service/GetAccount"
	Service_GenerateNewKeyPair_FullMethodName        = "/protochain.solana.account.v1.Service/GenerateNewKeyPair"
	Service_FundNative_FullMethodName                = "/protochain.solana.account.v1.Service/FundNative"
	Service_GetTokenAccountBalance_FullMethodName    = "/protochain.solana.account.v1.Service/GetTokenAccountBalance"
	Service_GetAssociatedTokenAddress_FullMethodName = "/protochain.solana.account.v1.Service/GetAssociatedTokenAddress"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// GetAccount will return a protochain Account entity representing an account on-chain
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
	// GenerateKeyPair will generate a public+private keypair (optionally using seed if set)
	GenerateNewKeyPair(ctx context.Context, in *GenerateNewKeyPairRequest, opts ...grpc.CallOption) (*GenerateNewKeyPairResponse, error)
	// FundNative will fund the destination account with SOL
	FundNative(ctx context.Context, in *FundNativeRequest, opts ...grpc.CallOption) (*FundNativeResponse, error)
	// GetTokenAccountBalance will return the balance of the token held by a token account
	GetTokenAccountBalance(ctx context.Context, in *GetTokenAccountBalanceRequest, opts ...grpc.CallOption) (*GetTokenAccountBalanceResponse, error)
	// GetAssociatedTokenAddress is used to get the PDA address of an associated token account
	GetAssociatedTokenAddress(ctx context.Context, in *GetAssociatedTokenAddressRequest, opts ...grpc.CallOption) (*GetAssociatedTokenAddressResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, Service_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GenerateNewKeyPair(ctx context.Context, in *GenerateNewKeyPairRequest, opts ...grpc.CallOption) (*GenerateNewKeyPairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateNewKeyPairResponse)
	err := c.cc.Invoke(ctx, Service_GenerateNewKeyPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) FundNative(ctx context.Context, in *FundNativeRequest, opts ...grpc.CallOption) (*FundNativeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundNativeResponse)
	err := c.cc.Invoke(ctx, Service_FundNative_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetTokenAccountBalance(ctx context.Context, in *GetTokenAccountBalanceRequest, opts ...grpc.CallOption) (*GetTokenAccountBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenAccountBalanceResponse)
	err := c.cc.Invoke(ctx, Service_GetTokenAccountBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetAssociatedTokenAddress(ctx context.Context, in *GetAssociatedTokenAddressRequest, opts ...grpc.CallOption) (*GetAssociatedTokenAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAssociatedTokenAddressResponse)
	err := c.cc.Invoke(ctx, Service_GetAssociatedTokenAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	// GetAccount will return a protochain Account entity representing an account on-chain
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
	// GenerateKeyPair will generate a public+private keypair (optionally using seed if set)
	GenerateNewKeyPair(context.Context, *GenerateNewKeyPairRequest) (*GenerateNewKeyPairResponse, error)
	// FundNative will fund the destination account with SOL
	FundNative(context.Context, *FundNativeRequest) (*FundNativeResponse, error)
	// GetTokenAccountBalance will return the balance of the token held by a token account
	GetTokenAccountBalance(context.Context, *GetTokenAccountBalanceRequest) (*GetTokenAccountBalanceResponse, error)
	// GetAssociatedTokenAddress is used to get the PDA address of an associated token account
	GetAssociatedTokenAddress(context.Context, *GetAssociatedTokenAddressRequest) (*GetAssociatedTokenAddressResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedServiceServer) GenerateNewKeyPair(context.Context, *GenerateNewKeyPairRequest) (*GenerateNewKeyPairResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateNewKeyPair not implemented")
}
func (UnimplementedServiceServer) FundNative(context.Context, *FundNativeRequest) (*FundNativeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FundNative not implemented")
}
func (UnimplementedServiceServer) GetTokenAccountBalance(context.Context, *GetTokenAccountBalanceRequest) (*GetTokenAccountBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTokenAccountBalance not implemented")
}
func (UnimplementedServiceServer) GetAssociatedTokenAddress(context.Context, *GetAssociatedTokenAddressRequest) (*GetAssociatedTokenAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAssociatedTokenAddress not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GenerateNewKeyPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateNewKeyPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GenerateNewKeyPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GenerateNewKeyPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GenerateNewKeyPair(ctx, req.(*GenerateNewKeyPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_FundNative_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundNativeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).FundNative(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_FundNative_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).FundNative(ctx, req.(*FundNativeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetTokenAccountBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenAccountBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetTokenAccountBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetTokenAccountBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetTokenAccountBalance(ctx, req.(*GetTokenAccountBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetAssociatedTokenAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssociatedTokenAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetAssociatedTokenAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetAssociatedTokenAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetAssociatedTokenAddress(ctx, req.(*GetAssociatedTokenAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protochain.solana.account.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _Service_GetAccount_Handler,
		},
		{
			MethodName: "GenerateNewKeyPair",
			Handler:    _Service_GenerateNewKeyPair_Handler,
		},
		{
			MethodName: "FundNative",
			Handler:    _Service_FundNative_Handler,
		},
		{
			MethodName: "GetTokenAccountBalance",
			Handler:    _Service_GetTokenAccountBalance_Handler,
		},
		{
			MethodName: "GetAssociatedTokenAddress",
			Handler:    _Service_GetAssociatedTokenAddress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protochain/solana/account/v1/service.proto",
}
