// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: protochain/solana/program/token/v1/service.proto

package token_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_CreateToken2022Mint_FullMethodName                = "/protochain.solana.program.token.v1.Service/CreateToken2022Mint"
	Service_CreateSPLTokenMint_FullMethodName                 = "/protochain.solana.program.token.v1.Service/CreateSPLTokenMint"
	Service_ParseMint_FullMethodName                          = "/protochain.solana.program.token.v1.Service/ParseMint"
	Service_GetCurrentMinRentForHoldingAccount_FullMethodName = "/protochain.solana.program.token.v1.Service/GetCurrentMinRentForHoldingAccount"
	Service_CreateHoldingAccount_FullMethodName               = "/protochain.solana.program.token.v1.Service/CreateHoldingAccount"
	Service_Mint_FullMethodName                               = "/protochain.solana.program.token.v1.Service/Mint"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Token Program service for creating SPL Token and Token-2022 instructions.
//
// Mint creation methods (CreateToken2022Mint, CreateSPLTokenMint) return the
// complete set of instructions needed to create and initialise a mint account
// in a single call — including the System::CreateAccount instruction, rent
// calculation, and any extension/metadata setup. This removes the need for
// callers to separately query rent, build a system create instruction, and
// then initialise the mint.
type ServiceClient interface {
	// Creates a fully initialised Token-2022 mint account in one call.
	//
	// Returns the complete ordered instruction set:
	//  1. System::CreateAccount  — allocates and funds the mint account
	//  2. Extension pre-init instructions (e.g. initialize_metadata_pointer)
	//  3. initialize_mint
	//  4. Extension post-init instructions (e.g. initialize_token_metadata, update_field × N)
	//
	// The response also includes the lamports deposited and the space allocated
	// for the account, so callers know the cost without a separate query.
	CreateToken2022Mint(ctx context.Context, in *CreateToken2022MintRequest, opts ...grpc.CallOption) (*CreateToken2022MintResponse, error)
	// Creates a fully initialised legacy SPL Token mint account in one call.
	//
	// Returns the complete ordered instruction set:
	//  1. System::CreateAccount  — allocates and funds the mint account (always 82 bytes)
	//  2. initialize_mint
	//  3. (optional) CreateMetadataAccountV3 — Metaplex on-chain metadata PDA
	//
	// The response also includes the lamports deposited and the space allocated.
	CreateSPLTokenMint(ctx context.Context, in *CreateSPLTokenMintRequest, opts ...grpc.CallOption) (*CreateSPLTokenMintResponse, error)
	// Parses mint account data into structured format
	//
	// Token Program Agnostic. Response indicates if mint is for Token2022 or SPL tokens.
	ParseMint(ctx context.Context, in *ParseMintRequest, opts ...grpc.CallOption) (*ParseMintResponse, error)
	// Gets current minimum rent for a token holding account, optionally accounting for memo transfer extension size when memo_transfer_config is provided.
	GetCurrentMinRentForHoldingAccount(ctx context.Context, in *GetCurrentMinRentForHoldingAccountRequest, opts ...grpc.CallOption) (*GetCurrentMinRentForHoldingAccountResponse, error)
	// Creates holding account initialization instructions. Adds memo-enable instruction when requested.
	CreateHoldingAccount(ctx context.Context, in *CreateHoldingAccountRequest, opts ...grpc.CallOption) (*CreateHoldingAccountResponse, error)
	// Mint tokens to an existing token account using MintToChecked instruction
	//
	// Token Program Agnostic.
	Mint(ctx context.Context, in *MintRequest, opts ...grpc.CallOption) (*MintResponse, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) CreateToken2022Mint(ctx context.Context, in *CreateToken2022MintRequest, opts ...grpc.CallOption) (*CreateToken2022MintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateToken2022MintResponse)
	err := c.cc.Invoke(ctx, Service_CreateToken2022Mint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateSPLTokenMint(ctx context.Context, in *CreateSPLTokenMintRequest, opts ...grpc.CallOption) (*CreateSPLTokenMintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSPLTokenMintResponse)
	err := c.cc.Invoke(ctx, Service_CreateSPLTokenMint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ParseMint(ctx context.Context, in *ParseMintRequest, opts ...grpc.CallOption) (*ParseMintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseMintResponse)
	err := c.cc.Invoke(ctx, Service_ParseMint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetCurrentMinRentForHoldingAccount(ctx context.Context, in *GetCurrentMinRentForHoldingAccountRequest, opts ...grpc.CallOption) (*GetCurrentMinRentForHoldingAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrentMinRentForHoldingAccountResponse)
	err := c.cc.Invoke(ctx, Service_GetCurrentMinRentForHoldingAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) CreateHoldingAccount(ctx context.Context, in *CreateHoldingAccountRequest, opts ...grpc.CallOption) (*CreateHoldingAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHoldingAccountResponse)
	err := c.cc.Invoke(ctx, Service_CreateHoldingAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Mint(ctx context.Context, in *MintRequest, opts ...grpc.CallOption) (*MintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintResponse)
	err := c.cc.Invoke(ctx, Service_Mint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
//
// Token Program service for creating SPL Token and Token-2022 instructions.
//
// Mint creation methods (CreateToken2022Mint, CreateSPLTokenMint) return the
// complete set of instructions needed to create and initialise a mint account
// in a single call — including the System::CreateAccount instruction, rent
// calculation, and any extension/metadata setup. This removes the need for
// callers to separately query rent, build a system create instruction, and
// then initialise the mint.
type ServiceServer interface {
	// Creates a fully initialised Token-2022 mint account in one call.
	//
	// Returns the complete ordered instruction set:
	//  1. System::CreateAccount  — allocates and funds the mint account
	//  2. Extension pre-init instructions (e.g. initialize_metadata_pointer)
	//  3. initialize_mint
	//  4. Extension post-init instructions (e.g. initialize_token_metadata, update_field × N)
	//
	// The response also includes the lamports deposited and the space allocated
	// for the account, so callers know the cost without a separate query.
	CreateToken2022Mint(context.Context, *CreateToken2022MintRequest) (*CreateToken2022MintResponse, error)
	// Creates a fully initialised legacy SPL Token mint account in one call.
	//
	// Returns the complete ordered instruction set:
	//  1. System::CreateAccount  — allocates and funds the mint account (always 82 bytes)
	//  2. initialize_mint
	//  3. (optional) CreateMetadataAccountV3 — Metaplex on-chain metadata PDA
	//
	// The response also includes the lamports deposited and the space allocated.
	CreateSPLTokenMint(context.Context, *CreateSPLTokenMintRequest) (*CreateSPLTokenMintResponse, error)
	// Parses mint account data into structured format
	//
	// Token Program Agnostic. Response indicates if mint is for Token2022 or SPL tokens.
	ParseMint(context.Context, *ParseMintRequest) (*ParseMintResponse, error)
	// Gets current minimum rent for a token holding account, optionally accounting for memo transfer extension size when memo_transfer_config is provided.
	GetCurrentMinRentForHoldingAccount(context.Context, *GetCurrentMinRentForHoldingAccountRequest) (*GetCurrentMinRentForHoldingAccountResponse, error)
	// Creates holding account initialization instructions. Adds memo-enable instruction when requested.
	CreateHoldingAccount(context.Context, *CreateHoldingAccountRequest) (*CreateHoldingAccountResponse, error)
	// Mint tokens to an existing token account using MintToChecked instruction
	//
	// Token Program Agnostic.
	Mint(context.Context, *MintRequest) (*MintResponse, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) CreateToken2022Mint(context.Context, *CreateToken2022MintRequest) (*CreateToken2022MintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateToken2022Mint not implemented")
}
func (UnimplementedServiceServer) CreateSPLTokenMint(context.Context, *CreateSPLTokenMintRequest) (*CreateSPLTokenMintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSPLTokenMint not implemented")
}
func (UnimplementedServiceServer) ParseMint(context.Context, *ParseMintRequest) (*ParseMintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseMint not implemented")
}
func (UnimplementedServiceServer) GetCurrentMinRentForHoldingAccount(context.Context, *GetCurrentMinRentForHoldingAccountRequest) (*GetCurrentMinRentForHoldingAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentMinRentForHoldingAccount not implemented")
}
func (UnimplementedServiceServer) CreateHoldingAccount(context.Context, *CreateHoldingAccountRequest) (*CreateHoldingAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHoldingAccount not implemented")
}
func (UnimplementedServiceServer) Mint(context.Context, *MintRequest) (*MintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mint not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call panics, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_CreateToken2022Mint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateToken2022MintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateToken2022Mint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateToken2022Mint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateToken2022Mint(ctx, req.(*CreateToken2022MintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateSPLTokenMint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSPLTokenMintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateSPLTokenMint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateSPLTokenMint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateSPLTokenMint(ctx, req.(*CreateSPLTokenMintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ParseMint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseMintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ParseMint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_ParseMint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ParseMint(ctx, req.(*ParseMintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetCurrentMinRentForHoldingAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentMinRentForHoldingAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetCurrentMinRentForHoldingAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetCurrentMinRentForHoldingAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetCurrentMinRentForHoldingAccount(ctx, req.(*GetCurrentMinRentForHoldingAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_CreateHoldingAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHoldingAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateHoldingAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_CreateHoldingAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateHoldingAccount(ctx, req.(*CreateHoldingAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Mint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Mint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_Mint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Mint(ctx, req.(*MintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protochain.solana.program.token.v1.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToken2022Mint",
			Handler:    _Service_CreateToken2022Mint_Handler,
		},
		{
			MethodName: "CreateSPLTokenMint",
			Handler:    _Service_CreateSPLTokenMint_Handler,
		},
		{
			MethodName: "ParseMint",
			Handler:    _Service_ParseMint_Handler,
		},
		{
			MethodName: "GetCurrentMinRentForHoldingAccount",
			Handler:    _Service_GetCurrentMinRentForHoldingAccount_Handler,
		},
		{
			MethodName: "CreateHoldingAccount",
			Handler:    _Service_CreateHoldingAccount_Handler,
		},
		{
			MethodName: "Mint",
			Handler:    _Service_Mint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protochain/solana/program/token/v1/service.proto",
}
