// Code generated by protoc-gen-passivgo. DO NOT EDIT.
// source: protochain/solana/program/token/v1/service.proto
package token_v1

import (
	context "context"
)

// Token Program service for creating SPL Token and Token-2022 instructions.
//
// Mint creation methods (CreateToken2022Mint, CreateSPLTokenMint) return the
// complete set of instructions needed to create and initialise a mint account
// in a single call — including the System::CreateAccount instruction, rent
// calculation, and any extension/metadata setup. This removes the need for
// callers to separately query rent, build a system create instruction, and
// then initialise the mint.
type ServiceInterface interface {
	// Creates a fully initialised Token-2022 mint account in one call.
	//
	// Returns the complete ordered instruction set:
	//   1. System::CreateAccount  — allocates and funds the mint account
	//   2. Extension pre-init instructions (e.g. initialize_metadata_pointer)
	//   3. initialize_mint
	//   4. Extension post-init instructions (e.g. initialize_token_metadata, update_field × N)
	//
	// The response also includes the lamports deposited and the space allocated
	// for the account, so callers know the cost without a separate query.
	CreateToken2022Mint(ctx context.Context, request *CreateToken2022MintRequest) (*CreateToken2022MintResponse, error)

	// Creates a fully initialised legacy SPL Token mint account in one call.
	//
	// Returns the complete ordered instruction set:
	//   1. System::CreateAccount  — allocates and funds the mint account (always 82 bytes)
	//   2. initialize_mint
	//   3. (optional) CreateMetadataAccountV3 — Metaplex on-chain metadata PDA
	//
	// The response also includes the lamports deposited and the space allocated.
	CreateSPLTokenMint(ctx context.Context, request *CreateSPLTokenMintRequest) (*CreateSPLTokenMintResponse, error)

	// Parses mint account data into structured format
	//
	// Token Program Agnostic. Response indicates if mint is for Token2022 or SPL tokens.
	ParseMint(ctx context.Context, request *ParseMintRequest) (*ParseMintResponse, error)

	// Gets current minimum rent for a token holding account, optionally accounting for memo transfer extension size when memo_transfer_config is provided.
	GetCurrentMinRentForHoldingAccount(ctx context.Context, request *GetCurrentMinRentForHoldingAccountRequest) (*GetCurrentMinRentForHoldingAccountResponse, error)

	// Creates holding account initialization instructions. Adds memo-enable instruction when requested.
	CreateHoldingAccount(ctx context.Context, request *CreateHoldingAccountRequest) (*CreateHoldingAccountResponse, error)

	// Mint tokens to an existing token account using MintToChecked instruction
	//
	// Token Program Agnostic.
	Mint(ctx context.Context, request *MintRequest) (*MintResponse, error)
}

const ServiceServiceProviderName = "protochain-solana-program-token-v1-Service"
