// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/program/token/v1/service.proto

package token_v1

import (
	v1 "github.com/meshtrade/protochain/lib/go/protochain/solana/transaction/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create and fully initialise a Token-2022 mint account.
type CreateToken2022MintRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the account that will pay for account creation (signer).
	PayerPubKey string `protobuf:"bytes,1,opt,name=payer_pub_key,json=payerPubKey,proto3" json:"payer_pub_key,omitempty"`
	// The public key of the Mint account to be created and initialized (signer).
	MintPubKey string `protobuf:"bytes,2,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// The authority that can mint new tokens.
	MintAuthorityPubKey string `protobuf:"bytes,3,opt,name=mint_authority_pub_key,json=mintAuthorityPubKey,proto3" json:"mint_authority_pub_key,omitempty"`
	// Optional authority that can freeze token accounts.
	// Leave empty to disable freeze functionality.
	FreezeAuthorityPubKey string `protobuf:"bytes,4,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"`
	// Number of base 10 digits to the right of the decimal place.
	// Common values: 9 for SOL-like tokens, 6 for USDC-like tokens, 0 for NFTs.
	Decimals uint32 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// Ordered list of extensions to enable on the mint.
	// NOTE: If extensions are not included here during initialization,
	// they cannot be added to the mint account later.
	Extensions    []*Token2022Extension `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToken2022MintRequest) Reset() {
	*x = CreateToken2022MintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToken2022MintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToken2022MintRequest) ProtoMessage() {}

func (x *CreateToken2022MintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToken2022MintRequest.ProtoReflect.Descriptor instead.
func (*CreateToken2022MintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateToken2022MintRequest) GetPayerPubKey() string {
	if x != nil {
		return x.PayerPubKey
	}
	return ""
}

func (x *CreateToken2022MintRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *CreateToken2022MintRequest) GetMintAuthorityPubKey() string {
	if x != nil {
		return x.MintAuthorityPubKey
	}
	return ""
}

func (x *CreateToken2022MintRequest) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

func (x *CreateToken2022MintRequest) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreateToken2022MintRequest) GetExtensions() []*Token2022Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Response containing the complete instruction set for Token-2022 mint creation.
type CreateToken2022MintResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered instructions to include in a transaction.
	// Includes System::CreateAccount followed by all Token-2022 initialisation instructions.
	Instructions []*v1.SolanaInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	// Lamports deposited into the mint account for rent exemption.
	// Covers the full final account size including variable-length extension data
	// (e.g. token metadata) that Token-2022 allocates via realloc after creation.
	Lamports uint64 `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	// Initial account space in bytes passed to System::CreateAccount.
	// Covers the base mint layout and fixed-size extension pods only.
	// Token-2022 may realloc beyond this size for variable-length extensions.
	Space         uint64 `protobuf:"varint,3,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToken2022MintResponse) Reset() {
	*x = CreateToken2022MintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToken2022MintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToken2022MintResponse) ProtoMessage() {}

func (x *CreateToken2022MintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToken2022MintResponse.ProtoReflect.Descriptor instead.
func (*CreateToken2022MintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateToken2022MintResponse) GetInstructions() []*v1.SolanaInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *CreateToken2022MintResponse) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *CreateToken2022MintResponse) GetSpace() uint64 {
	if x != nil {
		return x.Space
	}
	return 0
}

// Request to create and fully initialise a legacy SPL Token mint account.
type CreateSPLTokenMintRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the account that will pay for account creation (signer).
	PayerPubKey string `protobuf:"bytes,1,opt,name=payer_pub_key,json=payerPubKey,proto3" json:"payer_pub_key,omitempty"`
	// The public key of the Mint account to be created and initialized (signer).
	MintPubKey string `protobuf:"bytes,2,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// The authority that can mint new tokens.
	MintAuthorityPubKey string `protobuf:"bytes,3,opt,name=mint_authority_pub_key,json=mintAuthorityPubKey,proto3" json:"mint_authority_pub_key,omitempty"`
	// Optional authority that can freeze token accounts.
	// Leave empty to disable freeze functionality.
	FreezeAuthorityPubKey string `protobuf:"bytes,4,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"`
	// Number of base 10 digits to the right of the decimal place.
	// Common values: 9 for SOL-like tokens, 6 for USDC-like tokens, 0 for NFTs.
	Decimals uint32 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// Optional Metaplex metadata to attach to the mint via the Metaplex Token Metadata program.
	// When provided, a CreateMetadataAccountV3 instruction is appended after initialize_mint.
	Metadata      *MetaplexTokenMetadata `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSPLTokenMintRequest) Reset() {
	*x = CreateSPLTokenMintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSPLTokenMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSPLTokenMintRequest) ProtoMessage() {}

func (x *CreateSPLTokenMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSPLTokenMintRequest.ProtoReflect.Descriptor instead.
func (*CreateSPLTokenMintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSPLTokenMintRequest) GetPayerPubKey() string {
	if x != nil {
		return x.PayerPubKey
	}
	return ""
}

func (x *CreateSPLTokenMintRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *CreateSPLTokenMintRequest) GetMintAuthorityPubKey() string {
	if x != nil {
		return x.MintAuthorityPubKey
	}
	return ""
}

func (x *CreateSPLTokenMintRequest) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

func (x *CreateSPLTokenMintRequest) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreateSPLTokenMintRequest) GetMetadata() *MetaplexTokenMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Response containing the complete instruction set for SPL Token mint creation.
type CreateSPLTokenMintResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered instructions to include in a transaction.
	// Includes System::CreateAccount, initialize_mint, and optionally CreateMetadataAccountV3.
	Instructions []*v1.SolanaInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	// Lamports deposited into the mint account for rent exemption.
	Lamports uint64 `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	// Account space in bytes passed to System::CreateAccount (always 82 bytes for SPL Token mints).
	Space         uint64 `protobuf:"varint,3,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSPLTokenMintResponse) Reset() {
	*x = CreateSPLTokenMintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSPLTokenMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSPLTokenMintResponse) ProtoMessage() {}

func (x *CreateSPLTokenMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSPLTokenMintResponse.ProtoReflect.Descriptor instead.
func (*CreateSPLTokenMintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSPLTokenMintResponse) GetInstructions() []*v1.SolanaInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *CreateSPLTokenMintResponse) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

func (x *CreateSPLTokenMintResponse) GetSpace() uint64 {
	if x != nil {
		return x.Space
	}
	return 0
}

// Request to parse mint account
type ParseMintRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountAddress string                 `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseMintRequest) Reset() {
	*x = ParseMintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseMintRequest) ProtoMessage() {}

func (x *ParseMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseMintRequest.ProtoReflect.Descriptor instead.
func (*ParseMintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ParseMintRequest) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

// Response with parsed mint data.
type ParseMintResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base mint account fields (authority, decimals, supply, etc.).
	Mint *MintInfo `protobuf:"bytes,1,opt,name=mint,proto3" json:"mint,omitempty"`
	// The token program that owns this mint account (Legacy SPL Token or Token-2022).
	TokenProgram TokenProgram `protobuf:"varint,2,opt,name=token_program,json=tokenProgram,proto3,enum=protochain.solana.program.token.v1.TokenProgram" json:"token_program,omitempty"`
	// Extensions present on the mint account.
	// Only populated for Token-2022 mints that have extensions configured.
	Extensions []*Token2022Extension `protobuf:"bytes,3,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Metaplex Token Metadata associated with the mint.
	//
	// Only populated for legacy SPL Token mints that have an associated Metaplex
	// metadata PDA (i.e. created via CreateSPLTokenMint with metadata provided).
	// The metadata PDA is derived using the standard Metaplex seed convention:
	//
	//	["metadata", METADATA_PROGRAM_ID, mint_pubkey].
	//
	// For Token-2022 mints this field is always absent — metadata is instead
	// returned inline via the extensions field.
	MetaplexMetadata *MetaplexTokenMetadata `protobuf:"bytes,4,opt,name=metaplex_metadata,json=metaplexMetadata,proto3" json:"metaplex_metadata,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ParseMintResponse) Reset() {
	*x = ParseMintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseMintResponse) ProtoMessage() {}

func (x *ParseMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseMintResponse.ProtoReflect.Descriptor instead.
func (*ParseMintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ParseMintResponse) GetMint() *MintInfo {
	if x != nil {
		return x.Mint
	}
	return nil
}

func (x *ParseMintResponse) GetTokenProgram() TokenProgram {
	if x != nil {
		return x.TokenProgram
	}
	return TokenProgram_TOKEN_PROGRAM_UNSPECIFIED
}

func (x *ParseMintResponse) GetExtensions() []*Token2022Extension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *ParseMintResponse) GetMetaplexMetadata() *MetaplexTokenMetadata {
	if x != nil {
		return x.MetaplexMetadata
	}
	return nil
}

// Structured mint account information
type MintInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MintAuthorityPubKey   string                 `protobuf:"bytes,1,opt,name=mint_authority_pub_key,json=mintAuthorityPubKey,proto3" json:"mint_authority_pub_key,omitempty"`
	FreezeAuthorityPubKey string                 `protobuf:"bytes,2,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"`
	Decimals              uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Supply                string                 `protobuf:"bytes,4,opt,name=supply,proto3" json:"supply,omitempty"`
	IsInitialized         bool                   `protobuf:"varint,5,opt,name=is_initialized,json=isInitialized,proto3" json:"is_initialized,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MintInfo) Reset() {
	*x = MintInfo{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintInfo) ProtoMessage() {}

func (x *MintInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintInfo.ProtoReflect.Descriptor instead.
func (*MintInfo) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *MintInfo) GetMintAuthorityPubKey() string {
	if x != nil {
		return x.MintAuthorityPubKey
	}
	return ""
}

func (x *MintInfo) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

func (x *MintInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *MintInfo) GetSupply() string {
	if x != nil {
		return x.Supply
	}
	return ""
}

func (x *MintInfo) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

// Request to create a Token-2022 holding account (Associated Token Account)
// with optional extensions.
type CreateToken2022HoldingAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the account that will pay for account creation (signer).
	PayerPubKey string `protobuf:"bytes,1,opt,name=payer_pub_key,json=payerPubKey,proto3" json:"payer_pub_key,omitempty"`
	// The public key of the wallet that will own the holding account
	// (controls the token balance).
	OwnerPubKey string `protobuf:"bytes,2,opt,name=owner_pub_key,json=ownerPubKey,proto3" json:"owner_pub_key,omitempty"`
	// The public key of the mint this holding account will hold tokens for.
	MintPubKey string `protobuf:"bytes,3,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// Ordered list of Token-2022 extensions to enable on the holding account.
	// Extensions that are not included here during creation cannot be added
	// later without reallocating the account.
	Extensions    []*Token2022HoldingAccountExtension `protobuf:"bytes,4,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToken2022HoldingAccountRequest) Reset() {
	*x = CreateToken2022HoldingAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToken2022HoldingAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToken2022HoldingAccountRequest) ProtoMessage() {}

func (x *CreateToken2022HoldingAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToken2022HoldingAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateToken2022HoldingAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateToken2022HoldingAccountRequest) GetPayerPubKey() string {
	if x != nil {
		return x.PayerPubKey
	}
	return ""
}

func (x *CreateToken2022HoldingAccountRequest) GetOwnerPubKey() string {
	if x != nil {
		return x.OwnerPubKey
	}
	return ""
}

func (x *CreateToken2022HoldingAccountRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *CreateToken2022HoldingAccountRequest) GetExtensions() []*Token2022HoldingAccountExtension {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Response containing the complete instruction set for Token-2022 holding
// account creation.
type CreateToken2022HoldingAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Ordered instructions to include in a transaction.
	// Includes ATA creation and optionally reallocate + extension-init
	// instructions for each requested extension.
	Instructions []*v1.SolanaInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	// Lamports required for the holding account to be rent-exempt.
	// Accounts for the base token account size plus any requested extensions.
	Lamports      uint64 `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateToken2022HoldingAccountResponse) Reset() {
	*x = CreateToken2022HoldingAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateToken2022HoldingAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateToken2022HoldingAccountResponse) ProtoMessage() {}

func (x *CreateToken2022HoldingAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateToken2022HoldingAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateToken2022HoldingAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateToken2022HoldingAccountResponse) GetInstructions() []*v1.SolanaInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *CreateToken2022HoldingAccountResponse) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

// Request to create a legacy SPL Token holding account (Associated Token Account).
type CreateSPLTokenHoldingAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the account that will pay for account creation (signer).
	PayerPubKey string `protobuf:"bytes,1,opt,name=payer_pub_key,json=payerPubKey,proto3" json:"payer_pub_key,omitempty"`
	// The public key of the wallet that will own the holding account
	// (controls the token balance).
	OwnerPubKey string `protobuf:"bytes,2,opt,name=owner_pub_key,json=ownerPubKey,proto3" json:"owner_pub_key,omitempty"`
	// The public key of the mint this holding account will hold tokens for.
	MintPubKey    string `protobuf:"bytes,3,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSPLTokenHoldingAccountRequest) Reset() {
	*x = CreateSPLTokenHoldingAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSPLTokenHoldingAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSPLTokenHoldingAccountRequest) ProtoMessage() {}

func (x *CreateSPLTokenHoldingAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSPLTokenHoldingAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateSPLTokenHoldingAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSPLTokenHoldingAccountRequest) GetPayerPubKey() string {
	if x != nil {
		return x.PayerPubKey
	}
	return ""
}

func (x *CreateSPLTokenHoldingAccountRequest) GetOwnerPubKey() string {
	if x != nil {
		return x.OwnerPubKey
	}
	return ""
}

func (x *CreateSPLTokenHoldingAccountRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

// Response containing the instruction set for SPL Token holding account creation.
type CreateSPLTokenHoldingAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A single ATA creation instruction.
	Instructions []*v1.SolanaInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	// Lamports required for the holding account to be rent-exempt.
	Lamports      uint64 `protobuf:"varint,2,opt,name=lamports,proto3" json:"lamports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSPLTokenHoldingAccountResponse) Reset() {
	*x = CreateSPLTokenHoldingAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSPLTokenHoldingAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSPLTokenHoldingAccountResponse) ProtoMessage() {}

func (x *CreateSPLTokenHoldingAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSPLTokenHoldingAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateSPLTokenHoldingAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSPLTokenHoldingAccountResponse) GetInstructions() []*v1.SolanaInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

func (x *CreateSPLTokenHoldingAccountResponse) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

// Request to mint tokens to a destination account.
//
// The service retrieves the mint account on-chain to resolve the mint
// authority, decimal precision, and owning token program — so callers do not
// need to supply those values.
//
// NOTE: Multi-sig mint authorities are not yet supported.
type MintRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key of the token mint to mint from.
	MintPubKey string `protobuf:"bytes,1,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// Public key of the **system account** (wallet) that owns the destination
	// token account.  The Associated Token Account (ATA) is derived
	// automatically from this owner and the mint.
	//
	// Do NOT pass the ATA address itself — pass the owner's system account.
	DestinationOwnerPubKey string `protobuf:"bytes,2,opt,name=destination_owner_pub_key,json=destinationOwnerPubKey,proto3" json:"destination_owner_pub_key,omitempty"`
	// Human-readable token amount as a decimal string.
	//
	// Express the amount in whole-token units (e.g. "1.5" for one-and-a-half
	// tokens).  The service converts this to the on-chain base-unit
	// representation using the mint's decimal precision.
	//
	// Examples (assuming 6 decimals):
	//
	//	"1.0"     → 1 000 000 base units
	//	"0.5"     → 500 000 base units
	//	"1000"    → 1 000 000 000 base units
	//	"0.000001"→ 1 base unit
	Amount        string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintRequest) Reset() {
	*x = MintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintRequest) ProtoMessage() {}

func (x *MintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintRequest.ProtoReflect.Descriptor instead.
func (*MintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *MintRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *MintRequest) GetDestinationOwnerPubKey() string {
	if x != nil {
		return x.DestinationOwnerPubKey
	}
	return ""
}

func (x *MintRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// Response containing Mint instruction
type MintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v1.SolanaInstruction  `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintResponse) Reset() {
	*x = MintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintResponse) ProtoMessage() {}

func (x *MintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintResponse.ProtoReflect.Descriptor instead.
func (*MintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *MintResponse) GetInstruction() *v1.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// Request to freeze a token account.
type FreezeTokenAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the token account to freeze (Base58).
	TokenAccountPubKey string `protobuf:"bytes,1,opt,name=token_account_pub_key,json=tokenAccountPubKey,proto3" json:"token_account_pub_key,omitempty"`
	// The public key of the mint associated with the token account (Base58).
	MintPubKey string `protobuf:"bytes,2,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// The freeze authority of the mint (Base58). Must sign the transaction.
	FreezeAuthorityPubKey string `protobuf:"bytes,3,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FreezeTokenAccountRequest) Reset() {
	*x = FreezeTokenAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeTokenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeTokenAccountRequest) ProtoMessage() {}

func (x *FreezeTokenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeTokenAccountRequest.ProtoReflect.Descriptor instead.
func (*FreezeTokenAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *FreezeTokenAccountRequest) GetTokenAccountPubKey() string {
	if x != nil {
		return x.TokenAccountPubKey
	}
	return ""
}

func (x *FreezeTokenAccountRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *FreezeTokenAccountRequest) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

// Response containing the freeze account instruction.
type FreezeTokenAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v1.SolanaInstruction  `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeTokenAccountResponse) Reset() {
	*x = FreezeTokenAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeTokenAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeTokenAccountResponse) ProtoMessage() {}

func (x *FreezeTokenAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeTokenAccountResponse.ProtoReflect.Descriptor instead.
func (*FreezeTokenAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *FreezeTokenAccountResponse) GetInstruction() *v1.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// Request to thaw a frozen token account.
type ThawTokenAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the token account to thaw (Base58).
	TokenAccountPubKey string `protobuf:"bytes,1,opt,name=token_account_pub_key,json=tokenAccountPubKey,proto3" json:"token_account_pub_key,omitempty"`
	// The public key of the mint associated with the token account (Base58).
	MintPubKey string `protobuf:"bytes,2,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// The freeze authority of the mint (Base58). Must sign the transaction.
	FreezeAuthorityPubKey string `protobuf:"bytes,3,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ThawTokenAccountRequest) Reset() {
	*x = ThawTokenAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThawTokenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThawTokenAccountRequest) ProtoMessage() {}

func (x *ThawTokenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThawTokenAccountRequest.ProtoReflect.Descriptor instead.
func (*ThawTokenAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *ThawTokenAccountRequest) GetTokenAccountPubKey() string {
	if x != nil {
		return x.TokenAccountPubKey
	}
	return ""
}

func (x *ThawTokenAccountRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *ThawTokenAccountRequest) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

// Response containing the thaw account instruction.
type ThawTokenAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v1.SolanaInstruction  `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThawTokenAccountResponse) Reset() {
	*x = ThawTokenAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThawTokenAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThawTokenAccountResponse) ProtoMessage() {}

func (x *ThawTokenAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThawTokenAccountResponse.ProtoReflect.Descriptor instead.
func (*ThawTokenAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *ThawTokenAccountResponse) GetInstruction() *v1.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// Request to close a token account.
//
// The token account must have a zero token balance. Any remaining SOL
// (rent-exempt lamports) is transferred to the destination address.
type CloseTokenAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the token account to close (Base58).
	TokenAccountPubKey string `protobuf:"bytes,1,opt,name=token_account_pub_key,json=tokenAccountPubKey,proto3" json:"token_account_pub_key,omitempty"`
	// The public key that will receive the remaining SOL rent (Base58).
	// Typically the owner of the token account.
	DestinationPubKey string `protobuf:"bytes,2,opt,name=destination_pub_key,json=destinationPubKey,proto3" json:"destination_pub_key,omitempty"`
	// The authority allowed to close the token account (Base58).
	// This is the token account owner unless a close authority has been set.
	AuthorityPubKey string `protobuf:"bytes,3,opt,name=authority_pub_key,json=authorityPubKey,proto3" json:"authority_pub_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloseTokenAccountRequest) Reset() {
	*x = CloseTokenAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTokenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTokenAccountRequest) ProtoMessage() {}

func (x *CloseTokenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTokenAccountRequest.ProtoReflect.Descriptor instead.
func (*CloseTokenAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *CloseTokenAccountRequest) GetTokenAccountPubKey() string {
	if x != nil {
		return x.TokenAccountPubKey
	}
	return ""
}

func (x *CloseTokenAccountRequest) GetDestinationPubKey() string {
	if x != nil {
		return x.DestinationPubKey
	}
	return ""
}

func (x *CloseTokenAccountRequest) GetAuthorityPubKey() string {
	if x != nil {
		return x.AuthorityPubKey
	}
	return ""
}

// Response containing the close account instruction.
type CloseTokenAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v1.SolanaInstruction  `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseTokenAccountResponse) Reset() {
	*x = CloseTokenAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseTokenAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseTokenAccountResponse) ProtoMessage() {}

func (x *CloseTokenAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseTokenAccountResponse.ProtoReflect.Descriptor instead.
func (*CloseTokenAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *CloseTokenAccountResponse) GetInstruction() *v1.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// Request to burn tokens from a token account.
//
// The service retrieves the mint account on-chain to resolve the decimal
// precision and owning token program — so callers do not need to supply
// those values.
//
// NOTE: Multi-sig authorities are not yet supported.
type BurnTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key of the token mint to burn from (Base58).
	MintPubKey string `protobuf:"bytes,1,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// Public key of the **system account** (wallet) that owns the source
	// token account.  The Associated Token Account (ATA) is derived
	// automatically from this owner and the mint.
	//
	// Do NOT pass the ATA address itself — pass the owner's system account.
	OwnerPubKey string `protobuf:"bytes,2,opt,name=owner_pub_key,json=ownerPubKey,proto3" json:"owner_pub_key,omitempty"`
	// Human-readable token amount as a decimal string.
	//
	// Express the amount in whole-token units (e.g. "1.5" for one-and-a-half
	// tokens).  The service converts this to the on-chain base-unit
	// representation using the mint's decimal precision.
	//
	// Examples (assuming 6 decimals):
	//
	//	"1.0"     → 1 000 000 base units
	//	"0.5"     → 500 000 base units
	//	"1000"    → 1 000 000 000 base units
	//	"0.000001"→ 1 base unit
	Amount        string `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnTokenRequest) Reset() {
	*x = BurnTokenRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnTokenRequest) ProtoMessage() {}

func (x *BurnTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnTokenRequest.ProtoReflect.Descriptor instead.
func (*BurnTokenRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{19}
}

func (x *BurnTokenRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *BurnTokenRequest) GetOwnerPubKey() string {
	if x != nil {
		return x.OwnerPubKey
	}
	return ""
}

func (x *BurnTokenRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// Response containing the burn instruction.
type BurnTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v1.SolanaInstruction  `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnTokenResponse) Reset() {
	*x = BurnTokenResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnTokenResponse) ProtoMessage() {}

func (x *BurnTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnTokenResponse.ProtoReflect.Descriptor instead.
func (*BurnTokenResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *BurnTokenResponse) GetInstruction() *v1.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// Request to transfer tokens between token accounts.
//
// The service retrieves the mint account on-chain to resolve the decimal
// precision and owning token program — so callers do not need to supply
// those values.
//
// NOTE: Multi-sig authorities are not yet supported.
type TransferTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Public key of the token mint (Base58).
	MintPubKey string `protobuf:"bytes,1,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	// Public key of the **system account** (wallet) that owns the source
	// token account.  The Associated Token Account (ATA) is derived
	// automatically from this owner and the mint.
	//
	// Do NOT pass the ATA address itself — pass the owner's system account.
	SourceOwnerPubKey string `protobuf:"bytes,2,opt,name=source_owner_pub_key,json=sourceOwnerPubKey,proto3" json:"source_owner_pub_key,omitempty"`
	// Public key of the **system account** (wallet) that owns the destination
	// token account.  The Associated Token Account (ATA) is derived
	// automatically from this owner and the mint.
	//
	// Do NOT pass the ATA address itself — pass the owner's system account.
	DestinationOwnerPubKey string `protobuf:"bytes,3,opt,name=destination_owner_pub_key,json=destinationOwnerPubKey,proto3" json:"destination_owner_pub_key,omitempty"`
	// Human-readable token amount as a decimal string.
	//
	// Express the amount in whole-token units (e.g. "1.5" for one-and-a-half
	// tokens).  The service converts this to the on-chain base-unit
	// representation using the mint's decimal precision.
	//
	// Examples (assuming 6 decimals):
	//
	//	"1.0"     → 1 000 000 base units
	//	"0.5"     → 500 000 base units
	//	"1000"    → 1 000 000 000 base units
	//	"0.000001"→ 1 base unit
	Amount        string `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTokenRequest) Reset() {
	*x = TransferTokenRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTokenRequest) ProtoMessage() {}

func (x *TransferTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTokenRequest.ProtoReflect.Descriptor instead.
func (*TransferTokenRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{21}
}

func (x *TransferTokenRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *TransferTokenRequest) GetSourceOwnerPubKey() string {
	if x != nil {
		return x.SourceOwnerPubKey
	}
	return ""
}

func (x *TransferTokenRequest) GetDestinationOwnerPubKey() string {
	if x != nil {
		return x.DestinationOwnerPubKey
	}
	return ""
}

func (x *TransferTokenRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

// Response containing the transfer instruction.
type TransferTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v1.SolanaInstruction  `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferTokenResponse) Reset() {
	*x = TransferTokenResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferTokenResponse) ProtoMessage() {}

func (x *TransferTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferTokenResponse.ProtoReflect.Descriptor instead.
func (*TransferTokenResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{22}
}

func (x *TransferTokenResponse) GetInstruction() *v1.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

var File_protochain_solana_program_token_v1_service_proto protoreflect.FileDescriptor

const file_protochain_solana_program_token_v1_service_proto_rawDesc = "" +
	"\n" +
	"0protochain/solana/program/token/v1/service.proto\x12\"protochain.solana.program.token.v1\x1a;protochain/solana/program/token/v1/spl_token_metadata.proto\x1a<protochain/solana/program/token/v1/token2022_extension.proto\x1aLprotochain/solana/program/token/v1/token2022_holding_account_extension.proto\x1a2protochain/solana/transaction/v1/instruction.proto\x1a6protochain/solana/program/token/v1/token_program.proto\"\xc4\x02\n" +
	"\x1aCreateToken2022MintRequest\x12\"\n" +
	"\rpayer_pub_key\x18\x01 \x01(\tR\vpayerPubKey\x12 \n" +
	"\fmint_pub_key\x18\x02 \x01(\tR\n" +
	"mintPubKey\x123\n" +
	"\x16mint_authority_pub_key\x18\x03 \x01(\tR\x13mintAuthorityPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x04 \x01(\tR\x15freezeAuthorityPubKey\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\x12V\n" +
	"\n" +
	"extensions\x18\x06 \x03(\v26.protochain.solana.program.token.v1.Token2022ExtensionR\n" +
	"extensions\"\xa8\x01\n" +
	"\x1bCreateToken2022MintResponse\x12W\n" +
	"\finstructions\x18\x01 \x03(\v23.protochain.solana.transaction.v1.SolanaInstructionR\finstructions\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x04R\blamports\x12\x14\n" +
	"\x05space\x18\x03 \x01(\x04R\x05space\"\xc2\x02\n" +
	"\x19CreateSPLTokenMintRequest\x12\"\n" +
	"\rpayer_pub_key\x18\x01 \x01(\tR\vpayerPubKey\x12 \n" +
	"\fmint_pub_key\x18\x02 \x01(\tR\n" +
	"mintPubKey\x123\n" +
	"\x16mint_authority_pub_key\x18\x03 \x01(\tR\x13mintAuthorityPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x04 \x01(\tR\x15freezeAuthorityPubKey\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\x12U\n" +
	"\bmetadata\x18\x06 \x01(\v29.protochain.solana.program.token.v1.MetaplexTokenMetadataR\bmetadata\"\xa7\x01\n" +
	"\x1aCreateSPLTokenMintResponse\x12W\n" +
	"\finstructions\x18\x01 \x03(\v23.protochain.solana.transaction.v1.SolanaInstructionR\finstructions\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x04R\blamports\x12\x14\n" +
	"\x05space\x18\x03 \x01(\x04R\x05space\";\n" +
	"\x10ParseMintRequest\x12'\n" +
	"\x0faccount_address\x18\x01 \x01(\tR\x0eaccountAddress\"\xec\x02\n" +
	"\x11ParseMintResponse\x12@\n" +
	"\x04mint\x18\x01 \x01(\v2,.protochain.solana.program.token.v1.MintInfoR\x04mint\x12U\n" +
	"\rtoken_program\x18\x02 \x01(\x0e20.protochain.solana.program.token.v1.TokenProgramR\ftokenProgram\x12V\n" +
	"\n" +
	"extensions\x18\x03 \x03(\v26.protochain.solana.program.token.v1.Token2022ExtensionR\n" +
	"extensions\x12f\n" +
	"\x11metaplex_metadata\x18\x04 \x01(\v29.protochain.solana.program.token.v1.MetaplexTokenMetadataR\x10metaplexMetadata\"\xd3\x01\n" +
	"\bMintInfo\x123\n" +
	"\x16mint_authority_pub_key\x18\x01 \x01(\tR\x13mintAuthorityPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x02 \x01(\tR\x15freezeAuthorityPubKey\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12\x16\n" +
	"\x06supply\x18\x04 \x01(\tR\x06supply\x12%\n" +
	"\x0eis_initialized\x18\x05 \x01(\bR\risInitialized\"\xf6\x01\n" +
	"$CreateToken2022HoldingAccountRequest\x12\"\n" +
	"\rpayer_pub_key\x18\x01 \x01(\tR\vpayerPubKey\x12\"\n" +
	"\rowner_pub_key\x18\x02 \x01(\tR\vownerPubKey\x12 \n" +
	"\fmint_pub_key\x18\x03 \x01(\tR\n" +
	"mintPubKey\x12d\n" +
	"\n" +
	"extensions\x18\x04 \x03(\v2D.protochain.solana.program.token.v1.Token2022HoldingAccountExtensionR\n" +
	"extensions\"\x9c\x01\n" +
	"%CreateToken2022HoldingAccountResponse\x12W\n" +
	"\finstructions\x18\x01 \x03(\v23.protochain.solana.transaction.v1.SolanaInstructionR\finstructions\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x04R\blamports\"\x8f\x01\n" +
	"#CreateSPLTokenHoldingAccountRequest\x12\"\n" +
	"\rpayer_pub_key\x18\x01 \x01(\tR\vpayerPubKey\x12\"\n" +
	"\rowner_pub_key\x18\x02 \x01(\tR\vownerPubKey\x12 \n" +
	"\fmint_pub_key\x18\x03 \x01(\tR\n" +
	"mintPubKey\"\x9b\x01\n" +
	"$CreateSPLTokenHoldingAccountResponse\x12W\n" +
	"\finstructions\x18\x01 \x03(\v23.protochain.solana.transaction.v1.SolanaInstructionR\finstructions\x12\x1a\n" +
	"\blamports\x18\x02 \x01(\x04R\blamports\"\x82\x01\n" +
	"\vMintRequest\x12 \n" +
	"\fmint_pub_key\x18\x01 \x01(\tR\n" +
	"mintPubKey\x129\n" +
	"\x19destination_owner_pub_key\x18\x02 \x01(\tR\x16destinationOwnerPubKey\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"e\n" +
	"\fMintResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction\"\xa9\x01\n" +
	"\x19FreezeTokenAccountRequest\x121\n" +
	"\x15token_account_pub_key\x18\x01 \x01(\tR\x12tokenAccountPubKey\x12 \n" +
	"\fmint_pub_key\x18\x02 \x01(\tR\n" +
	"mintPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x03 \x01(\tR\x15freezeAuthorityPubKey\"s\n" +
	"\x1aFreezeTokenAccountResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction\"\xa7\x01\n" +
	"\x17ThawTokenAccountRequest\x121\n" +
	"\x15token_account_pub_key\x18\x01 \x01(\tR\x12tokenAccountPubKey\x12 \n" +
	"\fmint_pub_key\x18\x02 \x01(\tR\n" +
	"mintPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x03 \x01(\tR\x15freezeAuthorityPubKey\"q\n" +
	"\x18ThawTokenAccountResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction\"\xa9\x01\n" +
	"\x18CloseTokenAccountRequest\x121\n" +
	"\x15token_account_pub_key\x18\x01 \x01(\tR\x12tokenAccountPubKey\x12.\n" +
	"\x13destination_pub_key\x18\x02 \x01(\tR\x11destinationPubKey\x12*\n" +
	"\x11authority_pub_key\x18\x03 \x01(\tR\x0fauthorityPubKey\"r\n" +
	"\x19CloseTokenAccountResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction\"p\n" +
	"\x10BurnTokenRequest\x12 \n" +
	"\fmint_pub_key\x18\x01 \x01(\tR\n" +
	"mintPubKey\x12\"\n" +
	"\rowner_pub_key\x18\x02 \x01(\tR\vownerPubKey\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\"j\n" +
	"\x11BurnTokenResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction\"\xbc\x01\n" +
	"\x14TransferTokenRequest\x12 \n" +
	"\fmint_pub_key\x18\x01 \x01(\tR\n" +
	"mintPubKey\x12/\n" +
	"\x14source_owner_pub_key\x18\x02 \x01(\tR\x11sourceOwnerPubKey\x129\n" +
	"\x19destination_owner_pub_key\x18\x03 \x01(\tR\x16destinationOwnerPubKey\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"n\n" +
	"\x15TransferTokenResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction2\xc2\f\n" +
	"\aService\x12\x96\x01\n" +
	"\x13CreateToken2022Mint\x12>.protochain.solana.program.token.v1.CreateToken2022MintRequest\x1a?.protochain.solana.program.token.v1.CreateToken2022MintResponse\x12\x93\x01\n" +
	"\x12CreateSPLTokenMint\x12=.protochain.solana.program.token.v1.CreateSPLTokenMintRequest\x1a>.protochain.solana.program.token.v1.CreateSPLTokenMintResponse\x12x\n" +
	"\tParseMint\x124.protochain.solana.program.token.v1.ParseMintRequest\x1a5.protochain.solana.program.token.v1.ParseMintResponse\x12\xb4\x01\n" +
	"\x1dCreateToken2022HoldingAccount\x12H.protochain.solana.program.token.v1.CreateToken2022HoldingAccountRequest\x1aI.protochain.solana.program.token.v1.CreateToken2022HoldingAccountResponse\x12\xb1\x01\n" +
	"\x1cCreateSPLTokenHoldingAccount\x12G.protochain.solana.program.token.v1.CreateSPLTokenHoldingAccountRequest\x1aH.protochain.solana.program.token.v1.CreateSPLTokenHoldingAccountResponse\x12i\n" +
	"\x04Mint\x12/.protochain.solana.program.token.v1.MintRequest\x1a0.protochain.solana.program.token.v1.MintResponse\x12\x93\x01\n" +
	"\x12FreezeTokenAccount\x12=.protochain.solana.program.token.v1.FreezeTokenAccountRequest\x1a>.protochain.solana.program.token.v1.FreezeTokenAccountResponse\x12\x8d\x01\n" +
	"\x10ThawTokenAccount\x12;.protochain.solana.program.token.v1.ThawTokenAccountRequest\x1a<.protochain.solana.program.token.v1.ThawTokenAccountResponse\x12x\n" +
	"\tBurnToken\x124.protochain.solana.program.token.v1.BurnTokenRequest\x1a5.protochain.solana.program.token.v1.BurnTokenResponse\x12\x84\x01\n" +
	"\rTransferToken\x128.protochain.solana.program.token.v1.TransferTokenRequest\x1a9.protochain.solana.program.token.v1.TransferTokenResponse\x12\x90\x01\n" +
	"\x11CloseTokenAccount\x12<.protochain.solana.program.token.v1.CloseTokenAccountRequest\x1a=.protochain.solana.program.token.v1.CloseTokenAccountResponseBTZRgithub.com/meshtrade/protochain/lib/go/protochain/solana/program/token/v1;token_v1b\x06proto3"

var (
	file_protochain_solana_program_token_v1_service_proto_rawDescOnce sync.Once
	file_protochain_solana_program_token_v1_service_proto_rawDescData []byte
)

func file_protochain_solana_program_token_v1_service_proto_rawDescGZIP() []byte {
	file_protochain_solana_program_token_v1_service_proto_rawDescOnce.Do(func() {
		file_protochain_solana_program_token_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_service_proto_rawDesc), len(file_protochain_solana_program_token_v1_service_proto_rawDesc)))
	})
	return file_protochain_solana_program_token_v1_service_proto_rawDescData
}

var file_protochain_solana_program_token_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protochain_solana_program_token_v1_service_proto_goTypes = []any{
	(*CreateToken2022MintRequest)(nil),            // 0: protochain.solana.program.token.v1.CreateToken2022MintRequest
	(*CreateToken2022MintResponse)(nil),           // 1: protochain.solana.program.token.v1.CreateToken2022MintResponse
	(*CreateSPLTokenMintRequest)(nil),             // 2: protochain.solana.program.token.v1.CreateSPLTokenMintRequest
	(*CreateSPLTokenMintResponse)(nil),            // 3: protochain.solana.program.token.v1.CreateSPLTokenMintResponse
	(*ParseMintRequest)(nil),                      // 4: protochain.solana.program.token.v1.ParseMintRequest
	(*ParseMintResponse)(nil),                     // 5: protochain.solana.program.token.v1.ParseMintResponse
	(*MintInfo)(nil),                              // 6: protochain.solana.program.token.v1.MintInfo
	(*CreateToken2022HoldingAccountRequest)(nil),  // 7: protochain.solana.program.token.v1.CreateToken2022HoldingAccountRequest
	(*CreateToken2022HoldingAccountResponse)(nil), // 8: protochain.solana.program.token.v1.CreateToken2022HoldingAccountResponse
	(*CreateSPLTokenHoldingAccountRequest)(nil),   // 9: protochain.solana.program.token.v1.CreateSPLTokenHoldingAccountRequest
	(*CreateSPLTokenHoldingAccountResponse)(nil),  // 10: protochain.solana.program.token.v1.CreateSPLTokenHoldingAccountResponse
	(*MintRequest)(nil),                           // 11: protochain.solana.program.token.v1.MintRequest
	(*MintResponse)(nil),                          // 12: protochain.solana.program.token.v1.MintResponse
	(*FreezeTokenAccountRequest)(nil),             // 13: protochain.solana.program.token.v1.FreezeTokenAccountRequest
	(*FreezeTokenAccountResponse)(nil),            // 14: protochain.solana.program.token.v1.FreezeTokenAccountResponse
	(*ThawTokenAccountRequest)(nil),               // 15: protochain.solana.program.token.v1.ThawTokenAccountRequest
	(*ThawTokenAccountResponse)(nil),              // 16: protochain.solana.program.token.v1.ThawTokenAccountResponse
	(*CloseTokenAccountRequest)(nil),              // 17: protochain.solana.program.token.v1.CloseTokenAccountRequest
	(*CloseTokenAccountResponse)(nil),             // 18: protochain.solana.program.token.v1.CloseTokenAccountResponse
	(*BurnTokenRequest)(nil),                      // 19: protochain.solana.program.token.v1.BurnTokenRequest
	(*BurnTokenResponse)(nil),                     // 20: protochain.solana.program.token.v1.BurnTokenResponse
	(*TransferTokenRequest)(nil),                  // 21: protochain.solana.program.token.v1.TransferTokenRequest
	(*TransferTokenResponse)(nil),                 // 22: protochain.solana.program.token.v1.TransferTokenResponse
	(*Token2022Extension)(nil),                    // 23: protochain.solana.program.token.v1.Token2022Extension
	(*v1.SolanaInstruction)(nil),                  // 24: protochain.solana.transaction.v1.SolanaInstruction
	(*MetaplexTokenMetadata)(nil),                 // 25: protochain.solana.program.token.v1.MetaplexTokenMetadata
	(TokenProgram)(0),                             // 26: protochain.solana.program.token.v1.TokenProgram
	(*Token2022HoldingAccountExtension)(nil),      // 27: protochain.solana.program.token.v1.Token2022HoldingAccountExtension
}
var file_protochain_solana_program_token_v1_service_proto_depIdxs = []int32{
	23, // 0: protochain.solana.program.token.v1.CreateToken2022MintRequest.extensions:type_name -> protochain.solana.program.token.v1.Token2022Extension
	24, // 1: protochain.solana.program.token.v1.CreateToken2022MintResponse.instructions:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	25, // 2: protochain.solana.program.token.v1.CreateSPLTokenMintRequest.metadata:type_name -> protochain.solana.program.token.v1.MetaplexTokenMetadata
	24, // 3: protochain.solana.program.token.v1.CreateSPLTokenMintResponse.instructions:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	6,  // 4: protochain.solana.program.token.v1.ParseMintResponse.mint:type_name -> protochain.solana.program.token.v1.MintInfo
	26, // 5: protochain.solana.program.token.v1.ParseMintResponse.token_program:type_name -> protochain.solana.program.token.v1.TokenProgram
	23, // 6: protochain.solana.program.token.v1.ParseMintResponse.extensions:type_name -> protochain.solana.program.token.v1.Token2022Extension
	25, // 7: protochain.solana.program.token.v1.ParseMintResponse.metaplex_metadata:type_name -> protochain.solana.program.token.v1.MetaplexTokenMetadata
	27, // 8: protochain.solana.program.token.v1.CreateToken2022HoldingAccountRequest.extensions:type_name -> protochain.solana.program.token.v1.Token2022HoldingAccountExtension
	24, // 9: protochain.solana.program.token.v1.CreateToken2022HoldingAccountResponse.instructions:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	24, // 10: protochain.solana.program.token.v1.CreateSPLTokenHoldingAccountResponse.instructions:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	24, // 11: protochain.solana.program.token.v1.MintResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	24, // 12: protochain.solana.program.token.v1.FreezeTokenAccountResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	24, // 13: protochain.solana.program.token.v1.ThawTokenAccountResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	24, // 14: protochain.solana.program.token.v1.CloseTokenAccountResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	24, // 15: protochain.solana.program.token.v1.BurnTokenResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	24, // 16: protochain.solana.program.token.v1.TransferTokenResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	0,  // 17: protochain.solana.program.token.v1.Service.CreateToken2022Mint:input_type -> protochain.solana.program.token.v1.CreateToken2022MintRequest
	2,  // 18: protochain.solana.program.token.v1.Service.CreateSPLTokenMint:input_type -> protochain.solana.program.token.v1.CreateSPLTokenMintRequest
	4,  // 19: protochain.solana.program.token.v1.Service.ParseMint:input_type -> protochain.solana.program.token.v1.ParseMintRequest
	7,  // 20: protochain.solana.program.token.v1.Service.CreateToken2022HoldingAccount:input_type -> protochain.solana.program.token.v1.CreateToken2022HoldingAccountRequest
	9,  // 21: protochain.solana.program.token.v1.Service.CreateSPLTokenHoldingAccount:input_type -> protochain.solana.program.token.v1.CreateSPLTokenHoldingAccountRequest
	11, // 22: protochain.solana.program.token.v1.Service.Mint:input_type -> protochain.solana.program.token.v1.MintRequest
	13, // 23: protochain.solana.program.token.v1.Service.FreezeTokenAccount:input_type -> protochain.solana.program.token.v1.FreezeTokenAccountRequest
	15, // 24: protochain.solana.program.token.v1.Service.ThawTokenAccount:input_type -> protochain.solana.program.token.v1.ThawTokenAccountRequest
	19, // 25: protochain.solana.program.token.v1.Service.BurnToken:input_type -> protochain.solana.program.token.v1.BurnTokenRequest
	21, // 26: protochain.solana.program.token.v1.Service.TransferToken:input_type -> protochain.solana.program.token.v1.TransferTokenRequest
	17, // 27: protochain.solana.program.token.v1.Service.CloseTokenAccount:input_type -> protochain.solana.program.token.v1.CloseTokenAccountRequest
	1,  // 28: protochain.solana.program.token.v1.Service.CreateToken2022Mint:output_type -> protochain.solana.program.token.v1.CreateToken2022MintResponse
	3,  // 29: protochain.solana.program.token.v1.Service.CreateSPLTokenMint:output_type -> protochain.solana.program.token.v1.CreateSPLTokenMintResponse
	5,  // 30: protochain.solana.program.token.v1.Service.ParseMint:output_type -> protochain.solana.program.token.v1.ParseMintResponse
	8,  // 31: protochain.solana.program.token.v1.Service.CreateToken2022HoldingAccount:output_type -> protochain.solana.program.token.v1.CreateToken2022HoldingAccountResponse
	10, // 32: protochain.solana.program.token.v1.Service.CreateSPLTokenHoldingAccount:output_type -> protochain.solana.program.token.v1.CreateSPLTokenHoldingAccountResponse
	12, // 33: protochain.solana.program.token.v1.Service.Mint:output_type -> protochain.solana.program.token.v1.MintResponse
	14, // 34: protochain.solana.program.token.v1.Service.FreezeTokenAccount:output_type -> protochain.solana.program.token.v1.FreezeTokenAccountResponse
	16, // 35: protochain.solana.program.token.v1.Service.ThawTokenAccount:output_type -> protochain.solana.program.token.v1.ThawTokenAccountResponse
	20, // 36: protochain.solana.program.token.v1.Service.BurnToken:output_type -> protochain.solana.program.token.v1.BurnTokenResponse
	22, // 37: protochain.solana.program.token.v1.Service.TransferToken:output_type -> protochain.solana.program.token.v1.TransferTokenResponse
	18, // 38: protochain.solana.program.token.v1.Service.CloseTokenAccount:output_type -> protochain.solana.program.token.v1.CloseTokenAccountResponse
	28, // [28:39] is the sub-list for method output_type
	17, // [17:28] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_protochain_solana_program_token_v1_service_proto_init() }
func file_protochain_solana_program_token_v1_service_proto_init() {
	if File_protochain_solana_program_token_v1_service_proto != nil {
		return
	}
	file_protochain_solana_program_token_v1_spl_token_metadata_proto_init()
	file_protochain_solana_program_token_v1_token2022_extension_proto_init()
	file_protochain_solana_program_token_v1_token2022_holding_account_extension_proto_init()
	file_protochain_solana_program_token_v1_token_program_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_service_proto_rawDesc), len(file_protochain_solana_program_token_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protochain_solana_program_token_v1_service_proto_goTypes,
		DependencyIndexes: file_protochain_solana_program_token_v1_service_proto_depIdxs,
		MessageInfos:      file_protochain_solana_program_token_v1_service_proto_msgTypes,
	}.Build()
	File_protochain_solana_program_token_v1_service_proto = out.File
	file_protochain_solana_program_token_v1_service_proto_goTypes = nil
	file_protochain_solana_program_token_v1_service_proto_depIdxs = nil
}
