// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: protochain/solana/program/token/v1/service.proto

package token_v1

import (
	v11 "github.com/meshtrade/protochain/lib/go/protochain/solana/transaction/v1"
	v1 "github.com/meshtrade/protochain/lib/go/protochain/solana/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create InitialiseMint instruction
type InitialiseMintRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MintPubKey            string                 `protobuf:"bytes,1,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`
	MintAuthorityPubKey   string                 `protobuf:"bytes,2,opt,name=mint_authority_pub_key,json=mintAuthorityPubKey,proto3" json:"mint_authority_pub_key,omitempty"`
	FreezeAuthorityPubKey string                 `protobuf:"bytes,3,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"`
	Decimals              uint32                 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	TokenProgram          v1.TokenProgram        `protobuf:"varint,5,opt,name=token_program,json=tokenProgram,proto3,enum=protochain.solana.type.v1.TokenProgram" json:"token_program,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *InitialiseMintRequest) Reset() {
	*x = InitialiseMintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseMintRequest) ProtoMessage() {}

func (x *InitialiseMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseMintRequest.ProtoReflect.Descriptor instead.
func (*InitialiseMintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *InitialiseMintRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *InitialiseMintRequest) GetMintAuthorityPubKey() string {
	if x != nil {
		return x.MintAuthorityPubKey
	}
	return ""
}

func (x *InitialiseMintRequest) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

func (x *InitialiseMintRequest) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *InitialiseMintRequest) GetTokenProgram() v1.TokenProgram {
	if x != nil {
		return x.TokenProgram
	}
	return v1.TokenProgram(0)
}

// Response containing InitialiseMint instruction
type InitialiseMintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v11.SolanaInstruction `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialiseMintResponse) Reset() {
	*x = InitialiseMintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialiseMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialiseMintResponse) ProtoMessage() {}

func (x *InitialiseMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialiseMintResponse.ProtoReflect.Descriptor instead.
func (*InitialiseMintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *InitialiseMintResponse) GetInstruction() *v11.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

// Request to get current rent for token account
type GetCurrentMinRentForTokenAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentMinRentForTokenAccountRequest) Reset() {
	*x = GetCurrentMinRentForTokenAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentMinRentForTokenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentMinRentForTokenAccountRequest) ProtoMessage() {}

func (x *GetCurrentMinRentForTokenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentMinRentForTokenAccountRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentMinRentForTokenAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{2}
}

// Response with current rent amount
type GetCurrentMinRentForTokenAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lamports      uint64                 `protobuf:"varint,1,opt,name=lamports,proto3" json:"lamports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentMinRentForTokenAccountResponse) Reset() {
	*x = GetCurrentMinRentForTokenAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentMinRentForTokenAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentMinRentForTokenAccountResponse) ProtoMessage() {}

func (x *GetCurrentMinRentForTokenAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentMinRentForTokenAccountResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentMinRentForTokenAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentMinRentForTokenAccountResponse) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

// Request to parse mint account
type ParseMintRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountAddress string                 `protobuf:"bytes,1,opt,name=account_address,json=accountAddress,proto3" json:"account_address,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ParseMintRequest) Reset() {
	*x = ParseMintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseMintRequest) ProtoMessage() {}

func (x *ParseMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseMintRequest.ProtoReflect.Descriptor instead.
func (*ParseMintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *ParseMintRequest) GetAccountAddress() string {
	if x != nil {
		return x.AccountAddress
	}
	return ""
}

// Response with parsed mint data
type ParseMintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mint          *MintInfo              `protobuf:"bytes,1,opt,name=mint,proto3" json:"mint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseMintResponse) Reset() {
	*x = ParseMintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseMintResponse) ProtoMessage() {}

func (x *ParseMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseMintResponse.ProtoReflect.Descriptor instead.
func (*ParseMintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *ParseMintResponse) GetMint() *MintInfo {
	if x != nil {
		return x.Mint
	}
	return nil
}

// Structured mint account information
type MintInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MintAuthorityPubKey   string                 `protobuf:"bytes,1,opt,name=mint_authority_pub_key,json=mintAuthorityPubKey,proto3" json:"mint_authority_pub_key,omitempty"`
	FreezeAuthorityPubKey string                 `protobuf:"bytes,2,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"`
	Decimals              uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Supply                string                 `protobuf:"bytes,4,opt,name=supply,proto3" json:"supply,omitempty"`
	IsInitialized         bool                   `protobuf:"varint,5,opt,name=is_initialized,json=isInitialized,proto3" json:"is_initialized,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *MintInfo) Reset() {
	*x = MintInfo{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintInfo) ProtoMessage() {}

func (x *MintInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintInfo.ProtoReflect.Descriptor instead.
func (*MintInfo) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *MintInfo) GetMintAuthorityPubKey() string {
	if x != nil {
		return x.MintAuthorityPubKey
	}
	return ""
}

func (x *MintInfo) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

func (x *MintInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *MintInfo) GetSupply() string {
	if x != nil {
		return x.Supply
	}
	return ""
}

func (x *MintInfo) GetIsInitialized() bool {
	if x != nil {
		return x.IsInitialized
	}
	return false
}

type MemoTransferConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Require every inbound transfer into the account to include a memo.
	RequireIncomingMemo bool `protobuf:"varint,1,opt,name=require_incoming_memo,json=requireIncomingMemo,proto3" json:"require_incoming_memo,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MemoTransferConfig) Reset() {
	*x = MemoTransferConfig{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoTransferConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoTransferConfig) ProtoMessage() {}

func (x *MemoTransferConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoTransferConfig.ProtoReflect.Descriptor instead.
func (*MemoTransferConfig) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *MemoTransferConfig) GetRequireIncomingMemo() bool {
	if x != nil {
		return x.RequireIncomingMemo
	}
	return false
}

// Request to get current rent for holding account
type GetCurrentMinRentForHoldingAccountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MemoTransferConfig *MemoTransferConfig    `protobuf:"bytes,1,opt,name=memo_transfer_config,json=memoTransferConfig,proto3" json:"memo_transfer_config,omitempty"` // optional, defaults to false
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetCurrentMinRentForHoldingAccountRequest) Reset() {
	*x = GetCurrentMinRentForHoldingAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentMinRentForHoldingAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentMinRentForHoldingAccountRequest) ProtoMessage() {}

func (x *GetCurrentMinRentForHoldingAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentMinRentForHoldingAccountRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentMinRentForHoldingAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetCurrentMinRentForHoldingAccountRequest) GetMemoTransferConfig() *MemoTransferConfig {
	if x != nil {
		return x.MemoTransferConfig
	}
	return nil
}

// Response with current rent amount for holding account
type GetCurrentMinRentForHoldingAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lamports      uint64                 `protobuf:"varint,1,opt,name=lamports,proto3" json:"lamports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentMinRentForHoldingAccountResponse) Reset() {
	*x = GetCurrentMinRentForHoldingAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentMinRentForHoldingAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentMinRentForHoldingAccountResponse) ProtoMessage() {}

func (x *GetCurrentMinRentForHoldingAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentMinRentForHoldingAccountResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentMinRentForHoldingAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetCurrentMinRentForHoldingAccountResponse) GetLamports() uint64 {
	if x != nil {
		return x.Lamports
	}
	return 0
}

// Request to create and initialize a holding account in one call
type CreateHoldingAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System program create fields
	Payer      string `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`                             // Account paying for creation (signer)
	NewAccount string `protobuf:"bytes,2,opt,name=new_account,json=newAccount,proto3" json:"new_account,omitempty"` // Holding account to create (signer)
	// Token program initialize holding account fields
	HoldingAccountPubKey string              `protobuf:"bytes,3,opt,name=holding_account_pub_key,json=holdingAccountPubKey,proto3" json:"holding_account_pub_key,omitempty"` // Same as new_account for validation
	MintPubKey           string              `protobuf:"bytes,4,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`                                 // Mint this account will hold
	OwnerPubKey          string              `protobuf:"bytes,5,opt,name=owner_pub_key,json=ownerPubKey,proto3" json:"owner_pub_key,omitempty"`                              // Owner of the holding account
	MemoTransferConfig   *MemoTransferConfig `protobuf:"bytes,6,opt,name=memo_transfer_config,json=memoTransferConfig,proto3" json:"memo_transfer_config,omitempty"`         // optional, defaults to false
	TokenProgram         v1.TokenProgram     `protobuf:"varint,7,opt,name=token_program,json=tokenProgram,proto3,enum=protochain.solana.type.v1.TokenProgram" json:"token_program,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateHoldingAccountRequest) Reset() {
	*x = CreateHoldingAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHoldingAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHoldingAccountRequest) ProtoMessage() {}

func (x *CreateHoldingAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHoldingAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateHoldingAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateHoldingAccountRequest) GetPayer() string {
	if x != nil {
		return x.Payer
	}
	return ""
}

func (x *CreateHoldingAccountRequest) GetNewAccount() string {
	if x != nil {
		return x.NewAccount
	}
	return ""
}

func (x *CreateHoldingAccountRequest) GetHoldingAccountPubKey() string {
	if x != nil {
		return x.HoldingAccountPubKey
	}
	return ""
}

func (x *CreateHoldingAccountRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *CreateHoldingAccountRequest) GetOwnerPubKey() string {
	if x != nil {
		return x.OwnerPubKey
	}
	return ""
}

func (x *CreateHoldingAccountRequest) GetMemoTransferConfig() *MemoTransferConfig {
	if x != nil {
		return x.MemoTransferConfig
	}
	return nil
}

func (x *CreateHoldingAccountRequest) GetTokenProgram() v1.TokenProgram {
	if x != nil {
		return x.TokenProgram
	}
	return v1.TokenProgram(0)
}

// Response containing both create and initialize instructions
type CreateHoldingAccountResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Instructions  []*v11.SolanaInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHoldingAccountResponse) Reset() {
	*x = CreateHoldingAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHoldingAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHoldingAccountResponse) ProtoMessage() {}

func (x *CreateHoldingAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHoldingAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateHoldingAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateHoldingAccountResponse) GetInstructions() []*v11.SolanaInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// Request to create and initialize a mint account in one call
type CreateMintRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System program create fields
	Payer      string `protobuf:"bytes,1,opt,name=payer,proto3" json:"payer,omitempty"`                             // Account paying for creation (signer)
	NewAccount string `protobuf:"bytes,2,opt,name=new_account,json=newAccount,proto3" json:"new_account,omitempty"` // Mint account to create (signer)
	// Token program initialize mint fields
	MintPubKey            string          `protobuf:"bytes,3,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`                                    // Same as new_account for validation
	MintAuthorityPubKey   string          `protobuf:"bytes,4,opt,name=mint_authority_pub_key,json=mintAuthorityPubKey,proto3" json:"mint_authority_pub_key,omitempty"`       // Mint authority
	FreezeAuthorityPubKey string          `protobuf:"bytes,5,opt,name=freeze_authority_pub_key,json=freezeAuthorityPubKey,proto3" json:"freeze_authority_pub_key,omitempty"` // Freeze authority (optional)
	Decimals              uint32          `protobuf:"varint,6,opt,name=decimals,proto3" json:"decimals,omitempty"`                                                           // Mint decimals
	TokenProgram          v1.TokenProgram `protobuf:"varint,7,opt,name=token_program,json=tokenProgram,proto3,enum=protochain.solana.type.v1.TokenProgram" json:"token_program,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateMintRequest) Reset() {
	*x = CreateMintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMintRequest) ProtoMessage() {}

func (x *CreateMintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMintRequest.ProtoReflect.Descriptor instead.
func (*CreateMintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMintRequest) GetPayer() string {
	if x != nil {
		return x.Payer
	}
	return ""
}

func (x *CreateMintRequest) GetNewAccount() string {
	if x != nil {
		return x.NewAccount
	}
	return ""
}

func (x *CreateMintRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *CreateMintRequest) GetMintAuthorityPubKey() string {
	if x != nil {
		return x.MintAuthorityPubKey
	}
	return ""
}

func (x *CreateMintRequest) GetFreezeAuthorityPubKey() string {
	if x != nil {
		return x.FreezeAuthorityPubKey
	}
	return ""
}

func (x *CreateMintRequest) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CreateMintRequest) GetTokenProgram() v1.TokenProgram {
	if x != nil {
		return x.TokenProgram
	}
	return v1.TokenProgram(0)
}

// Response containing both create and initialize instructions
type CreateMintResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Instructions  []*v11.SolanaInstruction `protobuf:"bytes,1,rep,name=instructions,proto3" json:"instructions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMintResponse) Reset() {
	*x = CreateMintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMintResponse) ProtoMessage() {}

func (x *CreateMintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMintResponse.ProtoReflect.Descriptor instead.
func (*CreateMintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateMintResponse) GetInstructions() []*v11.SolanaInstruction {
	if x != nil {
		return x.Instructions
	}
	return nil
}

// Request to mint tokens to a token account
type MintRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MintPubKey               string                 `protobuf:"bytes,1,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`                                             // The mint to mint from
	DestinationAccountPubKey string                 `protobuf:"bytes,2,opt,name=destination_account_pub_key,json=destinationAccountPubKey,proto3" json:"destination_account_pub_key,omitempty"` // Token account to mint to
	MintAuthorityPubKey      string                 `protobuf:"bytes,3,opt,name=mint_authority_pub_key,json=mintAuthorityPubKey,proto3" json:"mint_authority_pub_key,omitempty"`                // Authority that can mint tokens
	Amount                   string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                                                                         // Amount to mint (as string to handle large numbers)
	Decimals                 uint32                 `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`                                                                    // Expected decimals for validation
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MintRequest) Reset() {
	*x = MintRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintRequest) ProtoMessage() {}

func (x *MintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintRequest.ProtoReflect.Descriptor instead.
func (*MintRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *MintRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

func (x *MintRequest) GetDestinationAccountPubKey() string {
	if x != nil {
		return x.DestinationAccountPubKey
	}
	return ""
}

func (x *MintRequest) GetMintAuthorityPubKey() string {
	if x != nil {
		return x.MintAuthorityPubKey
	}
	return ""
}

func (x *MintRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *MintRequest) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

// Response containing Mint instruction
type MintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v11.SolanaInstruction `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintResponse) Reset() {
	*x = MintResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintResponse) ProtoMessage() {}

func (x *MintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintResponse.ProtoReflect.Descriptor instead.
func (*MintResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *MintResponse) GetInstruction() *v11.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

type CreateAssociatedTokenAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayerPubKey   string                 `protobuf:"bytes,1,opt,name=payer_pub_key,json=payerPubKey,proto3" json:"payer_pub_key,omitempty"` // public key of the account paying for creation
	OwnerPubKey   string                 `protobuf:"bytes,2,opt,name=owner_pub_key,json=ownerPubKey,proto3" json:"owner_pub_key,omitempty"` // public key for the owner of the token account to be created
	MintPubKey    string                 `protobuf:"bytes,3,opt,name=mint_pub_key,json=mintPubKey,proto3" json:"mint_pub_key,omitempty"`    // public key of the mint token account
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssociatedTokenAccountRequest) Reset() {
	*x = CreateAssociatedTokenAccountRequest{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssociatedTokenAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssociatedTokenAccountRequest) ProtoMessage() {}

func (x *CreateAssociatedTokenAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssociatedTokenAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAssociatedTokenAccountRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAssociatedTokenAccountRequest) GetPayerPubKey() string {
	if x != nil {
		return x.PayerPubKey
	}
	return ""
}

func (x *CreateAssociatedTokenAccountRequest) GetOwnerPubKey() string {
	if x != nil {
		return x.OwnerPubKey
	}
	return ""
}

func (x *CreateAssociatedTokenAccountRequest) GetMintPubKey() string {
	if x != nil {
		return x.MintPubKey
	}
	return ""
}

type CreateAssociatedTokenAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instruction   *v11.SolanaInstruction `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAssociatedTokenAccountResponse) Reset() {
	*x = CreateAssociatedTokenAccountResponse{}
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAssociatedTokenAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAssociatedTokenAccountResponse) ProtoMessage() {}

func (x *CreateAssociatedTokenAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAssociatedTokenAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAssociatedTokenAccountResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *CreateAssociatedTokenAccountResponse) GetInstruction() *v11.SolanaInstruction {
	if x != nil {
		return x.Instruction
	}
	return nil
}

var File_protochain_solana_program_token_v1_service_proto protoreflect.FileDescriptor

const file_protochain_solana_program_token_v1_service_proto_rawDesc = "" +
	"\n" +
	"0protochain/solana/program/token/v1/service.proto\x12\"protochain.solana.program.token.v1\x1a2protochain/solana/transaction/v1/instruction.proto\x1a-protochain/solana/type/v1/token_program.proto\"\x91\x02\n" +
	"\x15InitialiseMintRequest\x12 \n" +
	"\fmint_pub_key\x18\x01 \x01(\tR\n" +
	"mintPubKey\x123\n" +
	"\x16mint_authority_pub_key\x18\x02 \x01(\tR\x13mintAuthorityPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x03 \x01(\tR\x15freezeAuthorityPubKey\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\rR\bdecimals\x12L\n" +
	"\rtoken_program\x18\x05 \x01(\x0e2'.protochain.solana.type.v1.TokenProgramR\ftokenProgram\"o\n" +
	"\x16InitialiseMintResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction\")\n" +
	"'GetCurrentMinRentForTokenAccountRequest\"F\n" +
	"(GetCurrentMinRentForTokenAccountResponse\x12\x1a\n" +
	"\blamports\x18\x01 \x01(\x04R\blamports\";\n" +
	"\x10ParseMintRequest\x12'\n" +
	"\x0faccount_address\x18\x01 \x01(\tR\x0eaccountAddress\"U\n" +
	"\x11ParseMintResponse\x12@\n" +
	"\x04mint\x18\x01 \x01(\v2,.protochain.solana.program.token.v1.MintInfoR\x04mint\"\xd3\x01\n" +
	"\bMintInfo\x123\n" +
	"\x16mint_authority_pub_key\x18\x01 \x01(\tR\x13mintAuthorityPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x02 \x01(\tR\x15freezeAuthorityPubKey\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12\x16\n" +
	"\x06supply\x18\x04 \x01(\tR\x06supply\x12%\n" +
	"\x0eis_initialized\x18\x05 \x01(\bR\risInitialized\"H\n" +
	"\x12MemoTransferConfig\x122\n" +
	"\x15require_incoming_memo\x18\x01 \x01(\bR\x13requireIncomingMemo\"\x95\x01\n" +
	")GetCurrentMinRentForHoldingAccountRequest\x12h\n" +
	"\x14memo_transfer_config\x18\x01 \x01(\v26.protochain.solana.program.token.v1.MemoTransferConfigR\x12memoTransferConfig\"H\n" +
	"*GetCurrentMinRentForHoldingAccountResponse\x12\x1a\n" +
	"\blamports\x18\x01 \x01(\x04R\blamports\"\x89\x03\n" +
	"\x1bCreateHoldingAccountRequest\x12\x14\n" +
	"\x05payer\x18\x01 \x01(\tR\x05payer\x12\x1f\n" +
	"\vnew_account\x18\x02 \x01(\tR\n" +
	"newAccount\x125\n" +
	"\x17holding_account_pub_key\x18\x03 \x01(\tR\x14holdingAccountPubKey\x12 \n" +
	"\fmint_pub_key\x18\x04 \x01(\tR\n" +
	"mintPubKey\x12\"\n" +
	"\rowner_pub_key\x18\x05 \x01(\tR\vownerPubKey\x12h\n" +
	"\x14memo_transfer_config\x18\x06 \x01(\v26.protochain.solana.program.token.v1.MemoTransferConfigR\x12memoTransferConfig\x12L\n" +
	"\rtoken_program\x18\a \x01(\x0e2'.protochain.solana.type.v1.TokenProgramR\ftokenProgram\"w\n" +
	"\x1cCreateHoldingAccountResponse\x12W\n" +
	"\finstructions\x18\x01 \x03(\v23.protochain.solana.transaction.v1.SolanaInstructionR\finstructions\"\xc4\x02\n" +
	"\x11CreateMintRequest\x12\x14\n" +
	"\x05payer\x18\x01 \x01(\tR\x05payer\x12\x1f\n" +
	"\vnew_account\x18\x02 \x01(\tR\n" +
	"newAccount\x12 \n" +
	"\fmint_pub_key\x18\x03 \x01(\tR\n" +
	"mintPubKey\x123\n" +
	"\x16mint_authority_pub_key\x18\x04 \x01(\tR\x13mintAuthorityPubKey\x127\n" +
	"\x18freeze_authority_pub_key\x18\x05 \x01(\tR\x15freezeAuthorityPubKey\x12\x1a\n" +
	"\bdecimals\x18\x06 \x01(\rR\bdecimals\x12L\n" +
	"\rtoken_program\x18\a \x01(\x0e2'.protochain.solana.type.v1.TokenProgramR\ftokenProgram\"m\n" +
	"\x12CreateMintResponse\x12W\n" +
	"\finstructions\x18\x01 \x03(\v23.protochain.solana.transaction.v1.SolanaInstructionR\finstructions\"\xd7\x01\n" +
	"\vMintRequest\x12 \n" +
	"\fmint_pub_key\x18\x01 \x01(\tR\n" +
	"mintPubKey\x12=\n" +
	"\x1bdestination_account_pub_key\x18\x02 \x01(\tR\x18destinationAccountPubKey\x123\n" +
	"\x16mint_authority_pub_key\x18\x03 \x01(\tR\x13mintAuthorityPubKey\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bdecimals\x18\x05 \x01(\rR\bdecimals\"e\n" +
	"\fMintResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction\"\x8f\x01\n" +
	"#CreateAssociatedTokenAccountRequest\x12\"\n" +
	"\rpayer_pub_key\x18\x01 \x01(\tR\vpayerPubKey\x12\"\n" +
	"\rowner_pub_key\x18\x02 \x01(\tR\vownerPubKey\x12 \n" +
	"\fmint_pub_key\x18\x03 \x01(\tR\n" +
	"mintPubKey\"}\n" +
	"$CreateAssociatedTokenAccountResponse\x12U\n" +
	"\vinstruction\x18\x01 \x01(\v23.protochain.solana.transaction.v1.SolanaInstructionR\vinstruction2\xcb\t\n" +
	"\aService\x12\x87\x01\n" +
	"\x0eInitialiseMint\x129.protochain.solana.program.token.v1.InitialiseMintRequest\x1a:.protochain.solana.program.token.v1.InitialiseMintResponse\x12\xbd\x01\n" +
	" GetCurrentMinRentForTokenAccount\x12K.protochain.solana.program.token.v1.GetCurrentMinRentForTokenAccountRequest\x1aL.protochain.solana.program.token.v1.GetCurrentMinRentForTokenAccountResponse\x12x\n" +
	"\tParseMint\x124.protochain.solana.program.token.v1.ParseMintRequest\x1a5.protochain.solana.program.token.v1.ParseMintResponse\x12\xc3\x01\n" +
	"\"GetCurrentMinRentForHoldingAccount\x12M.protochain.solana.program.token.v1.GetCurrentMinRentForHoldingAccountRequest\x1aN.protochain.solana.program.token.v1.GetCurrentMinRentForHoldingAccountResponse\x12{\n" +
	"\n" +
	"CreateMint\x125.protochain.solana.program.token.v1.CreateMintRequest\x1a6.protochain.solana.program.token.v1.CreateMintResponse\x12\x99\x01\n" +
	"\x14CreateHoldingAccount\x12?.protochain.solana.program.token.v1.CreateHoldingAccountRequest\x1a@.protochain.solana.program.token.v1.CreateHoldingAccountResponse\x12i\n" +
	"\x04Mint\x12/.protochain.solana.program.token.v1.MintRequest\x1a0.protochain.solana.program.token.v1.MintResponse\x12\xb1\x01\n" +
	"\x1cCreateAssociatedTokenAccount\x12G.protochain.solana.program.token.v1.CreateAssociatedTokenAccountRequest\x1aH.protochain.solana.program.token.v1.CreateAssociatedTokenAccountResponseBTZRgithub.com/meshtrade/protochain/lib/go/protochain/solana/program/token/v1;token_v1b\x06proto3"

var (
	file_protochain_solana_program_token_v1_service_proto_rawDescOnce sync.Once
	file_protochain_solana_program_token_v1_service_proto_rawDescData []byte
)

func file_protochain_solana_program_token_v1_service_proto_rawDescGZIP() []byte {
	file_protochain_solana_program_token_v1_service_proto_rawDescOnce.Do(func() {
		file_protochain_solana_program_token_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_service_proto_rawDesc), len(file_protochain_solana_program_token_v1_service_proto_rawDesc)))
	})
	return file_protochain_solana_program_token_v1_service_proto_rawDescData
}

var file_protochain_solana_program_token_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_protochain_solana_program_token_v1_service_proto_goTypes = []any{
	(*InitialiseMintRequest)(nil),                      // 0: protochain.solana.program.token.v1.InitialiseMintRequest
	(*InitialiseMintResponse)(nil),                     // 1: protochain.solana.program.token.v1.InitialiseMintResponse
	(*GetCurrentMinRentForTokenAccountRequest)(nil),    // 2: protochain.solana.program.token.v1.GetCurrentMinRentForTokenAccountRequest
	(*GetCurrentMinRentForTokenAccountResponse)(nil),   // 3: protochain.solana.program.token.v1.GetCurrentMinRentForTokenAccountResponse
	(*ParseMintRequest)(nil),                           // 4: protochain.solana.program.token.v1.ParseMintRequest
	(*ParseMintResponse)(nil),                          // 5: protochain.solana.program.token.v1.ParseMintResponse
	(*MintInfo)(nil),                                   // 6: protochain.solana.program.token.v1.MintInfo
	(*MemoTransferConfig)(nil),                         // 7: protochain.solana.program.token.v1.MemoTransferConfig
	(*GetCurrentMinRentForHoldingAccountRequest)(nil),  // 8: protochain.solana.program.token.v1.GetCurrentMinRentForHoldingAccountRequest
	(*GetCurrentMinRentForHoldingAccountResponse)(nil), // 9: protochain.solana.program.token.v1.GetCurrentMinRentForHoldingAccountResponse
	(*CreateHoldingAccountRequest)(nil),                // 10: protochain.solana.program.token.v1.CreateHoldingAccountRequest
	(*CreateHoldingAccountResponse)(nil),               // 11: protochain.solana.program.token.v1.CreateHoldingAccountResponse
	(*CreateMintRequest)(nil),                          // 12: protochain.solana.program.token.v1.CreateMintRequest
	(*CreateMintResponse)(nil),                         // 13: protochain.solana.program.token.v1.CreateMintResponse
	(*MintRequest)(nil),                                // 14: protochain.solana.program.token.v1.MintRequest
	(*MintResponse)(nil),                               // 15: protochain.solana.program.token.v1.MintResponse
	(*CreateAssociatedTokenAccountRequest)(nil),        // 16: protochain.solana.program.token.v1.CreateAssociatedTokenAccountRequest
	(*CreateAssociatedTokenAccountResponse)(nil),       // 17: protochain.solana.program.token.v1.CreateAssociatedTokenAccountResponse
	(v1.TokenProgram)(0),                               // 18: protochain.solana.type.v1.TokenProgram
	(*v11.SolanaInstruction)(nil),                      // 19: protochain.solana.transaction.v1.SolanaInstruction
}
var file_protochain_solana_program_token_v1_service_proto_depIdxs = []int32{
	18, // 0: protochain.solana.program.token.v1.InitialiseMintRequest.token_program:type_name -> protochain.solana.type.v1.TokenProgram
	19, // 1: protochain.solana.program.token.v1.InitialiseMintResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	6,  // 2: protochain.solana.program.token.v1.ParseMintResponse.mint:type_name -> protochain.solana.program.token.v1.MintInfo
	7,  // 3: protochain.solana.program.token.v1.GetCurrentMinRentForHoldingAccountRequest.memo_transfer_config:type_name -> protochain.solana.program.token.v1.MemoTransferConfig
	7,  // 4: protochain.solana.program.token.v1.CreateHoldingAccountRequest.memo_transfer_config:type_name -> protochain.solana.program.token.v1.MemoTransferConfig
	18, // 5: protochain.solana.program.token.v1.CreateHoldingAccountRequest.token_program:type_name -> protochain.solana.type.v1.TokenProgram
	19, // 6: protochain.solana.program.token.v1.CreateHoldingAccountResponse.instructions:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	18, // 7: protochain.solana.program.token.v1.CreateMintRequest.token_program:type_name -> protochain.solana.type.v1.TokenProgram
	19, // 8: protochain.solana.program.token.v1.CreateMintResponse.instructions:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	19, // 9: protochain.solana.program.token.v1.MintResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	19, // 10: protochain.solana.program.token.v1.CreateAssociatedTokenAccountResponse.instruction:type_name -> protochain.solana.transaction.v1.SolanaInstruction
	0,  // 11: protochain.solana.program.token.v1.Service.InitialiseMint:input_type -> protochain.solana.program.token.v1.InitialiseMintRequest
	2,  // 12: protochain.solana.program.token.v1.Service.GetCurrentMinRentForTokenAccount:input_type -> protochain.solana.program.token.v1.GetCurrentMinRentForTokenAccountRequest
	4,  // 13: protochain.solana.program.token.v1.Service.ParseMint:input_type -> protochain.solana.program.token.v1.ParseMintRequest
	8,  // 14: protochain.solana.program.token.v1.Service.GetCurrentMinRentForHoldingAccount:input_type -> protochain.solana.program.token.v1.GetCurrentMinRentForHoldingAccountRequest
	12, // 15: protochain.solana.program.token.v1.Service.CreateMint:input_type -> protochain.solana.program.token.v1.CreateMintRequest
	10, // 16: protochain.solana.program.token.v1.Service.CreateHoldingAccount:input_type -> protochain.solana.program.token.v1.CreateHoldingAccountRequest
	14, // 17: protochain.solana.program.token.v1.Service.Mint:input_type -> protochain.solana.program.token.v1.MintRequest
	16, // 18: protochain.solana.program.token.v1.Service.CreateAssociatedTokenAccount:input_type -> protochain.solana.program.token.v1.CreateAssociatedTokenAccountRequest
	1,  // 19: protochain.solana.program.token.v1.Service.InitialiseMint:output_type -> protochain.solana.program.token.v1.InitialiseMintResponse
	3,  // 20: protochain.solana.program.token.v1.Service.GetCurrentMinRentForTokenAccount:output_type -> protochain.solana.program.token.v1.GetCurrentMinRentForTokenAccountResponse
	5,  // 21: protochain.solana.program.token.v1.Service.ParseMint:output_type -> protochain.solana.program.token.v1.ParseMintResponse
	9,  // 22: protochain.solana.program.token.v1.Service.GetCurrentMinRentForHoldingAccount:output_type -> protochain.solana.program.token.v1.GetCurrentMinRentForHoldingAccountResponse
	13, // 23: protochain.solana.program.token.v1.Service.CreateMint:output_type -> protochain.solana.program.token.v1.CreateMintResponse
	11, // 24: protochain.solana.program.token.v1.Service.CreateHoldingAccount:output_type -> protochain.solana.program.token.v1.CreateHoldingAccountResponse
	15, // 25: protochain.solana.program.token.v1.Service.Mint:output_type -> protochain.solana.program.token.v1.MintResponse
	17, // 26: protochain.solana.program.token.v1.Service.CreateAssociatedTokenAccount:output_type -> protochain.solana.program.token.v1.CreateAssociatedTokenAccountResponse
	19, // [19:27] is the sub-list for method output_type
	11, // [11:19] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protochain_solana_program_token_v1_service_proto_init() }
func file_protochain_solana_program_token_v1_service_proto_init() {
	if File_protochain_solana_program_token_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_service_proto_rawDesc), len(file_protochain_solana_program_token_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protochain_solana_program_token_v1_service_proto_goTypes,
		DependencyIndexes: file_protochain_solana_program_token_v1_service_proto_depIdxs,
		MessageInfos:      file_protochain_solana_program_token_v1_service_proto_msgTypes,
	}.Build()
	File_protochain_solana_program_token_v1_service_proto = out.File
	file_protochain_solana_program_token_v1_service_proto_goTypes = nil
	file_protochain_solana_program_token_v1_service_proto_depIdxs = nil
}
