// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/program/token/v1/spl_token_metadata.proto

package token_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaplexUses_UseMethod int32

const (
	// Default unspecified value.
	MetaplexUses_USE_METHOD_UNSPECIFIED MetaplexUses_UseMethod = 0
	// The asset is burned after use.
	MetaplexUses_USE_METHOD_BURN MetaplexUses_UseMethod = 1
	// The asset can be used multiple times.
	MetaplexUses_USE_METHOD_MULTIPLE MetaplexUses_UseMethod = 2
	// The asset can be used once.
	MetaplexUses_USE_METHOD_SINGLE MetaplexUses_UseMethod = 3
)

// Enum value maps for MetaplexUses_UseMethod.
var (
	MetaplexUses_UseMethod_name = map[int32]string{
		0: "USE_METHOD_UNSPECIFIED",
		1: "USE_METHOD_BURN",
		2: "USE_METHOD_MULTIPLE",
		3: "USE_METHOD_SINGLE",
	}
	MetaplexUses_UseMethod_value = map[string]int32{
		"USE_METHOD_UNSPECIFIED": 0,
		"USE_METHOD_BURN":        1,
		"USE_METHOD_MULTIPLE":    2,
		"USE_METHOD_SINGLE":      3,
	}
)

func (x MetaplexUses_UseMethod) Enum() *MetaplexUses_UseMethod {
	p := new(MetaplexUses_UseMethod)
	*p = x
	return p
}

func (x MetaplexUses_UseMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetaplexUses_UseMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_protochain_solana_program_token_v1_spl_token_metadata_proto_enumTypes[0].Descriptor()
}

func (MetaplexUses_UseMethod) Type() protoreflect.EnumType {
	return &file_protochain_solana_program_token_v1_spl_token_metadata_proto_enumTypes[0]
}

func (x MetaplexUses_UseMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetaplexUses_UseMethod.Descriptor instead.
func (MetaplexUses_UseMethod) EnumDescriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescGZIP(), []int{3, 0}
}

// Corresponds to the Metaplex DataV2 Rust struct used for on-chain metadata.
// See: https://github.com/metaplex-foundation/mpl-token-metadata
type MetaplexTokenMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full name of the token (e.g. "USD Coin").
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The ticker/symbol of the token (e.g. "USDC").
	Symbol string `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// URL pointing to an off-chain JSON file (Arweave, IPFS, or HTTPS).
	// Follows the Metaplex standard for displaying images and descriptions in wallets.
	// See: https://developers.metaplex.com/smart-contracts/token-metadata/token-standard
	Uri string `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	// Royalties in basis points (100 = 1%).
	SellerFeeBasisPoints uint32 `protobuf:"varint,4,opt,name=seller_fee_basis_points,json=sellerFeeBasisPoints,proto3" json:"seller_fee_basis_points,omitempty"`
	// List of creators and their royalty shares.
	Creators []*MetaplexCreator `protobuf:"bytes,5,rep,name=creators,proto3" json:"creators,omitempty"`
	// Optional collection information grouping this asset.
	Collection *MetaplexCollection `protobuf:"bytes,6,opt,name=collection,proto3,oneof" json:"collection,omitempty"`
	// Optional usage restrictions/rules (primarily for gaming or limited-use assets).
	Uses          *MetaplexUses `protobuf:"bytes,7,opt,name=uses,proto3,oneof" json:"uses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaplexTokenMetadata) Reset() {
	*x = MetaplexTokenMetadata{}
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaplexTokenMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaplexTokenMetadata) ProtoMessage() {}

func (x *MetaplexTokenMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaplexTokenMetadata.ProtoReflect.Descriptor instead.
func (*MetaplexTokenMetadata) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *MetaplexTokenMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetaplexTokenMetadata) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MetaplexTokenMetadata) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MetaplexTokenMetadata) GetSellerFeeBasisPoints() uint32 {
	if x != nil {
		return x.SellerFeeBasisPoints
	}
	return 0
}

func (x *MetaplexTokenMetadata) GetCreators() []*MetaplexCreator {
	if x != nil {
		return x.Creators
	}
	return nil
}

func (x *MetaplexTokenMetadata) GetCollection() *MetaplexCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *MetaplexTokenMetadata) GetUses() *MetaplexUses {
	if x != nil {
		return x.Uses
	}
	return nil
}

// Creator information for royalties.
type MetaplexCreator struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the creator (Base58 encoded string).
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// Whether the creator has signed the metadata (verified).
	Verified bool `protobuf:"varint,2,opt,name=verified,proto3" json:"verified,omitempty"`
	// The percentage of royalties this creator receives (0-100).
	Share         uint32 `protobuf:"varint,3,opt,name=share,proto3" json:"share,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaplexCreator) Reset() {
	*x = MetaplexCreator{}
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaplexCreator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaplexCreator) ProtoMessage() {}

func (x *MetaplexCreator) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaplexCreator.ProtoReflect.Descriptor instead.
func (*MetaplexCreator) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MetaplexCreator) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MetaplexCreator) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *MetaplexCreator) GetShare() uint32 {
	if x != nil {
		return x.Share
	}
	return 0
}

// Collection grouping info.
type MetaplexCollection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the collection has been verified by the authority.
	Verified bool `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	// The mint address of the collection parent NFT (Base58 encoded string).
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaplexCollection) Reset() {
	*x = MetaplexCollection{}
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaplexCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaplexCollection) ProtoMessage() {}

func (x *MetaplexCollection) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaplexCollection.ProtoReflect.Descriptor instead.
func (*MetaplexCollection) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescGZIP(), []int{2}
}

func (x *MetaplexCollection) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *MetaplexCollection) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// Usage rules for the asset.
type MetaplexUses struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How the asset is consumed.
	UseMethod MetaplexUses_UseMethod `protobuf:"varint,1,opt,name=use_method,json=useMethod,proto3,enum=protochain.solana.program.token.v1.MetaplexUses_UseMethod" json:"use_method,omitempty"`
	// Remaining number of uses.
	Remaining uint64 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Total allowed uses.
	Total         uint64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaplexUses) Reset() {
	*x = MetaplexUses{}
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaplexUses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaplexUses) ProtoMessage() {}

func (x *MetaplexUses) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaplexUses.ProtoReflect.Descriptor instead.
func (*MetaplexUses) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescGZIP(), []int{3}
}

func (x *MetaplexUses) GetUseMethod() MetaplexUses_UseMethod {
	if x != nil {
		return x.UseMethod
	}
	return MetaplexUses_USE_METHOD_UNSPECIFIED
}

func (x *MetaplexUses) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *MetaplexUses) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_protochain_solana_program_token_v1_spl_token_metadata_proto protoreflect.FileDescriptor

const file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDesc = "" +
	"\n" +
	";protochain/solana/program/token/v1/spl_token_metadata.proto\x12\"protochain.solana.program.token.v1\"\x9d\x03\n" +
	"\x15MetaplexTokenMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x10\n" +
	"\x03uri\x18\x03 \x01(\tR\x03uri\x125\n" +
	"\x17seller_fee_basis_points\x18\x04 \x01(\rR\x14sellerFeeBasisPoints\x12O\n" +
	"\bcreators\x18\x05 \x03(\v23.protochain.solana.program.token.v1.MetaplexCreatorR\bcreators\x12[\n" +
	"\n" +
	"collection\x18\x06 \x01(\v26.protochain.solana.program.token.v1.MetaplexCollectionH\x00R\n" +
	"collection\x88\x01\x01\x12I\n" +
	"\x04uses\x18\a \x01(\v20.protochain.solana.program.token.v1.MetaplexUsesH\x01R\x04uses\x88\x01\x01B\r\n" +
	"\v_collectionB\a\n" +
	"\x05_uses\"]\n" +
	"\x0fMetaplexCreator\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1a\n" +
	"\bverified\x18\x02 \x01(\bR\bverified\x12\x14\n" +
	"\x05share\x18\x03 \x01(\rR\x05share\"B\n" +
	"\x12MetaplexCollection\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x8b\x02\n" +
	"\fMetaplexUses\x12Y\n" +
	"\n" +
	"use_method\x18\x01 \x01(\x0e2:.protochain.solana.program.token.v1.MetaplexUses.UseMethodR\tuseMethod\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x04R\tremaining\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"l\n" +
	"\tUseMethod\x12\x1a\n" +
	"\x16USE_METHOD_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUSE_METHOD_BURN\x10\x01\x12\x17\n" +
	"\x13USE_METHOD_MULTIPLE\x10\x02\x12\x15\n" +
	"\x11USE_METHOD_SINGLE\x10\x03BTZRgithub.com/meshtrade/protochain/lib/go/protochain/solana/program/token/v1;token_v1b\x06proto3"

var (
	file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescOnce sync.Once
	file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescData []byte
)

func file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescGZIP() []byte {
	file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescOnce.Do(func() {
		file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDesc), len(file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDesc)))
	})
	return file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDescData
}

var file_protochain_solana_program_token_v1_spl_token_metadata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protochain_solana_program_token_v1_spl_token_metadata_proto_goTypes = []any{
	(MetaplexUses_UseMethod)(0),   // 0: protochain.solana.program.token.v1.MetaplexUses.UseMethod
	(*MetaplexTokenMetadata)(nil), // 1: protochain.solana.program.token.v1.MetaplexTokenMetadata
	(*MetaplexCreator)(nil),       // 2: protochain.solana.program.token.v1.MetaplexCreator
	(*MetaplexCollection)(nil),    // 3: protochain.solana.program.token.v1.MetaplexCollection
	(*MetaplexUses)(nil),          // 4: protochain.solana.program.token.v1.MetaplexUses
}
var file_protochain_solana_program_token_v1_spl_token_metadata_proto_depIdxs = []int32{
	2, // 0: protochain.solana.program.token.v1.MetaplexTokenMetadata.creators:type_name -> protochain.solana.program.token.v1.MetaplexCreator
	3, // 1: protochain.solana.program.token.v1.MetaplexTokenMetadata.collection:type_name -> protochain.solana.program.token.v1.MetaplexCollection
	4, // 2: protochain.solana.program.token.v1.MetaplexTokenMetadata.uses:type_name -> protochain.solana.program.token.v1.MetaplexUses
	0, // 3: protochain.solana.program.token.v1.MetaplexUses.use_method:type_name -> protochain.solana.program.token.v1.MetaplexUses.UseMethod
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_protochain_solana_program_token_v1_spl_token_metadata_proto_init() }
func file_protochain_solana_program_token_v1_spl_token_metadata_proto_init() {
	if File_protochain_solana_program_token_v1_spl_token_metadata_proto != nil {
		return
	}
	file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDesc), len(file_protochain_solana_program_token_v1_spl_token_metadata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protochain_solana_program_token_v1_spl_token_metadata_proto_goTypes,
		DependencyIndexes: file_protochain_solana_program_token_v1_spl_token_metadata_proto_depIdxs,
		EnumInfos:         file_protochain_solana_program_token_v1_spl_token_metadata_proto_enumTypes,
		MessageInfos:      file_protochain_solana_program_token_v1_spl_token_metadata_proto_msgTypes,
	}.Build()
	File_protochain_solana_program_token_v1_spl_token_metadata_proto = out.File
	file_protochain_solana_program_token_v1_spl_token_metadata_proto_goTypes = nil
	file_protochain_solana_program_token_v1_spl_token_metadata_proto_depIdxs = nil
}
