// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/program/token/v1/token2022_extension_permanent_delegate.proto

package token_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Configuration for the Token-2022 Permanent Delegate extension.
//
// When enabled, grants an irrevocable delegate authority over ALL token
// accounts for this mint. The permanent delegate can transfer or burn tokens
// from any holder's account without the holder's consent.
//
// Use cases include regulated assets (compliance seizure), subscription
// tokens, and revocable access tokens.
//
// Must be configured at mint creation time. Cannot be changed after
// initialisation.
type Token2022ExtensionPermanentDelegate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The public key of the permanent delegate that has transfer and burn
	// authority over all token accounts for this mint.
	DelegatePubKey string `protobuf:"bytes,1,opt,name=delegate_pub_key,json=delegatePubKey,proto3" json:"delegate_pub_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Token2022ExtensionPermanentDelegate) Reset() {
	*x = Token2022ExtensionPermanentDelegate{}
	mi := &file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token2022ExtensionPermanentDelegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token2022ExtensionPermanentDelegate) ProtoMessage() {}

func (x *Token2022ExtensionPermanentDelegate) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token2022ExtensionPermanentDelegate.ProtoReflect.Descriptor instead.
func (*Token2022ExtensionPermanentDelegate) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDescGZIP(), []int{0}
}

func (x *Token2022ExtensionPermanentDelegate) GetDelegatePubKey() string {
	if x != nil {
		return x.DelegatePubKey
	}
	return ""
}

var File_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto protoreflect.FileDescriptor

const file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDesc = "" +
	"\n" +
	"Oprotochain/solana/program/token/v1/token2022_extension_permanent_delegate.proto\x12\"protochain.solana.program.token.v1\"O\n" +
	"#Token2022ExtensionPermanentDelegate\x12(\n" +
	"\x10delegate_pub_key\x18\x01 \x01(\tR\x0edelegatePubKeyBTZRgithub.com/meshtrade/protochain/lib/go/protochain/solana/program/token/v1;token_v1b\x06proto3"

var (
	file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDescOnce sync.Once
	file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDescData []byte
)

func file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDescGZIP() []byte {
	file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDescOnce.Do(func() {
		file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDesc), len(file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDesc)))
	})
	return file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDescData
}

var file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_goTypes = []any{
	(*Token2022ExtensionPermanentDelegate)(nil), // 0: protochain.solana.program.token.v1.Token2022ExtensionPermanentDelegate
}
var file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() {
	file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_init()
}
func file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_init() {
	if File_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDesc), len(file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_goTypes,
		DependencyIndexes: file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_depIdxs,
		MessageInfos:      file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_msgTypes,
	}.Build()
	File_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto = out.File
	file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_goTypes = nil
	file_protochain_solana_program_token_v1_token2022_extension_permanent_delegate_proto_depIdxs = nil
}
