// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/program/token/v1/token2022_extension_default_account_state.proto

package token_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Possible states for a token account.
type AccountState int32

const (
	// Unspecified / default — should not be used explicitly.
	AccountState_ACCOUNT_STATE_UNSPECIFIED AccountState = 0
	// Accounts are created in the normal initialized state (default behaviour
	// when this extension is not present).
	AccountState_ACCOUNT_STATE_INITIALIZED AccountState = 1
	// Accounts are created in the frozen state. The freeze authority must
	// explicitly thaw each account before the owner can transact.
	AccountState_ACCOUNT_STATE_FROZEN AccountState = 2
)

// Enum value maps for AccountState.
var (
	AccountState_name = map[int32]string{
		0: "ACCOUNT_STATE_UNSPECIFIED",
		1: "ACCOUNT_STATE_INITIALIZED",
		2: "ACCOUNT_STATE_FROZEN",
	}
	AccountState_value = map[string]int32{
		"ACCOUNT_STATE_UNSPECIFIED": 0,
		"ACCOUNT_STATE_INITIALIZED": 1,
		"ACCOUNT_STATE_FROZEN":      2,
	}
)

func (x AccountState) Enum() *AccountState {
	p := new(AccountState)
	*p = x
	return p
}

func (x AccountState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountState) Descriptor() protoreflect.EnumDescriptor {
	return file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_enumTypes[0].Descriptor()
}

func (AccountState) Type() protoreflect.EnumType {
	return &file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_enumTypes[0]
}

func (x AccountState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountState.Descriptor instead.
func (AccountState) EnumDescriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescGZIP(), []int{0}
}

// Configuration for the Token-2022 Default Account State extension.
//
// When enabled, all new token accounts for this mint are created in the
// specified default state. This is commonly used with `FROZEN` to require
// the freeze authority to explicitly approve each holder before they can
// transact.
//
// Requires the mint to have a freeze authority set.
// Must be configured at mint creation time.
type Token2022ExtensionDefaultAccountState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The default state for new token accounts.
	State         AccountState `protobuf:"varint,1,opt,name=state,proto3,enum=protochain.solana.program.token.v1.AccountState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Token2022ExtensionDefaultAccountState) Reset() {
	*x = Token2022ExtensionDefaultAccountState{}
	mi := &file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Token2022ExtensionDefaultAccountState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token2022ExtensionDefaultAccountState) ProtoMessage() {}

func (x *Token2022ExtensionDefaultAccountState) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token2022ExtensionDefaultAccountState.ProtoReflect.Descriptor instead.
func (*Token2022ExtensionDefaultAccountState) Descriptor() ([]byte, []int) {
	return file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescGZIP(), []int{0}
}

func (x *Token2022ExtensionDefaultAccountState) GetState() AccountState {
	if x != nil {
		return x.State
	}
	return AccountState_ACCOUNT_STATE_UNSPECIFIED
}

var File_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto protoreflect.FileDescriptor

const file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDesc = "" +
	"\n" +
	"Rprotochain/solana/program/token/v1/token2022_extension_default_account_state.proto\x12\"protochain.solana.program.token.v1\"o\n" +
	"%Token2022ExtensionDefaultAccountState\x12F\n" +
	"\x05state\x18\x01 \x01(\x0e20.protochain.solana.program.token.v1.AccountStateR\x05state*f\n" +
	"\fAccountState\x12\x1d\n" +
	"\x19ACCOUNT_STATE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19ACCOUNT_STATE_INITIALIZED\x10\x01\x12\x18\n" +
	"\x14ACCOUNT_STATE_FROZEN\x10\x02BTZRgithub.com/meshtrade/protochain/lib/go/protochain/solana/program/token/v1;token_v1b\x06proto3"

var (
	file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescOnce sync.Once
	file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescData []byte
)

func file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescGZIP() []byte {
	file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescOnce.Do(func() {
		file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDesc), len(file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDesc)))
	})
	return file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDescData
}

var file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_goTypes = []any{
	(AccountState)(0), // 0: protochain.solana.program.token.v1.AccountState
	(*Token2022ExtensionDefaultAccountState)(nil), // 1: protochain.solana.program.token.v1.Token2022ExtensionDefaultAccountState
}
var file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_depIdxs = []int32{
	0, // 0: protochain.solana.program.token.v1.Token2022ExtensionDefaultAccountState.state:type_name -> protochain.solana.program.token.v1.AccountState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() {
	file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_init()
}
func file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_init() {
	if File_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDesc), len(file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_goTypes,
		DependencyIndexes: file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_depIdxs,
		EnumInfos:         file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_enumTypes,
		MessageInfos:      file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_msgTypes,
	}.Build()
	File_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto = out.File
	file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_goTypes = nil
	file_protochain_solana_program_token_v1_token2022_extension_default_account_state_proto_depIdxs = nil
}
