// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file protochain/solana/account/v1/account.proto (package protochain.solana.account.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file protochain/solana/account/v1/account.proto.
 */
export const file_protochain_solana_account_v1_account: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Cipwcm90b2NoYWluL3NvbGFuYS9hY2NvdW50L3YxL2FjY291bnQucHJvdG8SHHByb3RvY2hhaW4uc29sYW5hLmFjY291bnQudjEicQoHQWNjb3VudBIPCgdhZGRyZXNzGAEgASgJEhAKCGxhbXBvcnRzGAIgASgEEg0KBW93bmVyGAMgASgJEhIKCmV4ZWN1dGFibGUYBCABKAgSDAoEZGF0YRgFIAEoCRISCgpyZW50X2Vwb2NoGAYgASgEQk5aTGdpdGh1Yi5jb20vQlJCdXNzeS9wcm90b2NoYWluL2xpYi9nby9wcm90b2NoYWluL3NvbGFuYS9hY2NvdW50L3YxO2FjY291bnRfdjFiBnByb3RvMw',
  );

/**
 *
 * Account is a solana account.
 *
 * @generated from message protochain.solana.account.v1.Account
 */
export type Account = Message<'protochain.solana.account.v1.Account'> & {
  /**
   * Base58-encoded account address
   *
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * Account balance in lamports (1 SOL = 1 billion lamports)
   *
   * @generated from field: uint64 lamports = 2;
   */
  lamports: bigint;

  /**
   * Base58-encoded owner program address
   *
   * @generated from field: string owner = 3;
   */
  owner: string;

  /**
   * Whether this account contains an executable program
   *
   * @generated from field: bool executable = 4;
   */
  executable: boolean;

  /**
   * Account data as JSON string
   *
   * @generated from field: string data = 5;
   */
  data: string;

  /**
   * Epoch at which this account will next owe rent
   *
   * @generated from field: uint64 rent_epoch = 6;
   */
  rentEpoch: bigint;
};

/**
 * Describes the message protochain.solana.account.v1.Account.
 * Use `create(AccountSchema)` to create a new message.
 */
export const AccountSchema: GenMessage<Account> =
  /*@__PURE__*/
  messageDesc(file_protochain_solana_account_v1_account, 0);
