// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/rpc_client/v1/service.proto

package rpc_client_v1

import (
	v1 "github.com/meshtrade/protochain/lib/go/protochain/solana/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMinimumBalanceForRentExemptionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DataLength      uint64                 `protobuf:"varint,1,opt,name=data_length,json=dataLength,proto3" json:"data_length,omitempty"`
	CommitmentLevel v1.CommitmentLevel     `protobuf:"varint,2,opt,name=commitment_level,json=commitmentLevel,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"commitment_level,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetMinimumBalanceForRentExemptionRequest) Reset() {
	*x = GetMinimumBalanceForRentExemptionRequest{}
	mi := &file_protochain_solana_rpc_client_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinimumBalanceForRentExemptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinimumBalanceForRentExemptionRequest) ProtoMessage() {}

func (x *GetMinimumBalanceForRentExemptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_rpc_client_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinimumBalanceForRentExemptionRequest.ProtoReflect.Descriptor instead.
func (*GetMinimumBalanceForRentExemptionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_rpc_client_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMinimumBalanceForRentExemptionRequest) GetDataLength() uint64 {
	if x != nil {
		return x.DataLength
	}
	return 0
}

func (x *GetMinimumBalanceForRentExemptionRequest) GetCommitmentLevel() v1.CommitmentLevel {
	if x != nil {
		return x.CommitmentLevel
	}
	return v1.CommitmentLevel(0)
}

type GetMinimumBalanceForRentExemptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       uint64                 `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMinimumBalanceForRentExemptionResponse) Reset() {
	*x = GetMinimumBalanceForRentExemptionResponse{}
	mi := &file_protochain_solana_rpc_client_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMinimumBalanceForRentExemptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMinimumBalanceForRentExemptionResponse) ProtoMessage() {}

func (x *GetMinimumBalanceForRentExemptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_rpc_client_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMinimumBalanceForRentExemptionResponse.ProtoReflect.Descriptor instead.
func (*GetMinimumBalanceForRentExemptionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_rpc_client_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMinimumBalanceForRentExemptionResponse) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

var File_protochain_solana_rpc_client_v1_service_proto protoreflect.FileDescriptor

const file_protochain_solana_rpc_client_v1_service_proto_rawDesc = "" +
	"\n" +
	"-protochain/solana/rpc_client/v1/service.proto\x12\x1fprotochain.solana.rpc_client.v1\x1a0protochain/solana/type/v1/commitment_level.proto\"\xa2\x01\n" +
	"(GetMinimumBalanceForRentExemptionRequest\x12\x1f\n" +
	"\vdata_length\x18\x01 \x01(\x04R\n" +
	"dataLength\x12U\n" +
	"\x10commitment_level\x18\x02 \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x0fcommitmentLevel\"E\n" +
	")GetMinimumBalanceForRentExemptionResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\x04R\abalance2\xc6\x01\n" +
	"\aService\x12\xba\x01\n" +
	"!GetMinimumBalanceForRentExemption\x12I.protochain.solana.rpc_client.v1.GetMinimumBalanceForRentExemptionRequest\x1aJ.protochain.solana.rpc_client.v1.GetMinimumBalanceForRentExemptionResponseBVZTgithub.com/meshtrade/protochain/lib/go/protochain/solana/rpc_client/v1;rpc_client_v1b\x06proto3"

var (
	file_protochain_solana_rpc_client_v1_service_proto_rawDescOnce sync.Once
	file_protochain_solana_rpc_client_v1_service_proto_rawDescData []byte
)

func file_protochain_solana_rpc_client_v1_service_proto_rawDescGZIP() []byte {
	file_protochain_solana_rpc_client_v1_service_proto_rawDescOnce.Do(func() {
		file_protochain_solana_rpc_client_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_rpc_client_v1_service_proto_rawDesc), len(file_protochain_solana_rpc_client_v1_service_proto_rawDesc)))
	})
	return file_protochain_solana_rpc_client_v1_service_proto_rawDescData
}

var file_protochain_solana_rpc_client_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protochain_solana_rpc_client_v1_service_proto_goTypes = []any{
	(*GetMinimumBalanceForRentExemptionRequest)(nil),  // 0: protochain.solana.rpc_client.v1.GetMinimumBalanceForRentExemptionRequest
	(*GetMinimumBalanceForRentExemptionResponse)(nil), // 1: protochain.solana.rpc_client.v1.GetMinimumBalanceForRentExemptionResponse
	(v1.CommitmentLevel)(0),                           // 2: protochain.solana.type.v1.CommitmentLevel
}
var file_protochain_solana_rpc_client_v1_service_proto_depIdxs = []int32{
	2, // 0: protochain.solana.rpc_client.v1.GetMinimumBalanceForRentExemptionRequest.commitment_level:type_name -> protochain.solana.type.v1.CommitmentLevel
	0, // 1: protochain.solana.rpc_client.v1.Service.GetMinimumBalanceForRentExemption:input_type -> protochain.solana.rpc_client.v1.GetMinimumBalanceForRentExemptionRequest
	1, // 2: protochain.solana.rpc_client.v1.Service.GetMinimumBalanceForRentExemption:output_type -> protochain.solana.rpc_client.v1.GetMinimumBalanceForRentExemptionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protochain_solana_rpc_client_v1_service_proto_init() }
func file_protochain_solana_rpc_client_v1_service_proto_init() {
	if File_protochain_solana_rpc_client_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_rpc_client_v1_service_proto_rawDesc), len(file_protochain_solana_rpc_client_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protochain_solana_rpc_client_v1_service_proto_goTypes,
		DependencyIndexes: file_protochain_solana_rpc_client_v1_service_proto_depIdxs,
		MessageInfos:      file_protochain_solana_rpc_client_v1_service_proto_msgTypes,
	}.Build()
	File_protochain_solana_rpc_client_v1_service_proto = out.File
	file_protochain_solana_rpc_client_v1_service_proto_goTypes = nil
	file_protochain_solana_rpc_client_v1_service_proto_depIdxs = nil
}
