// Code generated by protoc-gen-passivgo. DO NOT EDIT.
// source: protochain/solana/rpc_client/v1/service.proto
package rpc_client_v1

import (
	context "context"
)

type ServiceInterface interface {
	GetMinimumBalanceForRentExemption(ctx context.Context, request *GetMinimumBalanceForRentExemptionRequest) (*GetMinimumBalanceForRentExemptionResponse, error)
}

const ServiceServiceProviderName = "protochain-solana-rpc_client-v1-Service"
