// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/transaction/v1/error.proto

package transaction_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Comprehensive error codes for transaction submission failures
//
// Error classification is based on the "re-signing test" principle:
// - If fixing the error requires creating a new transaction with new signatures, it's PERMANENT
// - If the same signed transaction could work later, it's TEMPORARY
// - If we cannot determine whether the transaction was sent, it's INDETERMINATE
type TransactionErrorCode int32

const (
	TransactionErrorCode_TRANSACTION_ERROR_CODE_UNSPECIFIED TransactionErrorCode = 0
	// Transaction structure or format errors
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INVALID_TRANSACTION           TransactionErrorCode = 1  // Malformed transaction structure
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INVALID_SIGNATURE             TransactionErrorCode = 2  // Missing or invalid signatures
	TransactionErrorCode_TRANSACTION_ERROR_CODE_SIGNATURE_VERIFICATION_FAILED TransactionErrorCode = 3  // Signature verification failed
	TransactionErrorCode_TRANSACTION_ERROR_CODE_TRANSACTION_TOO_LARGE         TransactionErrorCode = 10 // Transaction exceeds size limits
	// Transaction Error
	TransactionErrorCode_TRANSACTION_ERROR_CODE_ALREADY_PROCESSED TransactionErrorCode = 48 // Transaction already processed
	// Account and validation errors
	TransactionErrorCode_TRANSACTION_ERROR_CODE_ACCOUNT_NOT_FOUND        TransactionErrorCode = 4  // Required account doesn't exist
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INVALID_ACCOUNT          TransactionErrorCode = 5  // Account in invalid state
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INVALID_BLOCKHASH_FORMAT TransactionErrorCode = 9  // Blockhash format is invalid
	TransactionErrorCode_TRANSACTION_ERROR_CODE_BLOCKHASH_NOT_FOUND      TransactionErrorCode = 11 // Expired blockhash - requires re-signing
	// Program execution errors
	TransactionErrorCode_TRANSACTION_ERROR_CODE_PROGRAM_ERROR                  TransactionErrorCode = 6  // Program execution failed
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INSTRUCTION_ERROR              TransactionErrorCode = 7  // Instruction execution failed
	TransactionErrorCode_TRANSACTION_ERROR_CODE_PRECOMPILE_VERIFICATION_FAILED TransactionErrorCode = 8  // Precompile verification failed
	TransactionErrorCode_TRANSACTION_ERROR_CODE_INSUFFICIENT_FUNDS             TransactionErrorCode = 20 // Add funds, same transaction works
	TransactionErrorCode_TRANSACTION_ERROR_CODE_ACCOUNT_IN_USE                 TransactionErrorCode = 21 // Account locked, wait for unlock
	TransactionErrorCode_TRANSACTION_ERROR_CODE_WOULD_EXCEED_BLOCK_LIMIT       TransactionErrorCode = 22 // Block capacity limit, try next block
	TransactionErrorCode_TRANSACTION_ERROR_CODE_TRANSIENT_SIMULATION_FAILURE   TransactionErrorCode = 23 // Temporary simulation issues
	TransactionErrorCode_TRANSACTION_ERROR_CODE_NETWORK_ERROR                  TransactionErrorCode = 40 // Could fail before/during/after send
	TransactionErrorCode_TRANSACTION_ERROR_CODE_TIMEOUT                        TransactionErrorCode = 41 // DANGEROUS - might have been sent
	TransactionErrorCode_TRANSACTION_ERROR_CODE_NODE_UNHEALTHY                 TransactionErrorCode = 42 // Node might have received it first
	TransactionErrorCode_TRANSACTION_ERROR_CODE_RATE_LIMITED                   TransactionErrorCode = 43 // Depends on where rate limiting occurs
	TransactionErrorCode_TRANSACTION_ERROR_CODE_RPC_ERROR                      TransactionErrorCode = 44 // Generic RPC failures
	TransactionErrorCode_TRANSACTION_ERROR_CODE_CONNECTION_FAILED              TransactionErrorCode = 45 // Connection establishment failed
	TransactionErrorCode_TRANSACTION_ERROR_CODE_REQUEST_FAILED                 TransactionErrorCode = 46 // HTTP/transport request failed
	TransactionErrorCode_TRANSACTION_ERROR_CODE_UNKNOWN                        TransactionErrorCode = 47 // Any unclassified error
)

// Enum value maps for TransactionErrorCode.
var (
	TransactionErrorCode_name = map[int32]string{
		0:  "TRANSACTION_ERROR_CODE_UNSPECIFIED",
		1:  "TRANSACTION_ERROR_CODE_INVALID_TRANSACTION",
		2:  "TRANSACTION_ERROR_CODE_INVALID_SIGNATURE",
		3:  "TRANSACTION_ERROR_CODE_SIGNATURE_VERIFICATION_FAILED",
		10: "TRANSACTION_ERROR_CODE_TRANSACTION_TOO_LARGE",
		48: "TRANSACTION_ERROR_CODE_ALREADY_PROCESSED",
		4:  "TRANSACTION_ERROR_CODE_ACCOUNT_NOT_FOUND",
		5:  "TRANSACTION_ERROR_CODE_INVALID_ACCOUNT",
		9:  "TRANSACTION_ERROR_CODE_INVALID_BLOCKHASH_FORMAT",
		11: "TRANSACTION_ERROR_CODE_BLOCKHASH_NOT_FOUND",
		6:  "TRANSACTION_ERROR_CODE_PROGRAM_ERROR",
		7:  "TRANSACTION_ERROR_CODE_INSTRUCTION_ERROR",
		8:  "TRANSACTION_ERROR_CODE_PRECOMPILE_VERIFICATION_FAILED",
		20: "TRANSACTION_ERROR_CODE_INSUFFICIENT_FUNDS",
		21: "TRANSACTION_ERROR_CODE_ACCOUNT_IN_USE",
		22: "TRANSACTION_ERROR_CODE_WOULD_EXCEED_BLOCK_LIMIT",
		23: "TRANSACTION_ERROR_CODE_TRANSIENT_SIMULATION_FAILURE",
		40: "TRANSACTION_ERROR_CODE_NETWORK_ERROR",
		41: "TRANSACTION_ERROR_CODE_TIMEOUT",
		42: "TRANSACTION_ERROR_CODE_NODE_UNHEALTHY",
		43: "TRANSACTION_ERROR_CODE_RATE_LIMITED",
		44: "TRANSACTION_ERROR_CODE_RPC_ERROR",
		45: "TRANSACTION_ERROR_CODE_CONNECTION_FAILED",
		46: "TRANSACTION_ERROR_CODE_REQUEST_FAILED",
		47: "TRANSACTION_ERROR_CODE_UNKNOWN",
	}
	TransactionErrorCode_value = map[string]int32{
		"TRANSACTION_ERROR_CODE_UNSPECIFIED":                    0,
		"TRANSACTION_ERROR_CODE_INVALID_TRANSACTION":            1,
		"TRANSACTION_ERROR_CODE_INVALID_SIGNATURE":              2,
		"TRANSACTION_ERROR_CODE_SIGNATURE_VERIFICATION_FAILED":  3,
		"TRANSACTION_ERROR_CODE_TRANSACTION_TOO_LARGE":          10,
		"TRANSACTION_ERROR_CODE_ALREADY_PROCESSED":              48,
		"TRANSACTION_ERROR_CODE_ACCOUNT_NOT_FOUND":              4,
		"TRANSACTION_ERROR_CODE_INVALID_ACCOUNT":                5,
		"TRANSACTION_ERROR_CODE_INVALID_BLOCKHASH_FORMAT":       9,
		"TRANSACTION_ERROR_CODE_BLOCKHASH_NOT_FOUND":            11,
		"TRANSACTION_ERROR_CODE_PROGRAM_ERROR":                  6,
		"TRANSACTION_ERROR_CODE_INSTRUCTION_ERROR":              7,
		"TRANSACTION_ERROR_CODE_PRECOMPILE_VERIFICATION_FAILED": 8,
		"TRANSACTION_ERROR_CODE_INSUFFICIENT_FUNDS":             20,
		"TRANSACTION_ERROR_CODE_ACCOUNT_IN_USE":                 21,
		"TRANSACTION_ERROR_CODE_WOULD_EXCEED_BLOCK_LIMIT":       22,
		"TRANSACTION_ERROR_CODE_TRANSIENT_SIMULATION_FAILURE":   23,
		"TRANSACTION_ERROR_CODE_NETWORK_ERROR":                  40,
		"TRANSACTION_ERROR_CODE_TIMEOUT":                        41,
		"TRANSACTION_ERROR_CODE_NODE_UNHEALTHY":                 42,
		"TRANSACTION_ERROR_CODE_RATE_LIMITED":                   43,
		"TRANSACTION_ERROR_CODE_RPC_ERROR":                      44,
		"TRANSACTION_ERROR_CODE_CONNECTION_FAILED":              45,
		"TRANSACTION_ERROR_CODE_REQUEST_FAILED":                 46,
		"TRANSACTION_ERROR_CODE_UNKNOWN":                        47,
	}
)

func (x TransactionErrorCode) Enum() *TransactionErrorCode {
	p := new(TransactionErrorCode)
	*p = x
	return p
}

func (x TransactionErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_protochain_solana_transaction_v1_error_proto_enumTypes[0].Descriptor()
}

func (TransactionErrorCode) Type() protoreflect.EnumType {
	return &file_protochain_solana_transaction_v1_error_proto_enumTypes[0]
}

func (x TransactionErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionErrorCode.Descriptor instead.
func (TransactionErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_error_proto_rawDescGZIP(), []int{0}
}

// Transaction submission certainty levels
//
// This enum indicates our level of certainty about whether the transaction
// was actually sent to the Solana network. This is critical for preventing
// duplicate transactions and implementing proper retry logic.
type TransactionSubmissionCertainty int32

const (
	// We are certain about what happened to the transaction
	TransactionSubmissionCertainty_TRANSACTION_SUBMISSION_CERTAINTY_UNSPECIFIED   TransactionSubmissionCertainty = 0 // Default/unknown state
	TransactionSubmissionCertainty_TRANSACTION_SUBMISSION_CERTAINTY_NOT_SUBMITTED TransactionSubmissionCertainty = 1 // 100% certain transaction was NOT sent to network
	TransactionSubmissionCertainty_TRANSACTION_SUBMISSION_CERTAINTY_SUBMITTED     TransactionSubmissionCertainty = 2 // 100% certain transaction WAS sent to network
	// We are uncertain but can resolve the state through blockchain analysis
	TransactionSubmissionCertainty_TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN_RESOLVABLE TransactionSubmissionCertainty = 3 // Wait for blockhash expiry, then check blockchain
	TransactionSubmissionCertainty_TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN            TransactionSubmissionCertainty = 4 // Cannot determine and cannot easily resolve
)

// Enum value maps for TransactionSubmissionCertainty.
var (
	TransactionSubmissionCertainty_name = map[int32]string{
		0: "TRANSACTION_SUBMISSION_CERTAINTY_UNSPECIFIED",
		1: "TRANSACTION_SUBMISSION_CERTAINTY_NOT_SUBMITTED",
		2: "TRANSACTION_SUBMISSION_CERTAINTY_SUBMITTED",
		3: "TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN_RESOLVABLE",
		4: "TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN",
	}
	TransactionSubmissionCertainty_value = map[string]int32{
		"TRANSACTION_SUBMISSION_CERTAINTY_UNSPECIFIED":        0,
		"TRANSACTION_SUBMISSION_CERTAINTY_NOT_SUBMITTED":      1,
		"TRANSACTION_SUBMISSION_CERTAINTY_SUBMITTED":          2,
		"TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN_RESOLVABLE": 3,
		"TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN":            4,
	}
)

func (x TransactionSubmissionCertainty) Enum() *TransactionSubmissionCertainty {
	p := new(TransactionSubmissionCertainty)
	*p = x
	return p
}

func (x TransactionSubmissionCertainty) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionSubmissionCertainty) Descriptor() protoreflect.EnumDescriptor {
	return file_protochain_solana_transaction_v1_error_proto_enumTypes[1].Descriptor()
}

func (TransactionSubmissionCertainty) Type() protoreflect.EnumType {
	return &file_protochain_solana_transaction_v1_error_proto_enumTypes[1]
}

func (x TransactionSubmissionCertainty) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionSubmissionCertainty.Descriptor instead.
func (TransactionSubmissionCertainty) EnumDescriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_error_proto_rawDescGZIP(), []int{1}
}

// Structured error information for transaction submission failures
//
// This message provides comprehensive error details that enable callers to determine
// with 100% certainty the state of their transaction submission and whether retry
// is appropriate. The error classification follows the "re-signing test" principle:
// - PERMANENT failures require rebuilding and re-signing the transaction
// - TEMPORARY failures can be resolved with the same signed transaction
// - INDETERMINATE states can be resolved by waiting for blockhash expiration
type TransactionError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific error code for programmatic handling
	Code TransactionErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=protochain.solana.transaction.v1.TransactionErrorCode" json:"code,omitempty"`
	// Human-readable error message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// JSON-encoded additional error context and details
	Details string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	// Whether the same transaction might succeed if retried without modification
	Retryable bool `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// Certainty level about transaction submission status
	Certainty TransactionSubmissionCertainty `protobuf:"varint,5,opt,name=certainty,proto3,enum=protochain.solana.transaction.v1.TransactionSubmissionCertainty" json:"certainty,omitempty"`
	// Original transaction blockhash for resolution timing
	Blockhash string `protobuf:"bytes,6,opt,name=blockhash,proto3" json:"blockhash,omitempty"`
	// Slot when blockhash expires (~150 blocks after creation)
	BlockhashExpirySlot uint64 `protobuf:"varint,7,opt,name=blockhash_expiry_slot,json=blockhashExpirySlot,proto3" json:"blockhash_expiry_slot,omitempty"`
	// Signature of the transaction (set if the transaction was actually submitted)
	Signature     string `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionError) Reset() {
	*x = TransactionError{}
	mi := &file_protochain_solana_transaction_v1_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionError) ProtoMessage() {}

func (x *TransactionError) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionError.ProtoReflect.Descriptor instead.
func (*TransactionError) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_error_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionError) GetCode() TransactionErrorCode {
	if x != nil {
		return x.Code
	}
	return TransactionErrorCode_TRANSACTION_ERROR_CODE_UNSPECIFIED
}

func (x *TransactionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TransactionError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *TransactionError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *TransactionError) GetCertainty() TransactionSubmissionCertainty {
	if x != nil {
		return x.Certainty
	}
	return TransactionSubmissionCertainty_TRANSACTION_SUBMISSION_CERTAINTY_UNSPECIFIED
}

func (x *TransactionError) GetBlockhash() string {
	if x != nil {
		return x.Blockhash
	}
	return ""
}

func (x *TransactionError) GetBlockhashExpirySlot() uint64 {
	if x != nil {
		return x.BlockhashExpirySlot
	}
	return 0
}

func (x *TransactionError) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_protochain_solana_transaction_v1_error_proto protoreflect.FileDescriptor

const file_protochain_solana_transaction_v1_error_proto_rawDesc = "" +
	"\n" +
	",protochain/solana/transaction/v1/error.proto\x12 protochain.solana.transaction.v1\"\x80\x03\n" +
	"\x10TransactionError\x12J\n" +
	"\x04code\x18\x01 \x01(\x0e26.protochain.solana.transaction.v1.TransactionErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\adetails\x18\x03 \x01(\tR\adetails\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\x12^\n" +
	"\tcertainty\x18\x05 \x01(\x0e2@.protochain.solana.transaction.v1.TransactionSubmissionCertaintyR\tcertainty\x12\x1c\n" +
	"\tblockhash\x18\x06 \x01(\tR\tblockhash\x122\n" +
	"\x15blockhash_expiry_slot\x18\a \x01(\x04R\x13blockhashExpirySlot\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature*\x95\t\n" +
	"\x14TransactionErrorCode\x12&\n" +
	"\"TRANSACTION_ERROR_CODE_UNSPECIFIED\x10\x00\x12.\n" +
	"*TRANSACTION_ERROR_CODE_INVALID_TRANSACTION\x10\x01\x12,\n" +
	"(TRANSACTION_ERROR_CODE_INVALID_SIGNATURE\x10\x02\x128\n" +
	"4TRANSACTION_ERROR_CODE_SIGNATURE_VERIFICATION_FAILED\x10\x03\x120\n" +
	",TRANSACTION_ERROR_CODE_TRANSACTION_TOO_LARGE\x10\n" +
	"\x12,\n" +
	"(TRANSACTION_ERROR_CODE_ALREADY_PROCESSED\x100\x12,\n" +
	"(TRANSACTION_ERROR_CODE_ACCOUNT_NOT_FOUND\x10\x04\x12*\n" +
	"&TRANSACTION_ERROR_CODE_INVALID_ACCOUNT\x10\x05\x123\n" +
	"/TRANSACTION_ERROR_CODE_INVALID_BLOCKHASH_FORMAT\x10\t\x12.\n" +
	"*TRANSACTION_ERROR_CODE_BLOCKHASH_NOT_FOUND\x10\v\x12(\n" +
	"$TRANSACTION_ERROR_CODE_PROGRAM_ERROR\x10\x06\x12,\n" +
	"(TRANSACTION_ERROR_CODE_INSTRUCTION_ERROR\x10\a\x129\n" +
	"5TRANSACTION_ERROR_CODE_PRECOMPILE_VERIFICATION_FAILED\x10\b\x12-\n" +
	")TRANSACTION_ERROR_CODE_INSUFFICIENT_FUNDS\x10\x14\x12)\n" +
	"%TRANSACTION_ERROR_CODE_ACCOUNT_IN_USE\x10\x15\x123\n" +
	"/TRANSACTION_ERROR_CODE_WOULD_EXCEED_BLOCK_LIMIT\x10\x16\x127\n" +
	"3TRANSACTION_ERROR_CODE_TRANSIENT_SIMULATION_FAILURE\x10\x17\x12(\n" +
	"$TRANSACTION_ERROR_CODE_NETWORK_ERROR\x10(\x12\"\n" +
	"\x1eTRANSACTION_ERROR_CODE_TIMEOUT\x10)\x12)\n" +
	"%TRANSACTION_ERROR_CODE_NODE_UNHEALTHY\x10*\x12'\n" +
	"#TRANSACTION_ERROR_CODE_RATE_LIMITED\x10+\x12$\n" +
	" TRANSACTION_ERROR_CODE_RPC_ERROR\x10,\x12,\n" +
	"(TRANSACTION_ERROR_CODE_CONNECTION_FAILED\x10-\x12)\n" +
	"%TRANSACTION_ERROR_CODE_REQUEST_FAILED\x10.\x12\"\n" +
	"\x1eTRANSACTION_ERROR_CODE_UNKNOWN\x10/*\x9d\x02\n" +
	"\x1eTransactionSubmissionCertainty\x120\n" +
	",TRANSACTION_SUBMISSION_CERTAINTY_UNSPECIFIED\x10\x00\x122\n" +
	".TRANSACTION_SUBMISSION_CERTAINTY_NOT_SUBMITTED\x10\x01\x12.\n" +
	"*TRANSACTION_SUBMISSION_CERTAINTY_SUBMITTED\x10\x02\x127\n" +
	"3TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN_RESOLVABLE\x10\x03\x12,\n" +
	"(TRANSACTION_SUBMISSION_CERTAINTY_UNKNOWN\x10\x04BXZVgithub.com/meshtrade/protochain/lib/go/protochain/solana/transaction/v1;transaction_v1b\x06proto3"

var (
	file_protochain_solana_transaction_v1_error_proto_rawDescOnce sync.Once
	file_protochain_solana_transaction_v1_error_proto_rawDescData []byte
)

func file_protochain_solana_transaction_v1_error_proto_rawDescGZIP() []byte {
	file_protochain_solana_transaction_v1_error_proto_rawDescOnce.Do(func() {
		file_protochain_solana_transaction_v1_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_transaction_v1_error_proto_rawDesc), len(file_protochain_solana_transaction_v1_error_proto_rawDesc)))
	})
	return file_protochain_solana_transaction_v1_error_proto_rawDescData
}

var file_protochain_solana_transaction_v1_error_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protochain_solana_transaction_v1_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protochain_solana_transaction_v1_error_proto_goTypes = []any{
	(TransactionErrorCode)(0),           // 0: protochain.solana.transaction.v1.TransactionErrorCode
	(TransactionSubmissionCertainty)(0), // 1: protochain.solana.transaction.v1.TransactionSubmissionCertainty
	(*TransactionError)(nil),            // 2: protochain.solana.transaction.v1.TransactionError
}
var file_protochain_solana_transaction_v1_error_proto_depIdxs = []int32{
	0, // 0: protochain.solana.transaction.v1.TransactionError.code:type_name -> protochain.solana.transaction.v1.TransactionErrorCode
	1, // 1: protochain.solana.transaction.v1.TransactionError.certainty:type_name -> protochain.solana.transaction.v1.TransactionSubmissionCertainty
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protochain_solana_transaction_v1_error_proto_init() }
func file_protochain_solana_transaction_v1_error_proto_init() {
	if File_protochain_solana_transaction_v1_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_transaction_v1_error_proto_rawDesc), len(file_protochain_solana_transaction_v1_error_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protochain_solana_transaction_v1_error_proto_goTypes,
		DependencyIndexes: file_protochain_solana_transaction_v1_error_proto_depIdxs,
		EnumInfos:         file_protochain_solana_transaction_v1_error_proto_enumTypes,
		MessageInfos:      file_protochain_solana_transaction_v1_error_proto_msgTypes,
	}.Build()
	File_protochain_solana_transaction_v1_error_proto = out.File
	file_protochain_solana_transaction_v1_error_proto_goTypes = nil
	file_protochain_solana_transaction_v1_error_proto_depIdxs = nil
}
