// Code generated by protoc-gen-passivgo. DO NOT EDIT.
// source: protochain/solana/transaction/v1/service.proto
package transaction_v1

import (
	context "context"
	common "github.com/meshtrade/protochain/lib/go/common"
	grpc "google.golang.org/grpc"
	io "io"
)

// ServiceServiceClientInterface is a gRPC service for the Service service.
// It combines the service interface with resource management capabilities using
// the common BaseGRPCClient for consistent authentication, timeouts, and tracing.
//
// Basic service usage with default configuration:
//
//	service, err := NewServiceService()
//	if err != nil {
//		log.Fatal(err)
//	}
//	defer service.Close() // ensures proper cleanup of underlying connection
//
// With default configuration API credentials are searched for using the standard discovery hierarchy:
//
// 1. PROTOCHAIN_API_CREDENTIALS environment variable
//
// 2. Default credential file location:
//
//   - Linux:   $XDG_CONFIG_HOME/protochain/credentials.json or fallback to $HOME/.config/protochain/credentials.json
//   - macOS:   $HOME/Library/Application Support/protochain/credentials.json
//   - Windows: C:\\Users\\<user>\\AppData\\Roaming\\protochain\\credentials.json
//
// The service may also be configured with custom options:
//
//	service, err := NewServiceService(
//		api.WithURL("api.example.com:443"),
//		api.WithAPIKey("your-api-key"),
//		api.WithTimeout(30 * time.Second),
//		api.WithTLS(true),
//	)
//	if err != nil {
//		log.Fatal(err)
//	}
//	defer service.Close() // ensures proper cleanup of underlying connection
type ServiceServiceClientInterface interface {
	ServiceInterface
	common.GRPCClient
}

// serviceService is the internal implementation of the ServiceServiceClientInterface interface.
// It embeds BaseGRPCClient to provide all common gRPC functionality including validation.
type serviceService struct {
	*common.BaseGRPCClient[ServiceClient]
}

// ensure serviceService implements the ServiceServiceClientInterface interface
var _ ServiceServiceClientInterface = &serviceService{}

// NewServiceService creates and initializes the Service service.
// The service uses the common BaseGRPCClient for all functionality including
// connection management, authentication, timeouts, and distributed tracing.
//
// With default configuration API credentials are searched for using the standard discovery hierarchy:
//
// 1. PROTOCHAIN_API_CREDENTIALS environment variable
//
// 2. Default credential file location:
//
//   - Linux:   $XDG_CONFIG_HOME/protochain/credentials.json or fallback to $HOME/.config/protochain/credentials.json
//   - macOS:   $HOME/Library/Application Support/protochain/credentials.json
//   - Windows: C:\\Users\\<user>\\AppData\\Roaming\\protochain\\credentials.json
//
// Examples:
//
//	// Create with default configuration
//	service, err := NewServiceService()
//	if err != nil {
//		log.Fatal(err)
//	}
//	defer service.Close()
//
//	// Create with custom configuration
//	service, err := NewServiceService(
//		api.WithURL("api.example.com:443"),
//		api.WithAPIKey("your-api-key"),
//		api.WithTLS(true),
//	)
//	if err != nil {
//		log.Fatal(err)
//	}
//	defer service.Close()
//
// Parameters:
//   - opts: Functional options to configure the client
//
// Returns:
//   - ServiceServiceClientInterface: Configured service instance
//   - error: Configuration or connection error
func NewServiceService(opts ...common.ServiceOption) (ServiceServiceClientInterface, error) {
	base, err := common.NewBaseGRPCClient(
		ServiceServiceProviderName,
		NewServiceClient,
		opts...,
	)
	if err != nil {
		return nil, err
	}

	return &serviceService{BaseGRPCClient: base}, nil
}

// CompileTransaction executes the CompileTransaction RPC method with automatic
// client-side validation, timeout handling, distributed tracing, and authentication.
func (s *serviceService) CompileTransaction(ctx context.Context, request *CompileTransactionRequest) (*CompileTransactionResponse, error) {
	return common.Execute(s.Executor(), ctx, "CompileTransaction", request, func(ctx context.Context) (*CompileTransactionResponse, error) {
		return s.GrpcClient().CompileTransaction(ctx, request)
	})
}

// EstimateTransaction executes the EstimateTransaction RPC method with automatic
// client-side validation, timeout handling, distributed tracing, and authentication.
func (s *serviceService) EstimateTransaction(ctx context.Context, request *EstimateTransactionRequest) (*EstimateTransactionResponse, error) {
	return common.Execute(s.Executor(), ctx, "EstimateTransaction", request, func(ctx context.Context) (*EstimateTransactionResponse, error) {
		return s.GrpcClient().EstimateTransaction(ctx, request)
	})
}

// SimulateTransaction executes the SimulateTransaction RPC method with automatic
// client-side validation, timeout handling, distributed tracing, and authentication.
func (s *serviceService) SimulateTransaction(ctx context.Context, request *SimulateTransactionRequest) (*SimulateTransactionResponse, error) {
	return common.Execute(s.Executor(), ctx, "SimulateTransaction", request, func(ctx context.Context) (*SimulateTransactionResponse, error) {
		return s.GrpcClient().SimulateTransaction(ctx, request)
	})
}

// SignTransaction executes the SignTransaction RPC method with automatic
// client-side validation, timeout handling, distributed tracing, and authentication.
func (s *serviceService) SignTransaction(ctx context.Context, request *SignTransactionRequest) (*SignTransactionResponse, error) {
	return common.Execute(s.Executor(), ctx, "SignTransaction", request, func(ctx context.Context) (*SignTransactionResponse, error) {
		return s.GrpcClient().SignTransaction(ctx, request)
	})
}

// SubmitTransaction executes the SubmitTransaction RPC method with automatic
// client-side validation, timeout handling, distributed tracing, and authentication.
func (s *serviceService) SubmitTransaction(ctx context.Context, request *SubmitTransactionRequest) (*SubmitTransactionResponse, error) {
	return common.Execute(s.Executor(), ctx, "SubmitTransaction", request, func(ctx context.Context) (*SubmitTransactionResponse, error) {
		return s.GrpcClient().SubmitTransaction(ctx, request)
	})
}

// GetTransaction executes the GetTransaction RPC method with automatic
// client-side validation, timeout handling, distributed tracing, and authentication.
func (s *serviceService) GetTransaction(ctx context.Context, request *GetTransactionRequest) (*GetTransactionResponse, error) {
	return common.Execute(s.Executor(), ctx, "GetTransaction", request, func(ctx context.Context) (*GetTransactionResponse, error) {
		return s.GrpcClient().GetTransaction(ctx, request)
	})
}

// MonitorTransaction executes the MonitorTransaction server streaming RPC method.
// For streaming methods, this delegates directly to the underlying gRPC client.
func (s *serviceService) MonitorTransaction(ctx context.Context, request *MonitorTransactionRequest, stream grpc.ServerStreamingServer[MonitorTransactionResponse]) error {
	// For streaming methods, delegate directly to the gRPC client stream
	clientStream, err := s.GrpcClient().MonitorTransaction(ctx, request)
	if err != nil {
		return err
	}
	// Forward all responses from client stream to server stream
	for {
		resp, err := clientStream.Recv()
		if err != nil {
			if err == io.EOF {
				return nil
			}
			return err
		}
		if err := stream.Send(resp); err != nil {
			return err
		}
	}
}
