// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: protochain/solana/transaction/v1/service.proto

package transaction_v1

import (
	v1 "github.com/meshtrade/protochain/lib/go/protochain/solana/type/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmissionResult int32

const (
	SubmissionResult_SUBMISSION_RESULT_UNSPECIFIED               SubmissionResult = 0
	SubmissionResult_SUBMISSION_RESULT_SUBMITTED                 SubmissionResult = 1 // Transaction successfully submitted to network
	SubmissionResult_SUBMISSION_RESULT_FAILED_VALIDATION         SubmissionResult = 2 // Transaction failed pre-submission validation
	SubmissionResult_SUBMISSION_RESULT_FAILED_NETWORK_ERROR      SubmissionResult = 3 // Network/RPC error prevented submission
	SubmissionResult_SUBMISSION_RESULT_FAILED_INSUFFICIENT_FUNDS SubmissionResult = 4 // Fee payer has insufficient balance
	SubmissionResult_SUBMISSION_RESULT_FAILED_INVALID_SIGNATURE  SubmissionResult = 5 // Transaction signature validation failed
	SubmissionResult_SUBMISSION_RESULT_INDETERMINATE             SubmissionResult = 6 // NEW: State unknown - use structured_error for resolution
)

// Enum value maps for SubmissionResult.
var (
	SubmissionResult_name = map[int32]string{
		0: "SUBMISSION_RESULT_UNSPECIFIED",
		1: "SUBMISSION_RESULT_SUBMITTED",
		2: "SUBMISSION_RESULT_FAILED_VALIDATION",
		3: "SUBMISSION_RESULT_FAILED_NETWORK_ERROR",
		4: "SUBMISSION_RESULT_FAILED_INSUFFICIENT_FUNDS",
		5: "SUBMISSION_RESULT_FAILED_INVALID_SIGNATURE",
		6: "SUBMISSION_RESULT_INDETERMINATE",
	}
	SubmissionResult_value = map[string]int32{
		"SUBMISSION_RESULT_UNSPECIFIED":               0,
		"SUBMISSION_RESULT_SUBMITTED":                 1,
		"SUBMISSION_RESULT_FAILED_VALIDATION":         2,
		"SUBMISSION_RESULT_FAILED_NETWORK_ERROR":      3,
		"SUBMISSION_RESULT_FAILED_INSUFFICIENT_FUNDS": 4,
		"SUBMISSION_RESULT_FAILED_INVALID_SIGNATURE":  5,
		"SUBMISSION_RESULT_INDETERMINATE":             6,
	}
)

func (x SubmissionResult) Enum() *SubmissionResult {
	p := new(SubmissionResult)
	*p = x
	return p
}

func (x SubmissionResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubmissionResult) Descriptor() protoreflect.EnumDescriptor {
	return file_protochain_solana_transaction_v1_service_proto_enumTypes[0].Descriptor()
}

func (SubmissionResult) Type() protoreflect.EnumType {
	return &file_protochain_solana_transaction_v1_service_proto_enumTypes[0]
}

func (x SubmissionResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubmissionResult.Descriptor instead.
func (SubmissionResult) EnumDescriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{0}
}

type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_RECEIVED    TransactionStatus = 1 // Transaction received by validator
	TransactionStatus_TRANSACTION_STATUS_PROCESSED   TransactionStatus = 2 // Transaction processed (commitment: processed)
	TransactionStatus_TRANSACTION_STATUS_CONFIRMED   TransactionStatus = 3 // Transaction confirmed (commitment: confirmed)
	TransactionStatus_TRANSACTION_STATUS_FINALIZED   TransactionStatus = 4 // Transaction finalized (commitment: finalized)
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 5 // Transaction failed during execution
	TransactionStatus_TRANSACTION_STATUS_DROPPED     TransactionStatus = 6 // Transaction dropped from network
	TransactionStatus_TRANSACTION_STATUS_TIMEOUT     TransactionStatus = 7 // Monitoring timeout reached
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_RECEIVED",
		2: "TRANSACTION_STATUS_PROCESSED",
		3: "TRANSACTION_STATUS_CONFIRMED",
		4: "TRANSACTION_STATUS_FINALIZED",
		5: "TRANSACTION_STATUS_FAILED",
		6: "TRANSACTION_STATUS_DROPPED",
		7: "TRANSACTION_STATUS_TIMEOUT",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_RECEIVED":    1,
		"TRANSACTION_STATUS_PROCESSED":   2,
		"TRANSACTION_STATUS_CONFIRMED":   3,
		"TRANSACTION_STATUS_FINALIZED":   4,
		"TRANSACTION_STATUS_FAILED":      5,
		"TRANSACTION_STATUS_DROPPED":     6,
		"TRANSACTION_STATUS_TIMEOUT":     7,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protochain_solana_transaction_v1_service_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_protochain_solana_transaction_v1_service_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{1}
}

// Request/Response messages
type CompileTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transaction     *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`                                // Must be in DRAFT state
	FeePayer        string                 `protobuf:"bytes,2,opt,name=fee_payer,json=feePayer,proto3" json:"fee_payer,omitempty"`                      // Who pays transaction fees
	RecentBlockhash string                 `protobuf:"bytes,3,opt,name=recent_blockhash,json=recentBlockhash,proto3" json:"recent_blockhash,omitempty"` // Optional - will fetch if empty
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CompileTransactionRequest) Reset() {
	*x = CompileTransactionRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileTransactionRequest) ProtoMessage() {}

func (x *CompileTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileTransactionRequest.ProtoReflect.Descriptor instead.
func (*CompileTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CompileTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CompileTransactionRequest) GetFeePayer() string {
	if x != nil {
		return x.FeePayer
	}
	return ""
}

func (x *CompileTransactionRequest) GetRecentBlockhash() string {
	if x != nil {
		return x.RecentBlockhash
	}
	return ""
}

type CompileTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"` // Now in COMPILED state
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileTransactionResponse) Reset() {
	*x = CompileTransactionResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileTransactionResponse) ProtoMessage() {}

func (x *CompileTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileTransactionResponse.ProtoReflect.Descriptor instead.
func (*CompileTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CompileTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type EstimateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transaction     *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`                                                                                // Must be in COMPILED state
	CommitmentLevel v1.CommitmentLevel     `protobuf:"varint,2,opt,name=commitment_level,json=commitmentLevel,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"commitment_level,omitempty"` // Commitment level for fee estimation
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EstimateTransactionRequest) Reset() {
	*x = EstimateTransactionRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateTransactionRequest) ProtoMessage() {}

func (x *EstimateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateTransactionRequest.ProtoReflect.Descriptor instead.
func (*EstimateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *EstimateTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *EstimateTransactionRequest) GetCommitmentLevel() v1.CommitmentLevel {
	if x != nil {
		return x.CommitmentLevel
	}
	return v1.CommitmentLevel(0)
}

type EstimateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComputeUnits  uint64                 `protobuf:"varint,1,opt,name=compute_units,json=computeUnits,proto3" json:"compute_units,omitempty"` // Estimated compute units required
	FeeLamports   uint64                 `protobuf:"varint,2,opt,name=fee_lamports,json=feeLamports,proto3" json:"fee_lamports,omitempty"`    // Estimated total transaction fee
	PriorityFee   uint64                 `protobuf:"varint,3,opt,name=priority_fee,json=priorityFee,proto3" json:"priority_fee,omitempty"`    // Current network priority fee estimate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimateTransactionResponse) Reset() {
	*x = EstimateTransactionResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimateTransactionResponse) ProtoMessage() {}

func (x *EstimateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimateTransactionResponse.ProtoReflect.Descriptor instead.
func (*EstimateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *EstimateTransactionResponse) GetComputeUnits() uint64 {
	if x != nil {
		return x.ComputeUnits
	}
	return 0
}

func (x *EstimateTransactionResponse) GetFeeLamports() uint64 {
	if x != nil {
		return x.FeeLamports
	}
	return 0
}

func (x *EstimateTransactionResponse) GetPriorityFee() uint64 {
	if x != nil {
		return x.PriorityFee
	}
	return 0
}

type SimulateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transaction     *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`                                                                                // Must be compiled
	CommitmentLevel v1.CommitmentLevel     `protobuf:"varint,2,opt,name=commitment_level,json=commitmentLevel,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"commitment_level,omitempty"` // Commitment level for simulation
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimulateTransactionRequest) Reset() {
	*x = SimulateTransactionRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionRequest) ProtoMessage() {}

func (x *SimulateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionRequest.ProtoReflect.Descriptor instead.
func (*SimulateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *SimulateTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SimulateTransactionRequest) GetCommitmentLevel() v1.CommitmentLevel {
	if x != nil {
		return x.CommitmentLevel
	}
	return v1.CommitmentLevel(0)
}

type SimulateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Logs          []string               `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateTransactionResponse) Reset() {
	*x = SimulateTransactionResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateTransactionResponse) ProtoMessage() {}

func (x *SimulateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateTransactionResponse.ProtoReflect.Descriptor instead.
func (*SimulateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *SimulateTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SimulateTransactionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *SimulateTransactionResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

type SignTransactionRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Transaction *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	// Types that are valid to be assigned to SigningMethod:
	//
	//	*SignTransactionRequest_PrivateKeys
	//	*SignTransactionRequest_Seeds
	SigningMethod isSignTransactionRequest_SigningMethod `protobuf_oneof:"signing_method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionRequest) Reset() {
	*x = SignTransactionRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionRequest) ProtoMessage() {}

func (x *SignTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionRequest.ProtoReflect.Descriptor instead.
func (*SignTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *SignTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SignTransactionRequest) GetSigningMethod() isSignTransactionRequest_SigningMethod {
	if x != nil {
		return x.SigningMethod
	}
	return nil
}

func (x *SignTransactionRequest) GetPrivateKeys() *SignWithPrivateKeys {
	if x != nil {
		if x, ok := x.SigningMethod.(*SignTransactionRequest_PrivateKeys); ok {
			return x.PrivateKeys
		}
	}
	return nil
}

func (x *SignTransactionRequest) GetSeeds() *SignWithSeeds {
	if x != nil {
		if x, ok := x.SigningMethod.(*SignTransactionRequest_Seeds); ok {
			return x.Seeds
		}
	}
	return nil
}

type isSignTransactionRequest_SigningMethod interface {
	isSignTransactionRequest_SigningMethod()
}

type SignTransactionRequest_PrivateKeys struct {
	PrivateKeys *SignWithPrivateKeys `protobuf:"bytes,2,opt,name=private_keys,json=privateKeys,proto3,oneof"`
}

type SignTransactionRequest_Seeds struct {
	Seeds *SignWithSeeds `protobuf:"bytes,3,opt,name=seeds,proto3,oneof"`
}

func (*SignTransactionRequest_PrivateKeys) isSignTransactionRequest_SigningMethod() {}

func (*SignTransactionRequest_Seeds) isSignTransactionRequest_SigningMethod() {}

type SignTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignTransactionResponse) Reset() {
	*x = SignTransactionResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTransactionResponse) ProtoMessage() {}

func (x *SignTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTransactionResponse.ProtoReflect.Descriptor instead.
func (*SignTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *SignTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type SignWithPrivateKeys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKeys   []string               `protobuf:"bytes,1,rep,name=private_keys,json=privateKeys,proto3" json:"private_keys,omitempty"` // Base58 encoded private keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignWithPrivateKeys) Reset() {
	*x = SignWithPrivateKeys{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignWithPrivateKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignWithPrivateKeys) ProtoMessage() {}

func (x *SignWithPrivateKeys) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignWithPrivateKeys.ProtoReflect.Descriptor instead.
func (*SignWithPrivateKeys) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SignWithPrivateKeys) GetPrivateKeys() []string {
	if x != nil {
		return x.PrivateKeys
	}
	return nil
}

type SignWithSeeds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seeds         []*KeySeed             `protobuf:"bytes,1,rep,name=seeds,proto3" json:"seeds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignWithSeeds) Reset() {
	*x = SignWithSeeds{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignWithSeeds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignWithSeeds) ProtoMessage() {}

func (x *SignWithSeeds) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignWithSeeds.ProtoReflect.Descriptor instead.
func (*SignWithSeeds) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *SignWithSeeds) GetSeeds() []*KeySeed {
	if x != nil {
		return x.Seeds
	}
	return nil
}

type KeySeed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seed          string                 `protobuf:"bytes,1,opt,name=seed,proto3" json:"seed,omitempty"`
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeySeed) Reset() {
	*x = KeySeed{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeySeed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeySeed) ProtoMessage() {}

func (x *KeySeed) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeySeed.ProtoReflect.Descriptor instead.
func (*KeySeed) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *KeySeed) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *KeySeed) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type CheckIfTransactionIsExpiredRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transaction     *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`                                                                                // Transaction to check
	CommitmentLevel v1.CommitmentLevel     `protobuf:"varint,2,opt,name=commitment_level,json=commitmentLevel,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"commitment_level,omitempty"` // Commitment level for transaction submission
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CheckIfTransactionIsExpiredRequest) Reset() {
	*x = CheckIfTransactionIsExpiredRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfTransactionIsExpiredRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfTransactionIsExpiredRequest) ProtoMessage() {}

func (x *CheckIfTransactionIsExpiredRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfTransactionIsExpiredRequest.ProtoReflect.Descriptor instead.
func (*CheckIfTransactionIsExpiredRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *CheckIfTransactionIsExpiredRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *CheckIfTransactionIsExpiredRequest) GetCommitmentLevel() v1.CommitmentLevel {
	if x != nil {
		return x.CommitmentLevel
	}
	return v1.CommitmentLevel(0)
}

type CheckIfTransactionIsExpiredResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsExpired     bool                   `protobuf:"varint,1,opt,name=is_expired,json=isExpired,proto3" json:"is_expired,omitempty"` // True if transaction is expired
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIfTransactionIsExpiredResponse) Reset() {
	*x = CheckIfTransactionIsExpiredResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIfTransactionIsExpiredResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIfTransactionIsExpiredResponse) ProtoMessage() {}

func (x *CheckIfTransactionIsExpiredResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIfTransactionIsExpiredResponse.ProtoReflect.Descriptor instead.
func (*CheckIfTransactionIsExpiredResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *CheckIfTransactionIsExpiredResponse) GetIsExpired() bool {
	if x != nil {
		return x.IsExpired
	}
	return false
}

// Request to asynchronously submit a transaction to the Solana network
// The method returns immediately after submission without waiting for confirmation
type SubmitTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Transaction     *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`                                                                                // Must be fully signed
	CommitmentLevel v1.CommitmentLevel     `protobuf:"varint,2,opt,name=commitment_level,json=commitmentLevel,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"commitment_level,omitempty"` // Commitment level for transaction submission
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitTransactionRequest) Reset() {
	*x = SubmitTransactionRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionRequest) ProtoMessage() {}

func (x *SubmitTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionRequest.ProtoReflect.Descriptor instead.
func (*SubmitTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitTransactionRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SubmitTransactionRequest) GetCommitmentLevel() v1.CommitmentLevel {
	if x != nil {
		return x.CommitmentLevel
	}
	return v1.CommitmentLevel(0)
}

// Response containing the submission result
// NOTE: This is an asynchronous submission - successful result means the transaction
// was successfully sent to the network, NOT that it was confirmed or executed
// Use MonitorTransaction to poll for confirmation and execution status
type SubmitTransactionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Signature        string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`                                                                                               // Transaction signature
	SubmissionResult SubmissionResult       `protobuf:"varint,2,opt,name=submission_result,json=submissionResult,proto3,enum=protochain.solana.transaction.v1.SubmissionResult" json:"submission_result,omitempty"` // Submission outcome (sent vs failed to send)
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                                                     // Error details if submission failed (kept for backward compatibility)
	StructuredError  *TransactionError      `protobuf:"bytes,4,opt,name=structured_error,json=structuredError,proto3" json:"structured_error,omitempty"`                                                            // NEW: Structured error details with certainty indicators
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitTransactionResponse) Reset() {
	*x = SubmitTransactionResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitTransactionResponse) ProtoMessage() {}

func (x *SubmitTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitTransactionResponse.ProtoReflect.Descriptor instead.
func (*SubmitTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitTransactionResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SubmitTransactionResponse) GetSubmissionResult() SubmissionResult {
	if x != nil {
		return x.SubmissionResult
	}
	return SubmissionResult_SUBMISSION_RESULT_UNSPECIFIED
}

func (x *SubmitTransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SubmitTransactionResponse) GetStructuredError() *TransactionError {
	if x != nil {
		return x.StructuredError
	}
	return nil
}

type GetTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Signature       string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	CommitmentLevel v1.CommitmentLevel     `protobuf:"varint,2,opt,name=commitment_level,json=commitmentLevel,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"commitment_level,omitempty"` // Commitment level for transaction retrieval
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetTransactionRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *GetTransactionRequest) GetCommitmentLevel() v1.CommitmentLevel {
	if x != nil {
		return x.CommitmentLevel
	}
	return v1.CommitmentLevel(0)
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Transaction monitoring messages
type MonitorTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Signature       string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`                                                                                    // Transaction signature to monitor
	CommitmentLevel v1.CommitmentLevel     `protobuf:"varint,2,opt,name=commitment_level,json=commitmentLevel,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"commitment_level,omitempty"` // Target commitment level
	IncludeLogs     bool                   `protobuf:"varint,3,opt,name=include_logs,json=includeLogs,proto3" json:"include_logs,omitempty"`                                                            // Include program execution logs
	TimeoutSeconds  uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                                   // Monitor timeout (default: 60)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MonitorTransactionRequest) Reset() {
	*x = MonitorTransactionRequest{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorTransactionRequest) ProtoMessage() {}

func (x *MonitorTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorTransactionRequest.ProtoReflect.Descriptor instead.
func (*MonitorTransactionRequest) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *MonitorTransactionRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MonitorTransactionRequest) GetCommitmentLevel() v1.CommitmentLevel {
	if x != nil {
		return x.CommitmentLevel
	}
	return v1.CommitmentLevel(0)
}

func (x *MonitorTransactionRequest) GetIncludeLogs() bool {
	if x != nil {
		return x.IncludeLogs
	}
	return false
}

func (x *MonitorTransactionRequest) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type MonitorTransactionResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Signature            string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`                                                                                          // Transaction signature being monitored
	Status               TransactionStatus      `protobuf:"varint,2,opt,name=status,proto3,enum=protochain.solana.transaction.v1.TransactionStatus" json:"status,omitempty"`                                       // Current transaction status
	Slot                 uint64                 `protobuf:"varint,3,opt,name=slot,proto3" json:"slot,omitempty"`                                                                                                   // Blockchain slot where transaction was processed
	ErrorMessage         string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`                                                                // Error details if transaction failed
	Logs                 []string               `protobuf:"bytes,5,rep,name=logs,proto3" json:"logs,omitempty"`                                                                                                    // Program execution logs (if requested)
	ComputeUnitsConsumed uint64                 `protobuf:"varint,6,opt,name=compute_units_consumed,json=computeUnitsConsumed,proto3" json:"compute_units_consumed,omitempty"`                                     // Compute units consumed by transaction
	CurrentCommitment    v1.CommitmentLevel     `protobuf:"varint,7,opt,name=current_commitment,json=currentCommitment,proto3,enum=protochain.solana.type.v1.CommitmentLevel" json:"current_commitment,omitempty"` // Current commitment level achieved
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *MonitorTransactionResponse) Reset() {
	*x = MonitorTransactionResponse{}
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonitorTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorTransactionResponse) ProtoMessage() {}

func (x *MonitorTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protochain_solana_transaction_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorTransactionResponse.ProtoReflect.Descriptor instead.
func (*MonitorTransactionResponse) Descriptor() ([]byte, []int) {
	return file_protochain_solana_transaction_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *MonitorTransactionResponse) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MonitorTransactionResponse) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *MonitorTransactionResponse) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *MonitorTransactionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *MonitorTransactionResponse) GetLogs() []string {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *MonitorTransactionResponse) GetComputeUnitsConsumed() uint64 {
	if x != nil {
		return x.ComputeUnitsConsumed
	}
	return 0
}

func (x *MonitorTransactionResponse) GetCurrentCommitment() v1.CommitmentLevel {
	if x != nil {
		return x.CurrentCommitment
	}
	return v1.CommitmentLevel(0)
}

var File_protochain_solana_transaction_v1_service_proto protoreflect.FileDescriptor

const file_protochain_solana_transaction_v1_service_proto_rawDesc = "" +
	"\n" +
	".protochain/solana/transaction/v1/service.proto\x12 protochain.solana.transaction.v1\x1a,protochain/solana/transaction/v1/error.proto\x1a2protochain/solana/transaction/v1/transaction.proto\x1a0protochain/solana/type/v1/commitment_level.proto\"\xb4\x01\n" +
	"\x19CompileTransactionRequest\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\x12\x1b\n" +
	"\tfee_payer\x18\x02 \x01(\tR\bfeePayer\x12)\n" +
	"\x10recent_blockhash\x18\x03 \x01(\tR\x0frecentBlockhash\"m\n" +
	"\x1aCompileTransactionResponse\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\"\xc4\x01\n" +
	"\x1aEstimateTransactionRequest\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\x12U\n" +
	"\x10commitment_level\x18\x02 \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x0fcommitmentLevel\"\x88\x01\n" +
	"\x1bEstimateTransactionResponse\x12#\n" +
	"\rcompute_units\x18\x01 \x01(\x04R\fcomputeUnits\x12!\n" +
	"\ffee_lamports\x18\x02 \x01(\x04R\vfeeLamports\x12!\n" +
	"\fpriority_fee\x18\x03 \x01(\x04R\vpriorityFee\"\xc4\x01\n" +
	"\x1aSimulateTransactionRequest\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\x12U\n" +
	"\x10commitment_level\x18\x02 \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x0fcommitmentLevel\"a\n" +
	"\x1bSimulateTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04logs\x18\x03 \x03(\tR\x04logs\"\xa0\x02\n" +
	"\x16SignTransactionRequest\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\x12Z\n" +
	"\fprivate_keys\x18\x02 \x01(\v25.protochain.solana.transaction.v1.SignWithPrivateKeysH\x00R\vprivateKeys\x12G\n" +
	"\x05seeds\x18\x03 \x01(\v2/.protochain.solana.transaction.v1.SignWithSeedsH\x00R\x05seedsB\x10\n" +
	"\x0esigning_method\"j\n" +
	"\x17SignTransactionResponse\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\"8\n" +
	"\x13SignWithPrivateKeys\x12!\n" +
	"\fprivate_keys\x18\x01 \x03(\tR\vprivateKeys\"P\n" +
	"\rSignWithSeeds\x12?\n" +
	"\x05seeds\x18\x01 \x03(\v2).protochain.solana.transaction.v1.KeySeedR\x05seeds\"=\n" +
	"\aKeySeed\x12\x12\n" +
	"\x04seed\x18\x01 \x01(\tR\x04seed\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"\xcc\x01\n" +
	"\"CheckIfTransactionIsExpiredRequest\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\x12U\n" +
	"\x10commitment_level\x18\x02 \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x0fcommitmentLevel\"D\n" +
	"#CheckIfTransactionIsExpiredResponse\x12\x1d\n" +
	"\n" +
	"is_expired\x18\x01 \x01(\bR\tisExpired\"\xc2\x01\n" +
	"\x18SubmitTransactionRequest\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\x12U\n" +
	"\x10commitment_level\x18\x02 \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x0fcommitmentLevel\"\x9e\x02\n" +
	"\x19SubmitTransactionResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12_\n" +
	"\x11submission_result\x18\x02 \x01(\x0e22.protochain.solana.transaction.v1.SubmissionResultR\x10submissionResult\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12]\n" +
	"\x10structured_error\x18\x04 \x01(\v22.protochain.solana.transaction.v1.TransactionErrorR\x0fstructuredError\"\x8c\x01\n" +
	"\x15GetTransactionRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12U\n" +
	"\x10commitment_level\x18\x02 \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x0fcommitmentLevel\"i\n" +
	"\x16GetTransactionResponse\x12O\n" +
	"\vtransaction\x18\x01 \x01(\v2-.protochain.solana.transaction.v1.TransactionR\vtransaction\"\xdc\x01\n" +
	"\x19MonitorTransactionRequest\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12U\n" +
	"\x10commitment_level\x18\x02 \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x0fcommitmentLevel\x12!\n" +
	"\finclude_logs\x18\x03 \x01(\bR\vincludeLogs\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\"\xe5\x02\n" +
	"\x1aMonitorTransactionResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12K\n" +
	"\x06status\x18\x02 \x01(\x0e23.protochain.solana.transaction.v1.TransactionStatusR\x06status\x12\x12\n" +
	"\x04slot\x18\x03 \x01(\x04R\x04slot\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04logs\x18\x05 \x03(\tR\x04logs\x124\n" +
	"\x16compute_units_consumed\x18\x06 \x01(\x04R\x14computeUnitsConsumed\x12Y\n" +
	"\x12current_commitment\x18\a \x01(\x0e2*.protochain.solana.type.v1.CommitmentLevelR\x11currentCommitment*\xb1\x02\n" +
	"\x10SubmissionResult\x12!\n" +
	"\x1dSUBMISSION_RESULT_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bSUBMISSION_RESULT_SUBMITTED\x10\x01\x12'\n" +
	"#SUBMISSION_RESULT_FAILED_VALIDATION\x10\x02\x12*\n" +
	"&SUBMISSION_RESULT_FAILED_NETWORK_ERROR\x10\x03\x12/\n" +
	"+SUBMISSION_RESULT_FAILED_INSUFFICIENT_FUNDS\x10\x04\x12.\n" +
	"*SUBMISSION_RESULT_FAILED_INVALID_SIGNATURE\x10\x05\x12#\n" +
	"\x1fSUBMISSION_RESULT_INDETERMINATE\x10\x06*\x9d\x02\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bTRANSACTION_STATUS_RECEIVED\x10\x01\x12 \n" +
	"\x1cTRANSACTION_STATUS_PROCESSED\x10\x02\x12 \n" +
	"\x1cTRANSACTION_STATUS_CONFIRMED\x10\x03\x12 \n" +
	"\x1cTRANSACTION_STATUS_FINALIZED\x10\x04\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x05\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_DROPPED\x10\x06\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_TIMEOUT\x10\a2\xa4\t\n" +
	"\aService\x12\x8f\x01\n" +
	"\x12CompileTransaction\x12;.protochain.solana.transaction.v1.CompileTransactionRequest\x1a<.protochain.solana.transaction.v1.CompileTransactionResponse\x12\x92\x01\n" +
	"\x13EstimateTransaction\x12<.protochain.solana.transaction.v1.EstimateTransactionRequest\x1a=.protochain.solana.transaction.v1.EstimateTransactionResponse\x12\x92\x01\n" +
	"\x13SimulateTransaction\x12<.protochain.solana.transaction.v1.SimulateTransactionRequest\x1a=.protochain.solana.transaction.v1.SimulateTransactionResponse\x12\x86\x01\n" +
	"\x0fSignTransaction\x128.protochain.solana.transaction.v1.SignTransactionRequest\x1a9.protochain.solana.transaction.v1.SignTransactionResponse\x12\xaa\x01\n" +
	"\x1bCheckIfTransactionIsExpired\x12D.protochain.solana.transaction.v1.CheckIfTransactionIsExpiredRequest\x1aE.protochain.solana.transaction.v1.CheckIfTransactionIsExpiredResponse\x12\x8c\x01\n" +
	"\x11SubmitTransaction\x12:.protochain.solana.transaction.v1.SubmitTransactionRequest\x1a;.protochain.solana.transaction.v1.SubmitTransactionResponse\x12\x83\x01\n" +
	"\x0eGetTransaction\x127.protochain.solana.transaction.v1.GetTransactionRequest\x1a8.protochain.solana.transaction.v1.GetTransactionResponse\x12\x91\x01\n" +
	"\x12MonitorTransaction\x12;.protochain.solana.transaction.v1.MonitorTransactionRequest\x1a<.protochain.solana.transaction.v1.MonitorTransactionResponse0\x01BXZVgithub.com/meshtrade/protochain/lib/go/protochain/solana/transaction/v1;transaction_v1b\x06proto3"

var (
	file_protochain_solana_transaction_v1_service_proto_rawDescOnce sync.Once
	file_protochain_solana_transaction_v1_service_proto_rawDescData []byte
)

func file_protochain_solana_transaction_v1_service_proto_rawDescGZIP() []byte {
	file_protochain_solana_transaction_v1_service_proto_rawDescOnce.Do(func() {
		file_protochain_solana_transaction_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protochain_solana_transaction_v1_service_proto_rawDesc), len(file_protochain_solana_transaction_v1_service_proto_rawDesc)))
	})
	return file_protochain_solana_transaction_v1_service_proto_rawDescData
}

var file_protochain_solana_transaction_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protochain_solana_transaction_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_protochain_solana_transaction_v1_service_proto_goTypes = []any{
	(SubmissionResult)(0),                       // 0: protochain.solana.transaction.v1.SubmissionResult
	(TransactionStatus)(0),                      // 1: protochain.solana.transaction.v1.TransactionStatus
	(*CompileTransactionRequest)(nil),           // 2: protochain.solana.transaction.v1.CompileTransactionRequest
	(*CompileTransactionResponse)(nil),          // 3: protochain.solana.transaction.v1.CompileTransactionResponse
	(*EstimateTransactionRequest)(nil),          // 4: protochain.solana.transaction.v1.EstimateTransactionRequest
	(*EstimateTransactionResponse)(nil),         // 5: protochain.solana.transaction.v1.EstimateTransactionResponse
	(*SimulateTransactionRequest)(nil),          // 6: protochain.solana.transaction.v1.SimulateTransactionRequest
	(*SimulateTransactionResponse)(nil),         // 7: protochain.solana.transaction.v1.SimulateTransactionResponse
	(*SignTransactionRequest)(nil),              // 8: protochain.solana.transaction.v1.SignTransactionRequest
	(*SignTransactionResponse)(nil),             // 9: protochain.solana.transaction.v1.SignTransactionResponse
	(*SignWithPrivateKeys)(nil),                 // 10: protochain.solana.transaction.v1.SignWithPrivateKeys
	(*SignWithSeeds)(nil),                       // 11: protochain.solana.transaction.v1.SignWithSeeds
	(*KeySeed)(nil),                             // 12: protochain.solana.transaction.v1.KeySeed
	(*CheckIfTransactionIsExpiredRequest)(nil),  // 13: protochain.solana.transaction.v1.CheckIfTransactionIsExpiredRequest
	(*CheckIfTransactionIsExpiredResponse)(nil), // 14: protochain.solana.transaction.v1.CheckIfTransactionIsExpiredResponse
	(*SubmitTransactionRequest)(nil),            // 15: protochain.solana.transaction.v1.SubmitTransactionRequest
	(*SubmitTransactionResponse)(nil),           // 16: protochain.solana.transaction.v1.SubmitTransactionResponse
	(*GetTransactionRequest)(nil),               // 17: protochain.solana.transaction.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),              // 18: protochain.solana.transaction.v1.GetTransactionResponse
	(*MonitorTransactionRequest)(nil),           // 19: protochain.solana.transaction.v1.MonitorTransactionRequest
	(*MonitorTransactionResponse)(nil),          // 20: protochain.solana.transaction.v1.MonitorTransactionResponse
	(*Transaction)(nil),                         // 21: protochain.solana.transaction.v1.Transaction
	(v1.CommitmentLevel)(0),                     // 22: protochain.solana.type.v1.CommitmentLevel
	(*TransactionError)(nil),                    // 23: protochain.solana.transaction.v1.TransactionError
}
var file_protochain_solana_transaction_v1_service_proto_depIdxs = []int32{
	21, // 0: protochain.solana.transaction.v1.CompileTransactionRequest.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	21, // 1: protochain.solana.transaction.v1.CompileTransactionResponse.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	21, // 2: protochain.solana.transaction.v1.EstimateTransactionRequest.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	22, // 3: protochain.solana.transaction.v1.EstimateTransactionRequest.commitment_level:type_name -> protochain.solana.type.v1.CommitmentLevel
	21, // 4: protochain.solana.transaction.v1.SimulateTransactionRequest.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	22, // 5: protochain.solana.transaction.v1.SimulateTransactionRequest.commitment_level:type_name -> protochain.solana.type.v1.CommitmentLevel
	21, // 6: protochain.solana.transaction.v1.SignTransactionRequest.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	10, // 7: protochain.solana.transaction.v1.SignTransactionRequest.private_keys:type_name -> protochain.solana.transaction.v1.SignWithPrivateKeys
	11, // 8: protochain.solana.transaction.v1.SignTransactionRequest.seeds:type_name -> protochain.solana.transaction.v1.SignWithSeeds
	21, // 9: protochain.solana.transaction.v1.SignTransactionResponse.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	12, // 10: protochain.solana.transaction.v1.SignWithSeeds.seeds:type_name -> protochain.solana.transaction.v1.KeySeed
	21, // 11: protochain.solana.transaction.v1.CheckIfTransactionIsExpiredRequest.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	22, // 12: protochain.solana.transaction.v1.CheckIfTransactionIsExpiredRequest.commitment_level:type_name -> protochain.solana.type.v1.CommitmentLevel
	21, // 13: protochain.solana.transaction.v1.SubmitTransactionRequest.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	22, // 14: protochain.solana.transaction.v1.SubmitTransactionRequest.commitment_level:type_name -> protochain.solana.type.v1.CommitmentLevel
	0,  // 15: protochain.solana.transaction.v1.SubmitTransactionResponse.submission_result:type_name -> protochain.solana.transaction.v1.SubmissionResult
	23, // 16: protochain.solana.transaction.v1.SubmitTransactionResponse.structured_error:type_name -> protochain.solana.transaction.v1.TransactionError
	22, // 17: protochain.solana.transaction.v1.GetTransactionRequest.commitment_level:type_name -> protochain.solana.type.v1.CommitmentLevel
	21, // 18: protochain.solana.transaction.v1.GetTransactionResponse.transaction:type_name -> protochain.solana.transaction.v1.Transaction
	22, // 19: protochain.solana.transaction.v1.MonitorTransactionRequest.commitment_level:type_name -> protochain.solana.type.v1.CommitmentLevel
	1,  // 20: protochain.solana.transaction.v1.MonitorTransactionResponse.status:type_name -> protochain.solana.transaction.v1.TransactionStatus
	22, // 21: protochain.solana.transaction.v1.MonitorTransactionResponse.current_commitment:type_name -> protochain.solana.type.v1.CommitmentLevel
	2,  // 22: protochain.solana.transaction.v1.Service.CompileTransaction:input_type -> protochain.solana.transaction.v1.CompileTransactionRequest
	4,  // 23: protochain.solana.transaction.v1.Service.EstimateTransaction:input_type -> protochain.solana.transaction.v1.EstimateTransactionRequest
	6,  // 24: protochain.solana.transaction.v1.Service.SimulateTransaction:input_type -> protochain.solana.transaction.v1.SimulateTransactionRequest
	8,  // 25: protochain.solana.transaction.v1.Service.SignTransaction:input_type -> protochain.solana.transaction.v1.SignTransactionRequest
	13, // 26: protochain.solana.transaction.v1.Service.CheckIfTransactionIsExpired:input_type -> protochain.solana.transaction.v1.CheckIfTransactionIsExpiredRequest
	15, // 27: protochain.solana.transaction.v1.Service.SubmitTransaction:input_type -> protochain.solana.transaction.v1.SubmitTransactionRequest
	17, // 28: protochain.solana.transaction.v1.Service.GetTransaction:input_type -> protochain.solana.transaction.v1.GetTransactionRequest
	19, // 29: protochain.solana.transaction.v1.Service.MonitorTransaction:input_type -> protochain.solana.transaction.v1.MonitorTransactionRequest
	3,  // 30: protochain.solana.transaction.v1.Service.CompileTransaction:output_type -> protochain.solana.transaction.v1.CompileTransactionResponse
	5,  // 31: protochain.solana.transaction.v1.Service.EstimateTransaction:output_type -> protochain.solana.transaction.v1.EstimateTransactionResponse
	7,  // 32: protochain.solana.transaction.v1.Service.SimulateTransaction:output_type -> protochain.solana.transaction.v1.SimulateTransactionResponse
	9,  // 33: protochain.solana.transaction.v1.Service.SignTransaction:output_type -> protochain.solana.transaction.v1.SignTransactionResponse
	14, // 34: protochain.solana.transaction.v1.Service.CheckIfTransactionIsExpired:output_type -> protochain.solana.transaction.v1.CheckIfTransactionIsExpiredResponse
	16, // 35: protochain.solana.transaction.v1.Service.SubmitTransaction:output_type -> protochain.solana.transaction.v1.SubmitTransactionResponse
	18, // 36: protochain.solana.transaction.v1.Service.GetTransaction:output_type -> protochain.solana.transaction.v1.GetTransactionResponse
	20, // 37: protochain.solana.transaction.v1.Service.MonitorTransaction:output_type -> protochain.solana.transaction.v1.MonitorTransactionResponse
	30, // [30:38] is the sub-list for method output_type
	22, // [22:30] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_protochain_solana_transaction_v1_service_proto_init() }
func file_protochain_solana_transaction_v1_service_proto_init() {
	if File_protochain_solana_transaction_v1_service_proto != nil {
		return
	}
	file_protochain_solana_transaction_v1_error_proto_init()
	file_protochain_solana_transaction_v1_transaction_proto_init()
	file_protochain_solana_transaction_v1_service_proto_msgTypes[6].OneofWrappers = []any{
		(*SignTransactionRequest_PrivateKeys)(nil),
		(*SignTransactionRequest_Seeds)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protochain_solana_transaction_v1_service_proto_rawDesc), len(file_protochain_solana_transaction_v1_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protochain_solana_transaction_v1_service_proto_goTypes,
		DependencyIndexes: file_protochain_solana_transaction_v1_service_proto_depIdxs,
		EnumInfos:         file_protochain_solana_transaction_v1_service_proto_enumTypes,
		MessageInfos:      file_protochain_solana_transaction_v1_service_proto_msgTypes,
	}.Build()
	File_protochain_solana_transaction_v1_service_proto = out.File
	file_protochain_solana_transaction_v1_service_proto_goTypes = nil
	file_protochain_solana_transaction_v1_service_proto_depIdxs = nil
}
